### ISSUE TITLE
显示问题

### ISSUE THREAD

**Issue by Suiyi-Light** [solstice23/argon-theme#100]
不知道咋描述
![屏幕截图 2020-10-18 202233.png](https://image.suiyil.cn/2020/10/屏幕截图-2020-10-18-202233.png)
初步认为是Fancybox问题
切回Zoomify 正常
使用经典编辑器添加图片（存在说明）

问题链接https://blog.suiyil.cn/1588.html

**Comment by solstice23** [comment]
能提供一下该页面未经 Argon 处理的 HTML 源码吗

**Comment by solstice23** [comment]
[尝试修复](https://github.com/solstice23/argon-theme/commit/b354ab726bd518a8cac2719bef61efb97281d26b)了这个问题，从仓库拉一份最新的代码试试（没法 Release），如果还是不行，考虑不用正则用解析库写了（

**Comment by Suiyi-Light** [comment]
> [尝试修复](https://github.com/solstice23/argon-theme/commit/b354ab726bd518a8cac2719bef61efb97281d26b)了这个问题，从仓库拉一份最新的代码试试（没发 Release），如果还是不行，考虑不用正则，用解析库写了（

还是不行
https://image.suiyil.cn/2020/10/1588.txt
文本自行取用

**Comment by solstice23** [comment]
Debug 了几个小时，最后发现不是正则或 HTML Parser 的问题，是嵌套在短代码中的 HTML Tag 在经 Argon 处理后又经过了一层 WP 的申必处理，导致 Tag 提前闭合，提高了 filter 的优先级就解决了（（（

**Comment by Suiyi-Light** [comment]
> Debug 了几个小时，最后发现不是正则或 HTML Parser 的问题，是嵌套在短代码中的 HTML Tag 在经 Argon 处理后又经过了一层 WP 的申必处理，导致 Tag 提前闭合，提高了 filter 的优先级就解决了（（（

友链图标也被识别了，格式变了..

**Comment by solstice23** [comment]
修了，等会发 Release
