### ISSUE TITLE
`*.fonts.googleapis.com` 打开很慢

### ISSUE THREAD

**Issue by zhao305149619** [solstice23/argon-theme#101]
*.fonts.googleapis.com
在点击分类链接的时候，会走到这个导致一直加载很慢，挂梯子之后秒开，是我们个人环境问题吗？

**Comment by solstice23** [comment]
国内引用 Google 字体比较慢，下几个版本会增加开关或内置 Google 字体

**Comment by solstice23** [comment]
已增加开关
