### ISSUE TITLE
首页加载缓慢，引入fonts.googleapis.com/css字体后引起的

### ISSUE THREAD

**Issue by 1Gbps** [solstice23/argon-theme#102]
在调试的时候开启了disable cache，意外发现首页加载了好久刷新不出来。

看了一下network，发现是首页引用了google资源文件，加载缓慢引起的：
`https://fonts.googleapis.com/css?family=Open+Sans%3A300%2C400%2C600%2C700%7CNoto+Serif+SC%3A300%2C600&display=swap&ver=5.5.1`

**Comment by solstice23** [comment]
#101 国内引用 Google 字体比较慢，下几个版本会增加开关或内置 Google 字体

**Comment by solstice23** [comment]
已增加开关
