### ISSUE TITLE
WordPress 后台找不到 「Argon 设置」选项

### ISSUE THREAD

**Issue by QingxuMo** [solstice23/argon-theme#103]
截图如下图所示

![WordPress 后台](https://one.qingxu.ga/pictures/Pictures/Screenshot_20201022-003159601.jpg)

这是 bug 还是说 Argon 没有独立的主题设置（

**Comment by solstice23** [comment]
bug，有可能是和插件冲突了，禁用插件试试看，或检查主题文件是否完整，之前有个相同问题的是因为打开了 "All In One WP Security" 插件的 "禁止修改文件" 选项

**Comment by QingxuMo** [comment]
我并没有找到类似选项。

我目前使用的安全插件是 Wordfence，里面并没有任何有关「禁止修改文件」选项。

我尝试过 git 直接 clone 仓库到 themes 目录（有进行修改文件权限）或直接下载 release 的版本上传，但都没有找到主题设置选项。

我再新建了一个 WordPress 测试站点，结果依然相同。

其他我使用过的主题如 Sakura 和 Akina 都没有出现该类问题。

LNMP 环境 和 WordPress 是我半手建的，不是类似宝塔这样的面板自动部署生成的，所有自定义的配置文件基本上是我手打的，我也没有进行任何关于目录修改权限的限制。

匪夷所思。

**Comment by solstice23** [comment]
奇怪，Argon 用的是 `add_menu_page` 这个函数来添加菜单 ([function.php 2353 行](https://github.com/solstice23/argon-theme/blob/master/functions.php#L2353))，按理说不应该没有菜单，有点玄学（

**Comment by 1328189205** [comment]
兄弟 我也没有设置菜单

**Comment by QingxuMo** [comment]
> 兄弟 我也没有设置菜单

你有什么启用什么插件或特殊自定义设置吗？😂我们或许可以比对一下找相同点。

**Comment by bigcyy** [comment]
我把插件全关了也没有
