### ISSUE TITLE
文章字数显示不准确

### ISSUE THREAD

**Issue by iiYK** [solstice23/argon-theme#108]
文章Meta信息中显示的文章字数明显少很多，是否可以利用写文章时内容结构菜单中的字数？
WordPress : 5.4.2
argon : 1.1.2.1

**Comment by stimw** [comment]
同问题

**Comment by solstice23** [comment]
统计字数优化过一次，现在的逻辑是"中文字数+英文词数"

**Comment by solstice23** [comment]
能给一个文章例子吗

**Comment by iiYK** [comment]
比如你的这篇文章：https://solstice23.top/archives/999
