### ISSUE TITLE
希望有个注释功能

### ISSUE THREAD

**Issue by crowya** [solstice23/argon-theme#110]
鼠标碰到右上角标时浮现注释内容
![参考知乎](https://user-images.githubusercontent.com/61354956/98513887-92a17300-22a3-11eb-811e-0b37d6f5daec.gif)
参考文章：https://zhuanlan.zhihu.com/p/252615892

**Comment by crowya** [comment]
感谢大佬更新！！！刚试了下，有几个bug，编辑了几次文章后发现第一条注释的编号变成从10开始了，末尾的参考出现重复内容。
比如我有三条注释A、B、C，结果变成了
1.A
2.B
3.C
4.A
5.B
6.C
7.A
8.B
9.C
10.A
……

**Comment by solstice23** [comment]
@crowya 能发下链接和文章源码吗

**Comment by crowya** [comment]
https://crowya.com/%E4%BF%9D%E7%A0%94%E8%BE%B9%E7%BC%98%E5%9B%9E%E5%BF%86%E5%BD%95

**Comment by crowya** [comment]
![image](https://user-images.githubusercontent.com/61354956/99142569-32d70d80-2691-11eb-9ccd-101eba19a6c6.png)
原文是这样用的
另外可以把参考的标题设为H1并索引到目录中去吗

**Comment by solstice23** [comment]
应该可以了
