### ISSUE TITLE
post-template 284行错误

### ISSUE THREAD

**Issue by doublog** [solstice23/argon-theme#112]
Warning:  count(): Parameter must be an array or an object that implements Countable in /public_html/wp-includes/post-template.php on line 284
用别的主题没发现这个错误。。

**Comment by solstice23** [comment]
是 wordpress 对 PHP 7.2 的兼容性问题

**Comment by doublog** [comment]
> 是 wordpress 对 PHP 7.2 的兼容性问题

那这个该如何处理呢？我php版本是7.4

**Comment by solstice23** [comment]
有可能是插件冲突 禁用下插件看看

**Comment by doublog** [comment]
> 有可能是插件冲突 禁用下插件看看

好的，我试下。谢谢！
