### ISSUE TITLE
修改functions.php出现问题

### ISSUE THREAD

**Issue by zgyzgyzgyzgy** [solstice23/argon-theme#116]
出现了问题。您的修改可能未被保存。请重试。您也可能需要通过FTP手工修复并上传文件。

argon版本：1.1.4

以前从未出现

**Comment by solstice23** [comment]
不建议使用 Wordpress 自带的编辑器修改主题文件，请使用其他途径修改。
同时也不建议直接修改 functions.php，因为主题更新会覆盖之前的 function.php，修改会全部失效，需要重新修改。如果想增加方法，推荐使用插件的形式。
