### ISSUE TITLE
建议：添加自动夜间模式

### ISSUE THREAD

**Issue by Jizyjiang** [solstice23/argon-theme#12]
才用这个主题，很感谢！🙏
有自动调节夜间模式的话这是极好的

**Comment by solstice23** [comment]
这个 Feature 自版本 v0.880 以来已经有了。
![screenshot](https://i.loli.net/2020/03/22/c2v1Rt3QJTSzpBx.png)

**Comment by Jizyjiang** [comment]
嗯嗯～ 谢谢
