### ISSUE TITLE
主题不能播放视频

### ISSUE THREAD

**Issue by merlinmxn** [solstice23/argon-theme#122]
wordpress版本的，用旧版的编辑器插入视频，文章内的视频都不能播放

到了前台主题，查看源代码，变成了这样，视频路径不见了：
`<video width='640' height='352' controls><source src=''></video>`

**Comment by Suiyi-Light** [comment]
在文本中将mp4=""（或其他）换成url=“”可以播放

不过希望作者可以对这个做下兼容
