### ISSUE TITLE
希望增加一项标题栏小图标的设置

### ISSUE THREAD

**Issue by merlinmxn** [solstice23/argon-theme#123]
在浏览器的收藏夹，和浏览器的标题栏，网站的图标默认还是WordPress的， 希望主题可以增加一项这个图标的设置

**Comment by solstice23** [comment]
"Wordpress 自定义" 里面可以设置这个

**Comment by merlinmxn** [comment]
> "Wordpress 自定义" 里面可以设置这个

找到了，一直没注意看，谢谢😜
