### ISSUE TITLE
文章加载图片有问题

### ISSUE THREAD

**Issue by Humengchao** [solstice23/argon-theme#125]
文章中有一些图片放在华为云的对象存储里，按理说不会出现访问异常的。但是应用这个主题再点开文章后图片一直在加载中，而且右上角也一直在转圈，点开图片或者重新刷新界面就能够正常看图。  url:  https://wqnmd.net  随便一篇文章都是这样

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/102682091-ad033080-4201-11eb-94a4-57d6462c87d6.png)
和插件有冲突？

如果用了 Editor.md 的话开兼容模式

**Comment by Humengchao** [comment]
嗯嗯，开启兼容模式就好了，谢谢大佬
