### ISSUE TITLE
评论的邮件提醒，是要设置什么才能发送呢？

### ISSUE THREAD

**Issue by merlinmxn** [solstice23/argon-theme#126]
评论的邮件提醒，是要设置什么wordpress才能发送出去呢？

**Comment by potoo0** [comment]
允许主题设置中的 **是否允许评论者接收评论回复邮件提醒**，并安装邮件服务的插件及配置，我使用的插件是 **WP Mail SMTP**，其可以配置 gmail/QQ 等等

**Comment by merlinmxn** [comment]
谢谢回复，已解决
