### ISSUE TITLE
与百度云朗读插件有冲突

### ISSUE THREAD

**Issue by merlinmxn** [solstice23/argon-theme#128]
主题与Hylsay Text Reading百度云语音合成插件有冲突，启用该插件后，文中图片不能正常显示

**Comment by merlinmxn** [comment]
并且文章目录也不能显示了

**Comment by yzxoi** [comment]
应该是 jQuery 引用版本不同导致冲突。

**Comment by yzxoi** [comment]
百度云朗读插件使用的 jQuery 是远古版本 1.7.1，目前 Argon 使用的是 3.5.1 版本，可以自行到插件目录 /js/jquery.min.js 修改成最新的 jQuery 就好了。
