### ISSUE TITLE
v0.923 的 bug 和 feature 建议

### ISSUE THREAD

**Issue by imByteCat** [solstice23/argon-theme#13]
Bug:
- 直接安装 `v0.923` 会显示缺失 `functions.php`，使用 `v0.922` 升级上来可以解决这个问题

Feature:
- 希望能添加代码高亮功能

**Comment by solstice23** [comment]
> 直接安装 v0.923 会显示缺失 functions.php，使用 v0.922 升级上来可以解决这个问题
无法复现，检查过了 v0.923 的包也是完整的

> 希望能添加代码高亮功能
可以先使用高亮插件，后续考虑内置

**Comment by imByteCat** [comment]
> > 直接安装 v0.923 会显示缺失 functions.php，使用 v0.922 升级上来可以解决这个问题
> 
> 无法复现，检查了 v0.923 的包也是完整的
> 
> > 希望能添加代码高亮功能
> 
> 可以先使用高亮插件，后续考虑内置

该 bug 我这边尝试在 WordPress 下复现，结果多次无果，可能是我设置上的问题；
至于代码高亮的 feature 我在使用 WP GitHub MD 插件后也得到了解决。

总之，感谢您的迅速答复，希望主题能越做越好。
