### ISSUE TITLE
argontheme.js导致网站连接不完全安全，网站信息那里是个叹号

### ISSUE THREAD

**Issue by 12313kaihuang** [solstice23/argon-theme#130]
配置了证书之后并没有锁的标志，而是一个叹号。F12看了一下警告是argontheme.js里面引用了我的网站地址（http形式），应该是这个原因吧，用自带的主题就不会有这个问题。

**Comment by solstice23** [comment]
@12313kaihuang 设置里把网站链接改成 HTTPS

**Comment by 12313kaihuang** [comment]
@solstice23  可以了 感谢

**Comment by 12313kaihuang** [comment]
solved
