### ISSUE TITLE
图片放大浏览bug

### ISSUE THREAD

**Issue by micksu** [solstice23/argon-theme#137]
WP5.6版本，如果都禁用fancybox和zoomify，鼠标hover带链接的图片会出现黑色线条动画，不知是BUG还是有意为之。
只用fancybox时，点击图片放大不会使用“链接媒体“文件，仍然是img标签的图片（比如缩略图）。

**Comment by solstice23** [comment]
算是 feature，文章中 a 标签 hover 的时候会有下划线，考虑到这个问题现已加入 `no-hover-underline` 类，在 a 中加入这个类 hover 时不会出现下划线。
