### ISSUE TITLE
使用主题之后网站健康状态提示三个错误

### ISSUE THREAD

**Issue by jingling2000** [solstice23/argon-theme#139]
![QQ截图20210113150750](https://user-images.githubusercontent.com/32089660/104417998-39aacf80-55b1-11eb-9706-b55855189007.jpg)
主题的版本为：1.1.5

**Comment by HolgerHuo** [comment]
您好～想请问一下 这个bug会对wp有什么影响w

**Comment by HolgerHuo** [comment]
感谢开发w~
