### ISSUE TITLE
顶部菜单自定义链接不能在新建标签页打开

### ISSUE THREAD

**Issue by DefiedParty** [solstice23/argon-theme#14]
你好，我遇到了顶部菜单自定义链接不能在新建标签页打开的问题（已经勾选在新建标签页中打开链接）：
![image](https://user-images.githubusercontent.com/44311872/78258889-792a9280-752e-11ea-915e-949ef12cdc1f.png)

我参阅了：https://github.com/solstice23/argon-theme/issues/2
但是顶部菜单自定义链接仍然存在这个问题
谢谢你，非常喜欢argon。

**Comment by solstice23** [comment]
请问这个复选框在后台设置中哪里，我没找到😂

**Comment by DefiedParty** [comment]
> 请问这个复选框在后台设置中哪里，我没找到😂

哈哈，就是在菜单里新建一个自定义链接，然后展开链接项目里面有这个复选框

**Comment by solstice23** [comment]
好像没有这个欸

![1](https://i.loli.net/2020/04/02/Y5WNkpHn92DJdR8.png)

![2](https://i.loli.net/2020/04/02/PAbpyNJfDkv8wVi.png)

**Comment by DefiedParty** [comment]
![image](https://user-images.githubusercontent.com/44311872/78267882-10491780-753a-11ea-9da6-09b796a4b482.png)

**Comment by solstice23** [comment]
OK，更新了，Fixed
