### ISSUE TITLE
官网换个好些的服务器吧，一些文档想看都看不到

### ISSUE THREAD

**Issue by lyryblog** [solstice23/argon-theme#147]
![image](https://user-images.githubusercontent.com/61700209/106117364-e9756500-618d-11eb-8784-3aa59d7fe428.png)

**Comment by solstice23** [comment]
域名到期忘记续了，到时候把文档迁移到 Github 吧

**Comment by lyryblog** [comment]
> 域名到期忘记续了，到时候把文档迁移到 Github 吧

OK
