### ISSUE TITLE
问题与建议

### ISSUE THREAD

**Issue by youthriverside** [solstice23/argon-theme#149]
### 使用Really-Simple-SSL插件会报错，站点健康处*有时* 报错
![image](https://user-images.githubusercontent.com/63176620/106279253-15b8e080-6277-11eb-9fd7-2dec5a8466a8.png)
### 工具栏（功能）部分加以美化
![image](https://user-images.githubusercontent.com/63176620/106279077-d4283580-6276-11eb-8d91-514167d96d45.png)
### 图片分辨率过高时会发生以下情况
![image](https://user-images.githubusercontent.com/63176620/106279361-46007f00-6277-11eb-8338-34bdf6bb88bb.png)
### 文章页下在无特色图片时将文字凸出（或加遮罩），如图，感官上难以发觉，不够明显
![image](https://user-images.githubusercontent.com/63176620/106279810-fa020a00-6277-11eb-8708-8a36692a00b8.png)

**Comment by yzxoi** [comment]
相似文章样式已修改 #156 ，应该下个版本会更新
