### ISSUE TITLE
超过百行的代码行数显示会重叠在一起

### ISSUE THREAD

**Issue by TomyJan** [solstice23/argon-theme#154]
emm这应该算是主题的问题吧

图
![image](https://user-images.githubusercontent.com/67973160/107110271-8cf70180-6881-11eb-8db5-90c275981371.png)

示例 https://blog.tomys.top/2021-02/2021newyear/

**Comment by solstice23** [comment]
已修复，但还没发 Release，可以先 Clone 一份最新的代码

**Comment by TomyJan** [comment]
> 已修复，但还没发 Release，可以先 Clone 一份最新的代码

好的，感谢。
另祝新年快乐！
