### ISSUE TITLE
请教一下页面背景的动态特效怎么加的

### ISSUE THREAD

**Issue by Kyou12138** [solstice23/argon-theme#155]
如题，感谢~

**Comment by solstice23** [comment]
https://github.com/VincentGarreau/particles.js

**Comment by lxy6515** [comment]
评论系统也是后来加的吗   我的gitalk评论一直没加上

**Comment by solstice23** [comment]
Gitalk 是一开始移植时候就加了

**Comment by lxy6515** [comment]
是这样的&nbsp;&nbsp;&nbsp;现在gitalk连不上&nbsp;&nbsp;&nbsp;网上查了一下是被作者限制了&nbsp;&nbsp;&nbsp;网上教程基本都是用不了的&nbsp;&nbsp;所以我在想换一个评论系统&nbsp;&nbsp;&nbsp;刚才回过去看的时候好像所有argon站都换了评论系统


---原始邮件---
发件人: &quot;solstice23&quot;<notifications@github.com&gt;
发送时间: 2021年2月23日(周二) 晚上9:23
收件人: &quot;solstice23/argon-theme&quot;<argon-theme@noreply.github.com&gt;;
抄送: &quot;l x y&quot;<1342343511@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题: Re: [solstice23/argon-theme] 请教一下页面背景的动态特效怎么加的 (#155)




 
Gitalk 是一开始移植时候就加了
 
&mdash;

**Comment by solstice23** [comment]
> 是这样的&nbsp;&nbsp;&nbsp;现在gitalk连不上&nbsp;&nbsp;&nbsp;网上查了一下是被作者限制了&nbsp;&nbsp;&nbsp;网上教程基本都是用不了的&nbsp;&nbsp;所以我在想换一个评论系统&nbsp;&nbsp;&nbsp;刚才回过去看的时候好像所有argon站都换了评论系统
> […](#)
> ---原始邮件--- 发件人: &quot;solstice23&quot;<notifications@github.com&gt; 发送时间: 2021年2月23日(周二) 晚上9:23 收件人: &quot;solstice23/argon-theme&quot;<argon-theme@noreply.github.com&gt;; 抄送: &quot;l x y&quot;<1342343511@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;; 主题: Re: [solstice23/argon-theme] 请教一下页面背景的动态特效怎么加的 (#155) Gitalk 是一开始移植时候就加了 &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

？？？
一个开源，调用 Github API 的前端库是如何被作者限制的？

可能的原因：
1. Gitalk 配置错误
2. 某众所周知的原因，国内访问 Github API 被阻断了

另外这个 Repo 是 Wordpress 版本的，不带 Gitalk，Gitalk 在 Hexo 版本中。"`好像所有argon站都换了评论系统`"，一个是 Wordpress 一个是 Hexo，评论系统当然不一样
