### ISSUE TITLE
[bug]Mathematical formula rendering problem 数学公式渲染问题

### ISSUE THREAD

**Issue by OldTaoge** [solstice23/argon-theme#163]
Hello Everyone:
I found some problems when remdering mathematical formulas.
Here are the details of the problem.
Theme Ver .`v1.1.6`
The problems found in use are as follows:
- When rendering formulas using Mathjax 3,`\\` line break is not recognized
- When rendering formulas using Mathjax 2, it cannot be rendered when entering from other pages (including the home page), and the page needs to be refreshed manually
- When  rendering formulas using Katex, the part with multi-line formulas (i.e. `$$ formula $$`) cannot be rendered
- Example: [Logarithmic function](https://blog.oldtaoge.space/2021/02/18/%e5%af%b9%e6%95%b0%e5%87%bd%e6%95%b0/) (Now usingMathjax 2)
Source File:
``$$
如果a\gt0,且a\neq1,M\gt0,N\gt0,那么: \\
(1) \log_a(M\cdot N)=\log_aM+\log_aN \\
(2) \log_a\frac{M}{N}=\log_aM-\log_aN \\
(3) \log_aM^n=n\log_aM(n\in R)
$$``
-------------------------
各位好:
我在渲染数学公式时遇到了一些问题
以下是问题的详情
主题版本`v1.1.6`
在使用中发现的问题如下:
- 使用 Mathjax 3渲染公式时,`\\`换行无法识别
- 使用 Mathjax 2渲染公式时,从其他页面(包括首页)进入无法渲染,需要手动刷新页面
- 使用 Katex 渲染公式时, 用多行公式 (即:`$$ 公式 $$`)的部分无法渲染
Example: [对数函数](https://blog.oldtaoge.space/2021/02/18/%e5%af%b9%e6%95%b0%e5%87%bd%e6%95%b0/) (现在使用的是Mathjax 2)
源文件:
对数的运算性质
``$$
如果a\gt0,且a\neq1,M\gt0,N\gt0,那么: \\
(1) \log_a(M\cdot N)=\log_aM+\log_aN \\
(2) \log_a\frac{M}{N}=\log_aM-\log_aN \\
(3) \log_aM^n=n\log_aM(n\in R)
$$``

**Comment by yzxoi** [comment]
> 使用 Mathjax 3渲染公式时,``\\``换行无法识别

Mathjax_v3 并不支持使用 ``\\`` 进行换行
> dpvc：
Linebreaks are not yet implemented in version 3. This is one of the significant features from version 2 that been ported to version 3.
https://github.com/mathjax/MathJax/issues/2312

**Comment by OldTaoge** [comment]
> Mathjax_v3 并不支持使用 `\\` 进行换行
好的,感谢您的解答,在使用Mathjax 2和Katex还是有一些问题的,还麻烦您看一下

**Comment by yzxoi** [comment]
> 使用 Katex 渲染公式时, 用多行公式 (即:``$$ 公式 $$``)的部分无法渲染

Katex 正常渲染，Katex 和 Mathjax 有所不同，有些宏包无法在 Katex 中使用，比如 align，经测试，您所提供的对数函数可以正常渲染。

**Comment by yzxoi** [comment]
> 使用 Mathjax 2渲染公式时,从其他页面(包括首页)进入无法渲染,需要手动刷新页面

应该是 Mathjax_v2 和 pjax 的不兼容问题，已修复 #164

**Comment by OldTaoge** [comment]
还感谢您的耐心指导,我知道这段公式是能够正确渲染的

![katex_org-rendered](https://user-images.githubusercontent.com/51744784/108440406-06352200-728e-11eb-8dc6-6409b3b754b7.jpg)


但是在[文章](https://blog.oldtaoge.space/2021/02/18/对数函数/)中却并没有正确渲染

这是文章的HTML:

![html-source](https://user-images.githubusercontent.com/51744784/108440380-fae1f680-728d-11eb-8b45-cca01df4fc6e.jpg)

它使用主题中KaTex渲染出来后是这样的:

![katex-rendered](https://user-images.githubusercontent.com/51744784/108440360-ef8ecb00-728d-11eb-8080-22dfcd020513.jpg)

我不确定是不是因为我的操作有问题导致了无法渲染

我尝试过在文章编辑器中添加和删除多行公式符号`$$`但均没有效果

-----------------------------

**Comment by yzxoi** [comment]
@OldTaoge 刚看了一下您的文章，发现您并没有使用 Mathjax_v2 或 Katex，您使用的是 Mathjax_v3
![image](https://user-images.githubusercontent.com/46484956/108440752-b014ae80-728e-11eb-9930-ce5454d860f7.png)

**Comment by OldTaoge** [comment]
我原来一直开的是Mathjax_v3(因为能够渲染),今天已经切换到KaTex,可能是缓存的原因没有更新到您的浏览器,我已经禁用和刷新服务器的缓存,希望您刷新下浏览器的缓存,谢谢

**Comment by yzxoi** [comment]
@OldTaoge 请问您能发个截图您文章的该部分编辑页面吗？

**Comment by OldTaoge** [comment]
这是经典编辑器的可视化部分:

![editor-humanreadable](https://user-images.githubusercontent.com/51744784/108441573-590fd900-7290-11eb-82f8-77c9b70fb0d5.jpg)

这是经典编辑器的文本部分:

![editor-text](https://user-images.githubusercontent.com/51744784/108441576-5a410600-7290-11eb-807b-8cd9ff0e5582.jpg)

我也尝试过古腾堡编辑器,WP Editor.md,但他们都不能很好的让KaTex渲染多行公式

**Comment by yzxoi** [comment]
@OldTaoge 您使用该编辑器使其换行的原因是 <br> 标签，但这也使您的 Katex 无法正常渲染，请您删除 <br> 标签后重试。

**Comment by OldTaoge** [comment]
嗯嗯问题解决了,感谢您的帮助,谢谢

**Comment by solstice23** [comment]
fixed，因为之前更改过 Pjax 的逻辑造成了 Mathjax V2 在 Pjax 加载后的渲染失效

**Comment by solstice23** [comment]
[v1.1.7](https://github.com/solstice23/argon-theme/releases/tag/v1.1.7) Release 已推送
