### ISSUE TITLE
说说保存或发表后依旧弹窗“系统可能不会保存你所做的任何更改”

### ISSUE THREAD

**Issue by youthriverside** [solstice23/argon-theme#165]
![image](https://user-images.githubusercontent.com/63176620/108442100-7002fb00-7291-11eb-9d33-04abe821f553.png)
### 如图所示

**Comment by yzxoi** [comment]
这应该是 Wordpress 的问题吧？

**Comment by solstice23** [comment]
wordpress 为防止误关闭而弹窗，无关主题
