### ISSUE TITLE
当验证码为除法时输入正确答案会提示错误

### ISSUE THREAD

**Issue by woshoxxx** [solstice23/argon-theme#168]
https://gong-cx.top/comments/
我遇到的验证码为40/8
当我输入5再评论时，会提示验证码错误
![OZJ~X~L@TW7CNTU%M@DVRVB](https://user-images.githubusercontent.com/51288473/108947073-b80f8c80-769a-11eb-8ddb-227b9e6a5efa.png)
![2E(0L64ZVMGK%R @8FB(EYL](https://user-images.githubusercontent.com/51288473/108947091-bfcf3100-769a-11eb-8bee-1c120bf6ba0b.png)

**Comment by yzxoi** [comment]
您的博客上并没有开启评论验证码吧

**Comment by woshoxxx** [comment]
刷新了一下恢复正常了

**Comment by solstice23** [comment]
在某次更新的时候，确实存在这个问题，第一次访问时验证码错误，但这个问题已经被修复

请检查是否符合以下几点之一：
1. 初次访问页面
2. 在其他页面评论过
