### ISSUE TITLE
启用或者预览时报错

### ISSUE THREAD

**Issue by crowya** [solstice23/argon-theme#17]
Warning: file_get_contents(/www/wwwroot/wordpress/wp-content/themes/argon/footer.php): failed to open stream: No such file or directory in /www/wwwroot/wordpress/wp-content/themes/argon-theme-master/functions.php on line 1143
阅读百分比不正常，目录定位不正常…
![image](https://user-images.githubusercontent.com/61354956/78479907-f5fc7d00-7777-11ea-82b6-738a8d0ae313.png)

**Comment by solstice23** [comment]
安装主题时请下载 [Release](https://github.com/solstice23/argon-theme/releases) 页面的 `argon.zip`，而不是下载整个 repo。

解决方法：
在 [Release](https://github.com/solstice23/argon-theme/releases) 页面下载最新的 `argon.zip` ，然后重新安装主题。或者在 `Wordpress 目录/wp-content/themes` 下重命名主题文件夹为 `argon`。
