### ISSUE TITLE
启用主题时出现致命错误。

### ISSUE THREAD

**Issue by 928882650** [solstice23/argon-theme#173]
您好：

WordPress从版本5.2开始，能够检测到您站点上的插件或主题造成了致命错误，并向您发送自动的通知邮件。

这次，WordPress发现了您的主题造成的错误：argon。

首先，访问您的站点（https://www.aigeek.top/ ）并查看有无可见的问题。然后，访问发生错误的页面（https://www.aigeek.top/wp-admin/themes.php?activated=true ）并查看有无问题。

请联系您的主机提供商来获得帮助及调查此问题。

如果您的站点看上去不正常，且您不能正常访问仪表盘，WordPress现在有了特殊的“恢复模式”，能够让您安全地登录仪表盘并调查问题。
在寻求关于此问题的帮助时，您可能需要提供以下信息：
WordPress版本5.6.2
当前主题：argon（版本1.1.7）
当前插件：（版本）
PHP版本7.3.22

错误详情
============
错误类别E_ERROR发生在文件/data/mystack/sites/www.aigeek.top/www/wp-content/themes/argon-theme-master/functions.php的1658行。错误信息：Cannot redeclare hex2rgb() (previously declared in /data/mystack/sites/www.aigeek.top/www/wp-content/plugins/1565957449-live2d/main.php:54)

**Comment by yzxoi** [comment]
因为 live2d 插件的 hex2rgb 函数与 Argon 的函数重名了，您可以尝试停用 live2d 插件，再看看是否正常。
