### ISSUE TITLE
【建议】增加关闭顶部Banner(封面)的选项

### ISSUE THREAD

**Issue by waahaa** [solstice23/argon-theme#174]
主题很棒，真正做到了简洁美观，且布局落落大方，这里有一个小小的建议
在不设置Banner背景图，且开启Banner透明化的情况下，会显得顶部很留白过多，显得很空，能否增加关闭顶部Banner的选项？

**Comment by cddehsy** [comment]
同意啊，

**Comment by WangLiwen1994** [comment]
+1，希望可以增加一个关闭选项
