### ISSUE TITLE
左侧栏作者板块显示错误

### ISSUE THREAD

**Issue by lz00qs** [solstice23/argon-theme#177]
左侧栏作者板块的站点概览中的分类显示的分类数量是实际分类数量+1，例如您的博客中分类只有4种，显示的是五种

**Comment by yzxoi** [comment]
@lz00qs 因为wp的分类数量的确是5，但是有一类中没有任何文章，所以在分类中显示只有4种，的确是个bug。

**Comment by lz00qs** [comment]
> @lz00qs 因为wp的分类数量的确是5，但是有一类中没有任何文章，所以在分类中显示只有4种，的确是个bug。

已解决，在显示界面当中添加一个名为未分类的栏目就好了
