### ISSUE TITLE
最新Release出现致命错误

### ISSUE THREAD

**Issue by lushuyu** [solstice23/argon-theme#18]
错误代码如下：
```php
Notice: Undefined variable: comment_data in /home/wwwroot/default/wp-content/themes/argon/functions.php on line 596

Fatal error: Cannot declare class Parsedown, because the name is already in use in /home/wwwroot/default/wp-content/themes/argon/parsedown.php on line 16
```
看起来像重复定义，我现在正在尝试老版本。

**Comment by lushuyu** [comment]
看起来我已经找到了这个问题的解决方案，把`functions.php`中的`class Parsedown`改掉就好了。我正在尝试搞一个PR /kel

**Comment by lushuyu** [comment]
#19 已经提交了一个PR

**Comment by solstice23** [comment]
看了一下，是 `theme-update-checker` 这个库中也有一份旧版本的 `Parsedown`，与现存的 `Parsedown` 冲突造成的。重复定义在特定的环境会抛 `Fatal Error`。
修改 `parsedown.php` 中的重复类名可以解决冲突问题，`function.php` 中用到该版本的 `Parsedown` 的地方也要一起修改。

> Notice: Undefined variable: comment_data in /home/wwwroot/default/wp-content/themes/argon/functions.php on line 596
Fixed

**Comment by lushuyu** [comment]
果然我说为什么把类名改掉不会报错，原来是重复定义了。
