### ISSUE TITLE
有没有一个菜单设置文档，例如作者顶部的归档和菜单是如何做到的？

### ISSUE THREAD

**Issue by jianpingzhao** [solstice23/argon-theme#180]

**Comment by yzxoi** [comment]
请自行查看 [官方文档-菜单](https://argon-docs.solstice23.top/#/menu)

**Comment by yzxoi** [comment]
[归档时间轴](https://argon-docs.solstice23.top/#/archives)

**Comment by jianpingzhao** [comment]
@yzxoi 感谢回复，官方文档写的太简单了，”没头没尾“(请原谅我这么说)，有没有示例啊。

**Comment by jianpingzhao** [comment]
”例如新建页面“，这个如何新建，可能问题有的小白

**Comment by yzxoi** [comment]
> @yzxoi 感谢回复，官方文档写的太简单了，”没头没尾“(请原谅我这么说)，有没有示例啊。

文档正在补充之中，欢迎提 PR 和 Issues 到 argon-theme-docs，感谢提出，最近有空会更。

**Comment by jianpingzhao** [comment]
@yzxoi 能不能给个指导，用了快一年了，就是想要顶部栏不会弄，我想到就是自定义菜单然后贴链接做，但是不知道归档、标签的地址什么，可不可以以此为例给知道一下，多谢你了。

**Comment by yzxoi** [comment]
![image](https://user-images.githubusercontent.com/46484956/111429221-a702ea00-8733-11eb-8aed-ae907f14a0e2.png)
![image](https://user-images.githubusercontent.com/46484956/111429305-c8fc6c80-8733-11eb-8ce5-7ec70deb94eb.png)

**Comment by jianpingzhao** [comment]
@yzxoi 万分感谢，已经搞定了
