### ISSUE TITLE
【建议】父主题的方法使用可插拔函数以便于子主题覆盖

### ISSUE THREAD

**Issue by YohoYang** [solstice23/argon-theme#182]
子主题的逻辑是先加载子主题方法再加载父主题方法，使用可插拔函数（Pluggable Functions）可以使同名方法只有子主题的生效。

```
<?php
if ( ! function_exists ( 'my_function' ) ) {
    function my_function() {
        // Contents of your function here.
    }
}
?>
```

比如我现在需要给argon_get_post_thumbnail函数生成的特色图片增加OSS的图片处理后缀，但是没法覆盖这个函数来直接实现。
希望可以支持（目前先直接改了父主题实现了）

**Comment by solstice23** [comment]
可能使用 Filter 会更优雅一点，Filter 可以使用自定义的函数过滤该 URL，而不用覆盖这个函数。

已为该函数及其他一些函数增加了 Filter：https://argon-docs.solstice23.top/#/filters

**Comment by YohoYang** [comment]
感谢支持！在release更新后会进行调试
