### ISSUE TITLE
安卓设备的中文字体粗体显示异常

### ISSUE THREAD

**Issue by MagmaBlock** [solstice23/argon-theme#183]
已测试Chrome、Edge，Firefox，X5内核的浏览器，设备是Mi8SE（MIUI12）Android10。还找了一个安卓4.4.4的设备看了看
所有正文里**中文**的加粗都无法正常显示，英文字体正常。
个人感觉这可能是主题规定了安卓系统的中文字体但是不知道出了什么bug
### Windows Edge
如图，左边应该是加粗的汉字
![image](https://user-images.githubusercontent.com/61128045/112727238-89682880-8f5c-11eb-9128-b6bc6bf8f38e.png)

### Edge
加粗未能显示
![image](https://user-images.githubusercontent.com/61128045/112727637-5aeb4d00-8f5e-11eb-982e-b74173991ac6.png)
### Chrome
加粗未能显示
![image](https://user-images.githubusercontent.com/61128045/112727675-9423bd00-8f5e-11eb-8304-7ffc5885b825.png)

### Firefox
加粗几乎看不见（？不知道为什么火狐能看出来一点区别）
![image](https://user-images.githubusercontent.com/61128045/112727630-51fa7b80-8f5e-11eb-8276-ce2cd5cf7626.png)

### X5内核的浏览器（只是测试）
加粗未能显示
![image](https://user-images.githubusercontent.com/61128045/112727614-3c855180-8f5e-11eb-8eb3-dd8e018c969a.png)

个人更改了第三方的字体，能正常显示了
![image](https://user-images.githubusercontent.com/61128045/112727897-a6522b00-8f5f-11eb-958f-f50e32dca558.png)

**Comment by solstice23** [comment]
Android 中文字体少字重，有些粗体不能正常显示，可以通过刷 Magisk 模块解决，和主题应该无关

**Comment by MagmaBlock** [comment]
> Android 中文字体少字重，有些粗体不能正常显示，可以通过刷 Magisk 模块解决，和主题应该无关

那么能否实现在主题设置内更改自定义字体文件呢，或者关闭主题的默认字体
我现在用自定义css又引入了一套字体，中文就能正常显示了，但是加载网页的时候变两次有点卡...

**Comment by solstice23** [comment]
主题可以内置字体，但代价是带来很大的字体资源加载消耗。所以不内置字体，可以自己通过 CSS 引入。
