### ISSUE TITLE
说说好像不会自动换行？

### ISSUE THREAD

**Issue by ZegWe** [solstice23/argon-theme#185]
屏幕较窄或说说内容一行过多的话会超出右侧边界

**Comment by solstice23** [comment]
是首页上还是"说说"页面上

**Comment by ZegWe** [comment]
> 是首页上还是"说说"页面上

都不会换行

**Comment by solstice23** [comment]
请提供一下造成错误的文本和截图

**Comment by ZegWe** [comment]
https://blog.zegwe.me/one-thing/
![image](https://user-images.githubusercontent.com/22636524/113477331-a13b3180-94b3-11eb-9d5f-fbbd847fdb1e.png)

**Comment by solstice23** [comment]
已修复
