### ISSUE TITLE
文字不能放置在图片上方（官方2021 OK）

### ISSUE THREAD

**Issue by amufeng** [solstice23/argon-theme#187]
![2021](https://user-images.githubusercontent.com/50547434/113514810-484ac680-95a3-11eb-842b-a15fe259f1df.png)
![文字不能放置在图片上方](https://user-images.githubusercontent.com/50547434/113514811-4aad2080-95a3-11eb-8986-34acf1e285e8.png)

**Comment by MagmaBlock** [comment]
好像升级到5.7之后就有这个bug了...
不过Argon似乎目前对古腾堡编辑器的兼容做的比较少 不知道好不好修复

**Comment by solstice23** [comment]
对 Gutenberg 编辑器的支持之前就有计划了，TODO
