### ISSUE TITLE
【建议】主题搭建得太好了，如果能将自动调整为夜间模式的时间22：00-07：00也可以自定义就更好了

### ISSUE THREAD

**Issue by sparkyangglory** [solstice23/argon-theme#196]

**Comment by solstice23** [comment]
已增加相应的 Filter：`argon_darkmode_time_check`，可以通过此 Filter 来自定义判断夜间模式的时间区间，详见文档 [Filters](https://argon-docs.solstice23.top/#/filters) 章节

**Comment by crowya** [comment]
您好，我增加了Filter后页面一片空白，不知道是什么原因，我的Filter代码如下：
```
<?php
/*
Plugin Name: 鸦鸦的插件
Description: 更换夜间时间为晚八至早八
Version: 1.0
*/
add_filter('argon_darkmode_time_check', 'hour >=20 || hour <8');
?>
```

**Comment by crowya** [comment]
查到一个类似问题，不知道是否相关：https://blog.csdn.net/qq_43619271/article/details/108567524
