### ISSUE TITLE
兼容问题

### ISSUE THREAD

**Issue by FurryRbl** [solstice23/argon-theme#198]
貌似不能兼容wp的live2d看板娘插件?
还有微信打赏插件

**Comment by FurryRbl** [comment]
貌似也不兼容wx打赏差距.

**Comment by yzxoi** [comment]
因为 live2d 插件的 hex2rgb 函数与 Argon 的函数重名了，您可以尝试停用 live2d 插件，再看看是否正常。

同 #173

**Comment by FurryRbl** [comment]
> 因为live2d插件的hex2rgb函数与Argon的函数重名了，您可以尝试修改live2d插件，再看看是否正常。
> 
> 同[＃173](https://github.com/solstice23/argon-theme/issues/173)

我不会php emm

**Comment by vihor3** [comment]
用WPJAM插件的Memcached缓存功能也不兼容。评论头像不显示，懒加载也有问题
