### ISSUE TITLE
新标签页打开超链接的target属性值设置错误

### ISSUE THREAD

**Issue by bobo2334** [solstice23/argon-theme#2]
您好，我在使用这个主题的时候发现了一些问题。

我在使用短代码生成的友情链接的时候发现这些链接不会在新标签页打开，看了一下网页源代码，发现`<a>`标签的`target`属性为`_blink`，我觉得您当时可能想写的是`_blank`。

![image.png](https://i.loli.net/2020/02/23/T1yaL6xVGku5HUA.png)

另外，我在仓库里搜了一下，还有其他的几处`_blink`出现的地方。

![image.png](https://i.loli.net/2020/02/23/yklqwcCevHSh7aK.png)

还有，非常喜欢您这款主题，真是太棒啦。

**Comment by solstice23** [comment]
这个问题遗留了这么久都没有被发现😂，已经修复并更新了新版本，感谢~
