### ISSUE TITLE
友链短代码什么也没输出

### ISSUE THREAD

**Issue by lushuyu** [solstice23/argon-theme#20]
![image](https://user-images.githubusercontent.com/27007632/79116792-f4f0ce80-7dbb-11ea-8822-311bf576029e.png)

![image](https://user-images.githubusercontent.com/27007632/79116848-18b41480-7dbc-11ea-86fb-df8608371b64.png)

这是什么鬼畜错误？我去打开debug看看更多的信息

**Comment by lushuyu** [comment]
刚才控制台图片搞了筛选器，补一个完整的

![image](https://user-images.githubusercontent.com/27007632/79116957-5a44bf80-7dbc-11ea-81f0-fe6aeec8ac72.png)

**Comment by solstice23** [comment]
请检查页面模板是否设为了 "留言板"，留言板模板会隐藏文章，只保留评论区
