### ISSUE TITLE
【错误反馈】插件 Code Syntax Block 的 CSS 被大量覆盖

### ISSUE THREAD

**Issue by ADD-SP** [solstice23/argon-theme#201]
## 简单说明

使用插件 Code Syntax Block 提供代码高亮，在关闭了主题的代码高亮功能后，发现 Code Syntax Block 提供的 CSS 样式被大量覆盖。改用官方主题 「二〇二一」后表现正常。

### Argon 主题的效果

![image](https://user-images.githubusercontent.com/44437200/117331852-bac40480-aec9-11eb-90da-28a34a69907a.png)

![image](https://user-images.githubusercontent.com/44437200/117331742-a122bd00-aec9-11eb-8fc1-3e3dcdb39c4b.png)

## 官方主题「二〇二一」的效果

![image](https://user-images.githubusercontent.com/44437200/117332996-0dea8700-aecb-11eb-85e1-ca8479402086.png)

## 系统环境

* WordPress: 5.7.1
* PHP: 7.4
* Web Server: nginx-1.20.0
* Argon: v1.1.7

## 复现步骤

1. 通过 Wordpress 管理页面安装 Code Syntax Block 插件并启用。
2. 关闭主题自带的代码高亮功能。
3. 进入任意一篇文章，插入一个代码块，填入合适的内容，在区块设置中选择合适的语言，
4. 为代码区块选择合适语言，然后将代码区块的颜色主题设置为 `One Dark`。
![image](https://user-images.githubusercontent.com/44437200/117332307-3de55a80-aeca-11eb-837a-98c6601a77e7.png)
5. 保存之后访问页面，会发现代码块背景不为黑色。通过控制台会发现代码块的 CSS 被大量覆盖。

**Comment by solstice23** [comment]
已新增禁用 Argon 自带样式选项
