### ISSUE TITLE
主题搜索功能SSL加密提示“并非完全安全”

### ISSUE THREAD

**Issue by hzjixiang** [solstice23/argon-theme#202]
argon/searchform.php  中的`<?php echo get_option('home'); ?>`会导致网站SSL加密提示“并非完全安全”
我百度查的解决办法不清楚对不对：改成`<?php echo home_url(); ?> `就好了。  
如果有更好的办法，请告知，谢谢啦。

![微信截图_20210507051103](https://user-images.githubusercontent.com/16386198/117366169-f0c9ae80-aef2-11eb-8c58-0d12dd9ce7e9.png)

**Comment by solstice23** [comment]
在 Wordpress 设置中将网站地址设为 HTTPS 协议的
