### ISSUE TITLE
Gutenburg 画廊显示异常

### ISSUE THREAD

**Issue by Robotxm** [solstice23/argon-theme#207]
如图，如果用 Gutenburg 的画廊插入多张图片，Argon 无法正常显示，会超出边界

![image](https://user-images.githubusercontent.com/5405331/118110169-ab3a4380-b414-11eb-9ee3-d9c1a96fb8b9.png)

**Comment by IodineFlask** [comment]
同样的问题，感觉主题还没有很好的适配区块编辑器
