### ISSUE TITLE
增加文集模式的可能性询问···

### ISSUE THREAD

**Issue by TianJiaLin1994** [solstice23/argon-theme#216]
hello， 作者你好，非常感谢你的主题，我一直在使用，非常好看，很喜欢。
我因为想写一些系列文章，但是不一定一直连续写，所以它们分散在各个地方，当我想阅读的时候非常不方便。

所以有空的时候希望你考虑一下做个能写文集的办法，非常感谢。
类似效果如：gitbook

**Comment by solstice23** [comment]
善用"分类"功能

如果说的是像 Gitbook 这样文档侧栏目录功能，WordPress 本身就不是一个很好的写文档工具（文章是零碎的）

**Comment by TianJiaLin1994** [comment]
感谢回复， 那我还是考虑一下曲线救国了 : )
