### ISSUE TITLE
一言api json错误

### ISSUE THREAD

**Issue by crowya** [solstice23/argon-theme#22]
![image](https://user-images.githubusercontent.com/61354956/79188768-90348300-7e52-11ea-9520-36d866afbff7.png)

解决办法：应去掉 argontheme.js 1632 行 的 `result = JSON.parse(result);`
原因：JSON.parse()用于从一个字符串中解析出json对象，而目标数据本来就是一个json对象了，不需要在转换了。[Unexpected token o in JSON at position 1 报错原因](https://blog.csdn.net/wxl1555/article/details/79184076)

**Comment by solstice23** [comment]
fixed，感谢找出 BUG
我之前测的时候返回的好像还是纯文本
