### ISSUE TITLE
[Feature Request]请求能够自定义评论框的placeholder内容

### ISSUE THREAD

**Issue by Marukon** [solstice23/argon-theme#221]
现在评论框的placeholder内容默认为”评论内容“，希望作者可以在主题设置增加一个选项，能够自定义这个placeholder内容，谢谢。

**Comment by Marukon** [comment]
谢谢作者

**Comment by Marukon** [comment]
@solstice23 大佬，我可能表达错了我的意思。能否在主题设置里面增加一个选项，能够修改这里面默认的内容？
![1](https://user-images.githubusercontent.com/6285343/125159932-f66e9980-e1ac-11eb-9a52-2d44fb55cb8a.png)

![2](https://user-images.githubusercontent.com/6285343/125159980-303fa000-e1ad-11eb-8ba5-8b12efd59d12.png)

**Comment by solstice23** [comment]
没有必要为这个需求单独增加一个选项，所以用了更轻量灵活的 Filter 方式替代。

具体参见文档 [Filter](https://argon-docs.solstice23.top/#/filters) 章节，已撰写了一个例子。

**Comment by Marukon** [comment]
> 没有必要为这个需求单独增加一个选项，所以用了更轻量灵活的 Filter 方式替代。
> 
> 具体参见文档 [Filter](https://argon-docs.solstice23.top/#/filters) 章节，已撰写了一个例子。

明白了，我去仔细看一下教程。谢谢大佬回复。
