### ISSUE TITLE
建议QQ头像对QQ邮箱的支持

### ISSUE THREAD

**Issue by Shizuri23** [solstice23/argon-theme#225]
![image](https://user-images.githubusercontent.com/46082179/121782672-5f2e1a80-cbdd-11eb-9119-9834b7447de6.png)
一般人往那输的是QQ邮箱，但是QQ邮箱并不会有QQ头像
if(strpos($qqmail,'@qq.com'))

**Comment by solstice23** [comment]
会和 Gravatar 冲突，如果用户想使用 Gravatar 就没办法了

**Comment by Shizuri23** [comment]
可以增加个选项吗？

**Comment by solstice23** [comment]
即将更新的下个版本中，[check_qqnumber](https://github.com/solstice23/argon-theme/blob/master/functions.php#L1427-L1433) 函数变为可插拔函数，可以用自己写的插件覆盖它。
可以在覆盖它的函数中加入邮箱的逻辑，并在为邮箱时覆写 `$_POST['email']` 为去掉邮箱后缀的 QQ 号即可实现。

**Comment by HanHan666666** [comment]
现在，输入QQ邮箱和QQ号都可以获取QQ头像，有没有解决方法了
