### ISSUE TITLE
文章加密问题

### ISSUE THREAD

**Issue by ruom0** [solstice23/argon-theme#227]
我的wordpress安装在子目录/index/中，在主题设置中wordpress子目录我已改为/index/，若文章未加密访问均正常。
在给文章启用密码保护后，正确的提交地址应该是/index/wp-login.php?action=postpass，但是我这边一直提交的都是/wp-login.php?action=postpass
测试后是主题的关系。。因为更换主题后这个问题就不存在了……请问有什么解决方法吗。。

**Comment by solstice23** [comment]
已修，感谢反馈
