### ISSUE TITLE
语言

### ISSUE THREAD

**Issue by xiaocao666tzh** [solstice23/argon-theme#237]
安装完主题之后，主题默认是英文，我手动吧languages下的.po文件删了，只保留了中文的.po文件，但是这样子还有一部分字体是英文，比如copy时候的提示。但是我的WordPress后台设置的语言是简体中文

**Comment by xiaocao666tzh** [comment]
能否在主题设置里面添加语言选择

**Comment by solstice23** [comment]
@xiaocao666tzh 主题跟随 WordPress 语言设置

**Comment by xiaocao666tzh** [comment]
wp语言已经设置成了简体中文但主题还是英文。

**Comment by xiaocao666tzh** [comment]
删除其他.po文件后还有一些地方是英文比如
https://i.loli.net/2021/07/28/PTjc6AZLmrRVBho.png
https://i.loli.net/2021/07/28/8xXJie17MR96shz.png

**Comment by solstice23** [comment]
检查是否有插件冲突，Hook 了语言

**Comment by xiaocao666tzh** [comment]
插件全部检查了一遍了，还是不行啊

**Comment by xiaocao666tzh** [comment]
应该不是插件的问题
