### ISSUE TITLE
代码高亮 

### ISSUE THREAD

**Issue by zhangdengjie** [solstice23/argon-theme#238]
反复刷新界面
有几率出现
1 显示不全
2 显示全代码之后,背景色不显示,点击全屏显示的时候,背景色透明

版本:1.1.9

**Comment by solstice23** [comment]
F12 Network 菜单截个图

**Comment by zhangdengjie** [comment]
> F12 Network 菜单截个图
![Snipaste_2021-07-20_16-39-24](https://user-images.githubusercontent.com/9708735/126289921-031276b0-4d96-46ca-a47b-24a045ece199.png)
![Snipaste_2021-07-20_16-39-44](https://user-images.githubusercontent.com/9708735/126289932-d79a6f70-4601-44e4-81a8-11b691ceac1a.png)
![Snipaste_2021-07-20_16-40-00](https://user-images.githubusercontent.com/9708735/126289936-4fa116c9-c264-4df4-82a8-f57dfb5bd9db.png)

**Comment by solstice23** [comment]
资源看上去全都加载了，Console 有报错吗

**Comment by zhangdengjie** [comment]
> F12 Network 菜单截个图

![Snipaste_2021-07-20_16-41-14](https://user-images.githubusercontent.com/9708735/126290083-be75c193-0938-43a3-802c-b73b575da41b.png)

**Comment by solstice23** [comment]
检查一下是否有冲突的插件

**Comment by zhangdengjie** [comment]
> 检查一下是否有冲突的插件

我把启用的插件都关闭了,看起来是好了
我来看看是哪个插件引起的吧 3Q
