### ISSUE TITLE
功能建议：图片说明

### ISSUE THREAD

**Issue by DefiedParty** [solstice23/argon-theme#24]
希望可以支持图片说明的功能
编辑器插入图片：
![image](https://user-images.githubusercontent.com/44311872/80239574-104cbb00-8693-11ea-9210-4aaa807ecb7d.png)
但是在浏览页面，argon看起来没有支持图片说明
![image](https://user-images.githubusercontent.com/44311872/80239520-f7dca080-8692-11ea-94ce-92cd606e6b3f.png)
如果可以的话，非常感谢！

**Comment by solstice23** [comment]
已支持√

**Comment by DefiedParty** [comment]
大佬整活好快:joy:
