### ISSUE TITLE
问题求助

### ISSUE THREAD

**Issue by FmgX** [solstice23/argon-theme#241]
这个‘文章过时信息显示’弄不明白
![Snipaste_2021-07-22_19-15-49](https://user-images.githubusercontent.com/47731175/126630938-72fac787-ed5b-4de9-8c6c-d85d30e3a97c.png)
一旦开启这个后是无差别的全部都是有‘文章过时信息显示’的，可是有的文章不需要。所以想知道怎么单独的设置这个‘文章过时信息显示’呢

谢谢

**Comment by solstice23** [comment]
[刚更新](https://github.com/solstice23/argon-theme/commit/92de5fc90d418624757fdd0a2c3b1dcf064887e8)，还没有发 Release，需要删掉 Release 版本 Clone 一份。

在文章设置中开启即可。
![image](https://user-images.githubusercontent.com/23134847/126631859-99eb4ca6-505c-4a4e-8c10-33553efe9d26.png)
