### ISSUE TITLE
暗黑模式 表格条纹样式有配色冲突

### ISSUE THREAD

**Issue by isyekong** [solstice23/argon-theme#245]
表格使用条纹样式，开启暗黑模式后表格内容部分配色冲突。
![image](https://user-images.githubusercontent.com/20068143/127293283-b9c517b7-24c7-4e00-a526-85ec4341eb56.png)

表格在小屏幕/移动端排版错乱，希望优化。

感谢作者

**Comment by solstice23** [comment]
fixed
