### ISSUE TITLE
切换夜间模式背景图片未自动切换。

### ISSUE THREAD

**Issue by Kennthey** [solstice23/argon-theme#246]
切换夜间模式背景图片未自动切换，仍是日间模式背景图。
wp5.8版本右侧“近期文章”，“近期评论”，栏目会出现英文，回退5.7版本无此现象。

**Comment by solstice23** [comment]
1. 请检查夜间图片地址是否设置错误，或无法加载。

2. Wordpress 未翻译完全的问题，主题不负责这部分翻译。

**Comment by solstice23** [comment]
已修复夜间模式问题

**Comment by Kennthey** [comment]
问题解决
