### ISSUE TITLE
使用WP Githuber MD编辑器编写KaTex公式时首次渲染问题

### ISSUE THREAD

**Issue by dhao2001** [solstice23/argon-theme#249]
您好，非常喜欢您的主题，这几天尝试使用KaTex编写公式时遇到了如下问题：

- 在WP Githuber MD编写数学公式时预览正常
- 访问文章链接时，第一次无法正常加载数学公式，显示的段落为原始的LaTeX代码，需要刷新页面方可正常显示数学公式
- 控制台中没有其他错误信息，KaTeX的auto-render.min.js加载正常

**Comment by solstice23** [comment]
使用的是否是 Katex 插件或手动引用 Katex？

Pjax 加载后页面没有刷新，Katex 不会自动渲染，需要将渲染代码写进 `window.pjaxLoaded` 函数中。

Argon 也内置了 Katex 库的引用，并且支持 Pjax 自动渲染，在设置中即可开启。
