### ISSUE TITLE
关于代码高亮问题

### ISSUE THREAD

**Issue by stimw** [solstice23/argon-theme#25]
希望可以添加普通文本的支持
比如：
\```text
balabalabla
\```
目前如果在```后面添加任意不能识别的语言显示都会出bug（比如none或者text）
建议可以改成：如果不能识别语言，那么默认不启用任何高亮，只显示mac样式的代码块。

**Comment by crowya** [comment]
- 希望加入对内联代码的高亮支持
- 代码块后面的段落间距过大
- 全屏的时候好像会和`.card{backdrop-filter:blur(6px);}`这个CSS属性冲突（应该只有我有这个问题，为了毛玻璃效果_(:з)∠)_）

**Comment by solstice23** [comment]
> 代码块后面的段落间距过大
修了
> 全屏的时候好像会和.card{backdrop-filter:blur(6px);}这个CSS属性冲突（应该只有我有这个问题，为了毛玻璃效果_(:з)∠)_）
新版本在代码块全屏后会给 html 添加 `codeblock-fullscreen` 类，可以在存在这个类时取消 `backdrop-filter` 属性来兼容

**Comment by solstice23** [comment]
> 希望可以添加普通文本的支持
> 比如：
> ```text
> balabalabla
> ```
> 目前如果在```后面添加任意不能识别的语言显示都会出bug（比如none或者text）
> 建议可以改成：如果不能识别语言，那么默认不启用任何高亮，只显示mac样式的代码块。

语言识别是 highlight.js 库那边的，不能识别的语言名称会不解析。如果不确定语言的名称，可以参考 highlight.js 官网。或者，不输入任何语言名称则会自动识别语言。
普通文本可以写成 `plaintext`，会被作为纯文本解析。
