### ISSUE TITLE
一言接口建议

### ISSUE THREAD

**Issue by HankMo** [solstice23/argon-theme#251]
这个一言接口句子乱七八糟，我想自定义接口 ，但是我改了argontheme.js里面的接口，不行，没反应还是一言的接口，我发现是在后台开启了cdn，但是如果关闭cdn又会出现一系列资源错误 ，比如图标不显示报错等。
![image](https://user-images.githubusercontent.com/60347960/128302022-29524546-792b-4bc7-8e84-5e83630f637e.png)
如果可以希望作者优化下。

**Comment by HankMo** [comment]
为了自定义格式统一 可以用作者官网的接口格式
![image](https://user-images.githubusercontent.com/60347960/128307583-d50b4caf-7eb8-44fd-b37e-4374328901af.png)

**Comment by solstice23** [comment]
一言这个很难搞，网上的一言 API 各有各的格式，不统一，所以主题无法提供自定义一言 API 功能。

统一 API 格式的话，需要手写 API，都写 API 了那也不差这十几行前端代码了吧...
