### ISSUE TITLE
The source code exists http requests

### ISSUE THREAD

**Issue by choisiulun1** [solstice23/argon-theme#252]
When I have installed an SSL cert, I found that my website was still claimed as unsafe by the browser. I have checked the problem. It's because there are some HTTP requests in my source code. btw, your work is awesome! 

For your reference,
![image](https://user-images.githubusercontent.com/36674999/128450092-b76f210d-6474-4952-9055-ebccdecb6ac5.png)
![image](https://user-images.githubusercontent.com/36674999/128450118-c3fce354-ebf7-46df-a0c7-c63db312cd81.png)
![image](https://user-images.githubusercontent.com/36674999/128450173-072c9b35-bc9d-4cc2-887d-edb5733cc2ec.png)

**Comment by solstice23** [comment]
Check the URL form in "Settings - General", which should start with "HTTPS".

The HTTP links in screenshots are just for a namespace, will no be requested.
