### ISSUE TITLE
[BUG]安装WP Editor.md插件后文章目录功能崩溃

### ISSUE THREAD

**Issue by MemoryShadow** [solstice23/argon-theme#253]
**BUG描述 | Describe the bug**
>安装[WP Editor.md](https://github.com/LuRenJiasWorld/WP-Editor.md "点击前往")插件后文章目录功能崩溃

**复现方法 | To Reproduce**
> 安装后即可复现请查看[此页面](https://memoryshadow.cn/index.php/2021/08/06/integration-package/ "点击前往")可以看到文章目录消失,并留下报错

**期望行为 | Expected behavior**
> 双方得以共存,一同运作

**截图 | Screenshots**
>这是安装[此插件](https://github.com/LuRenJiasWorld/WP-Editor.md "点击前往")后的状态
![image.png](https://i.loli.net/2021/08/06/ktcLxGBMgNJ9fbr.png)
>这是禁用[此插件](https://github.com/LuRenJiasWorld/WP-Editor.md "点击前往")后的状态
![image.png](https://i.loli.net/2021/08/06/olh7fYudQp6AmOW.png)

**其他内容 | Additional context**
> 以下是浏览器的输出日志
![image.png](https://i.loli.net/2021/08/06/rNw6pGUPRyhJOtX.png)

**Comment by solstice23** [comment]
开启 Editor.md 的兼容模式即可

**Comment by MemoryShadow** [comment]
问题解决,非常感谢
