### ISSUE TITLE
Bug反馈 Pjax与侧边文章目录

### ISSUE THREAD

**Issue by Small-SaltedFish** [solstice23/argon-theme#258]
由于Pjax刷新的缘故
当从首页进入文章
侧边栏中的文章目录由于未刷新空白
![image](https://user-images.githubusercontent.com/34180066/129382205-e05ea040-066c-4ebb-9af1-e4e08fb8d2ff.png)

**Comment by solstice23** [comment]
请检查 F12 Console 是否有报错

**Comment by Small-SaltedFish** [comment]
无报错

**Comment by Small-SaltedFish** [comment]
不清楚原因 但是您的站点没有问题
我的站点https://blog.daihan.top

**Comment by solstice23** [comment]
应该是某个插件的锅吧，内联 js 被改了

**Comment by Small-SaltedFish** [comment]
关闭了wp-rocket的优化css js功能 css js全部回到jsdeliver 问题仍然存在

**Comment by solstice23** [comment]
全部禁用试试，然后再逐个启用

**Comment by Small-SaltedFish** [comment]
关闭了js递送优化 问题解决感谢 可能是js加载顺序问题 谢谢您回复 我将此issue关闭
