### ISSUE TITLE
较长的链接分两行显示时鼠标移上去的动画显示不正常

### ISSUE THREAD

**Issue by 4o4E** [solstice23/argon-theme#259]
如下图所示，只会显示一部分的下划线
![image](https://user-images.githubusercontent.com/58851040/129446177-9d2c9faa-5042-4232-8c49-2f3d02fb0c4c.png)

**Comment by solstice23** [comment]
受限于伪元素本身，没法做到多行全部有下划线动画

可能的解决方案： 始终显示下划线，不用动画
