### ISSUE TITLE
文章设置了特色图片，标题就看不太清楚了

### ISSUE THREAD

**Issue by RalstonLiu** [solstice23/argon-theme#265]
![](https://s1.328888.xyz/2021/08/20/image.png)  提一个小建议，文章设置了特色图片，标题就看不太清楚了（包括首页显示也是），有没有办法加个阴影呢，类似这样的 ![](https://s1.328888.xyz/2021/08/20/image6bfe57bbfc94d4cf.png) 这样就能看得更清楚啦。

**Comment by solstice23** [comment]
@RalstonLiu 可以考虑加一个 backdrop-filter
