### ISSUE TITLE
BUG 双栏反转和瀑布流同时使用有bug

### ISSUE THREAD

**Issue by IodineFlask** [solstice23/argon-theme#269]
右侧卡片和Sidebar有重叠

**Comment by solstice23** [comment]
无法复现

**Comment by IodineFlask** [comment]
作者你好：
所述bug是像这样，pc端chrome。
地址:https://wasteflask.com
***@***.***

________________________________

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/131322900-0c7522d5-5e6d-4601-83c7-08e5f9c9d82e.png)
![image](https://user-images.githubusercontent.com/23134847/131322918-7722650a-168b-4d18-b0c8-92bf9d02a143.png)
无法复现
