### ISSUE TITLE
左侧栏在目录、站点概览、功能之间切换时页面乱动并刷新，不知道是什么原因

### ISSUE THREAD

**Issue by crowya** [solstice23/argon-theme#27]
我的网站上切换左侧栏时页面老是抖，好像会回到顶部刷新一遍，但是作者大大的网站上切换时就很顺滑，困扰了我许久，不知道是什么原因……我的网址链接是这个https://crowya.com/bode-plot/

我在`window.pjaxLoaded()`里写了东西，不知道和这个有关系吗？另外我的页尾脚本里也塞了不少东西，额外CSS也是……但是以前没写的时候好像也这样？

**Comment by solstice23** [comment]
似乎是这个监听事件的问题

![](https://i.loli.net/2020/04/29/XvFSrMZdb3htx7T.png)

**Comment by crowya** [comment]
作者大大，我试了下把ivory search的插件禁用后，还是出现了相同问题，但是当我把smoothscroll的点击事件remove后，似乎变正常了，但是我看不太懂这个函数做了什么_(:з)∠)_如图……
![image](https://user-images.githubusercontent.com/61354956/80671515-a68e4000-8adc-11ea-88c4-b51a6b62bdc1.png)
![image](https://user-images.githubusercontent.com/61354956/80671586-e9e8ae80-8adc-11ea-9364-75367856bc1b.png)

**Comment by crowya** [comment]
有没有大佬知道如何通过JS移除上面的监听事件呀，我用下面的代码好像不行
```
document.querySelector('#leftbar_tab_tools_btn').removeEventListener("click",linkHandler);
document.querySelector('#leftbar_tab_overview_btn').removeEventListener("click",linkHandler);
```

**Comment by crowya** [comment]
上述移除监听事件的方法无效后，我在网上找到一个不太完美的方法移除某个元素的所有监听事件，思路是——克隆元素，然后替换！简单粗暴，但是有效……
```
	//移除左侧栏切换时的监听事件防止页面刷新
	if($("#leftbar_tab_catalog_btn").length > 0){
		var el = document.getElementById('leftbar_tab_catalog_btn'),elClone = el.cloneNode(true);
		el.parentNode.replaceChild(elClone, el);
	}
	var el = document.getElementById('leftbar_tab_overview_btn'),elClone = el.cloneNode(true);
	el.parentNode.replaceChild(elClone, el);
	var el = document.getElementById('leftbar_tab_tools_btn'),elClone = el.cloneNode(true);
	el.parentNode.replaceChild(elClone, el);
```
元凶大概找到了，应该是 Aplayer 这个罪魁祸首……
另外这个东西还要写在延时函数里等它加载完再执行……
