### ISSUE TITLE
友联那页有点怪怪的

### ISSUE THREAD

**Issue by Shizuri23** [solstice23/argon-theme#273]
<img width="888" alt="image" src="https://user-images.githubusercontent.com/46082179/132496120-d0e5a8a5-eafc-4c17-9311-c733e9a74368.png">
请问是故意设计成这样吗？（下面有块黑）
Safari MacOS

**Comment by solstice23** [comment]
@Shizuri23 显然不是，是 bug（

**Comment by Shizuri23** [comment]
> @Shizuri23 显然不是，是 bug（

我不清楚别的游览器会不会出现这种情况，大佬，请加油

**Comment by Shizuri23** [comment]
> @Shizuri23 显然不是，是 bug（

1.2.10仍然有这个问题的存在，请问能否解决这个问题quq
