### ISSUE TITLE
发现了一个很有趣的现象，可能是bug

### ISSUE THREAD

**Issue by lvbibir** [solstice23/argon-theme#276]
![GIF 2021-9-15 10-02-43](https://user-images.githubusercontent.com/53466270/133358355-5314ed6e-ad1f-4518-bbec-99bbf1c3b479.gif)
bug的触发需要先将页面滚动栏拉到最底下，且最后一篇文章的标题过长，将鼠标放在标题上就会出现这个bug。gif图片的帧数较低，真实效果要比这个快很多，很魔性。

**Comment by solstice23** [comment]
@lvbibir 没办法，hover 时字距变大超过一行就会出现折行，解决方法是像瀑布流中那样只用 transform 放大而不是加大字距，算是 feature（

**Comment by qeqeq1** [comment]
同样发现该问题~很魔性

**Comment by solstice23** [comment]
有一个很 tricky 的方法，但终究不太好
```
.post-title {
	display: inline-block;
	width: 100%;
}
.post-title:hover {
	letter-spacing: 1px;
	margin-left: -14px;
	margin-right: -14px;
	width: calc(100% + 28px);
}
```
