### ISSUE TITLE
不知道是bug还是什么问题

### ISSUE THREAD

**Issue by Shizuri23** [solstice23/argon-theme#278]
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/46082179/135378134-c1ffdc6b-a784-4a5c-8b80-241f118974f2.png">
游客评论的时候会显示

<img width="325" alt="image" src="https://user-images.githubusercontent.com/46082179/135378238-17e7b939-99fd-4503-884b-a2e21107800a.png">

实际上已经发送成功
网站：https://nmsl.pet/

**Comment by solstice23** [comment]
似乎是 #272 的问题
