### ISSUE TITLE
有个不成熟的小建议，希望每篇加密的文章可以设置不同的密码提示信息

### ISSUE THREAD

**Issue by crowya** [solstice23/argon-theme#28]
1.希望每篇加密文章可以有不同的密码提示信息。其实我是想搞一个类似回答问题的筛选机制，根据提示信息猜出来了就可以放行，而不至于挡住所有人……另外对自己回忆密码也有帮助
2.希望登录界面和404页面能匹配主题色

**Comment by solstice23** [comment]
第一个可以
第二个好像适配主题色没什么效果，倒是夜间模式可以适配一下

**Comment by crowya** [comment]
另，似乎发现一个bug，说说标题过长的时候没有自动断行
![5665084E-1303-4F7E-AA34-D0D6B1CCA90E](https://user-images.githubusercontent.com/61354956/80830138-0c80e180-8c1b-11ea-92d3-8d1c174ee847.jpeg)

**Comment by solstice23** [comment]
> 1.希望每篇加密文章可以有不同的密码提示信息。其实我是想搞一个类似回答问题的筛选机制，根据提示信息猜出来了就可以放行，而不至于挡住所有人……另外对自己回忆密码也有帮助
> 2.希望登录界面和404页面能匹配主题色

已支持，密码提示请新建名为 password_hint 的 Meta 项，并将其内容设为想要的提示内容
> 另，似乎发现一个bug，说说标题过长的时候没有自动断行

已修复
