### ISSUE TITLE
WP的播放器在说说详情页不能显示

### ISSUE THREAD

**Issue by wele0612** [solstice23/argon-theme#280]
第一幅图是在博客的首页，播放器可以正常显示和播放
第二幅图是点进去说说的详情页和评论页，此时出现问题
对应元素信息：class="wp-playlist-item-meta wp-playlist-item-title"
出现问题的网页访问链接: ltyxh.com
![1](https://user-images.githubusercontent.com/59970710/135735807-df47f388-6534-452c-86ee-d73cc95cf34c.jpg)
![1](https://user-images.githubusercontent.com/59970710/135735814-e751f453-293f-45e6-8b3f-76dad3ff072d.jpg)

**Comment by wele0612** [comment]
补充：移动端和网页端均复现此问题
此外播放的那个黑条叠放次序也有问题，移动端处于顶部菜单栏的上方，向上滚动就能卡出来

**Comment by solstice23** [comment]
https://argon-docs.solstice23.top/#/faq?id=q-%e5%ae%89%e8%a3%85%e4%ba%86%e6%9f%90%e4%b8%aa%e6%8f%92%e4%bb%b6%ef%bc%8c%e5%88%9d%e6%ac%a1%e8%bf%9b%e5%85%a5%e6%9f%90%e4%b8%aa%e9%a1%b5%e9%9d%a2%e5%8f%af%e4%bb%a5%e5%b7%a5%e4%bd%9c%ef%bc%8c%e4%bd%86%e6%98%af%e4%bb%8e%e5%88%ab%e7%9a%84%e9%a1%b5%e9%9d%a2%e8%b7%b3%e8%bd%ac%e8%bf%9b%e5%85%a5%e5%b7%a5%e4%bd%9c%e4%b8%8d%e6%ad%a3%e5%b8%b8
------
叠放次序是 argon design system 的 z-index 太小的问题，已修
