### ISSUE TITLE
主题颜色“蓝灰”问题

### ISSUE THREAD

**Issue by stimw** [solstice23/argon-theme#29]
该颜色下，文章页内的链接高亮并不是非常明显，乍一看可能看不出来。
主要是移动端的问题，桌面端的话鼠标悬停会有下划线所以还好。

然后主题颜色“黑色”下，夜间模式文章标题颜色也会融入背景...

**Comment by foamzou** [comment]
> 然后主题颜色“黑色”下，夜间模式文章标题颜色也会融入背景...
这个我建议作者大大，不同模式对应设置不同主题色
