### ISSUE TITLE
关于字数统计的建议

### ISSUE THREAD

**Issue by laoguanTX** [solstice23/argon-theme#297]
主题中可以选择选择文章字数，但是对于我们这些写代码的人来说，这种统计方式似乎不合理（好像不会统计代码的字数）这样的话阅读时间会很不合理，我尝试过将每分钟的阅读字数调低，但对于一些纯文字的文章，又会变得不合理，希望能够在主题设置加入一个选项，选择代码是否加入文字计数。
附带两个问题：
1.背景如何设置动态背景。
2.文本背景如何设置半透明。

**Comment by solstice23** [comment]
@laoguanTX 可以加入代码行数统计

ext.
1. Video
2. CSS

**Comment by laoguanTX** [comment]
这是什么意思(那个ext.)我没看懂，可以解释一下吗

**Comment by solstice23** [comment]
@laoguanTX extra

**Comment by solstice23** [comment]
已支持统计代码行数并计算时间

**Comment by laoguanTX** [comment]
感谢！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月6日(星期六) 晚上6:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [solstice23/argon-theme] 关于字数统计的建议 (Issue #297)





 
已支持统计代码行数并计算时间
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by laoguanTX** [comment]
目前似乎所有问题都解决了，感谢！
