### ISSUE TITLE
邮件相关问题

### ISSUE THREAD

**Issue by RookieTerry** [solstice23/argon-theme#298]
请问如何向评论者发送评论被回复的邮件，以及有评论时收到邮件？我使用的是WP Mail SMTP插件，请问你们的主题自带这一功能吗？

**Comment by solstice23** [comment]
自带，但是需要安装插件

**Comment by RookieTerry** [comment]
我安装了WP Mail SMTP插件，结果出现如图报错
[image: UWHF95{(01VP9164R8F[(UM.png]

solstice23 ***@***.***> 于2021年11月2日周二 下午3:28写道：

**Comment by solstice23** [comment]
图片没发出来

**Comment by RookieTerry** [comment]
[image: bd33e30f5059e45e6c185537551ed43d.png]

solstice23 ***@***.***> 于2021年11月4日周四 下午4:07写道：

**Comment by solstice23** [comment]
@RookieTerry 通过邮件回复的形式 似乎 无法发出图片
