### ISSUE TITLE
相关问题反馈

### ISSUE THREAD

**Issue by mocehu** [solstice23/argon-theme#3]
1.手机端侧栏圆角处不透明（白的...）加上公告就更怪异了...
2.新版更新圆角后悬浮的设置按钮没有恢复选项，
3.手机端悬浮阅读进度不能到100，
4.当进行多轮回复后文字显示的宽度过小，而且头像居中总感觉很怪...（这点应该发现了吧）
5.当前的更新源不可用？？？Github源检测不到，而另一个源会自动更新失败，这个问题不知道是不是个例
6.短代码在代码中也被识别（这个是bug吗？）
暂且就这些，谢谢大佬对我近期对我的耐心解答

**Comment by solstice23** [comment]
1. 圆角BUG 待修复。公告这个其实我也没想好怎么去处理，不过肯定会改。
2. 其实是有的，点击左边的文字就可以恢复。这个有些隐蔽，考虑改的更明显一点，或者加个恢复全部选项的按钮。
3. 我好像无法复现。在手机多个浏览器测试都可以到达 100%。
4. 小屏上多轮回复宽度过小的问题会调整。头像居中准备改成居上。
5. 应该是你的服务器访问 Github 和备选更新源不顺畅，应该会增加新的更新源。
6. 这个应该是 Wordpress 解析短代码机制的问题。不过有一个解决方案，可以利用短代码里嵌套的短代码不能被解析的特性，搞一个专门用来让短代码不解析的短代码（有点绕？？），下个版本会加入。

**Comment by mocehu** [comment]
第3个问题我再次确认了一下，在博客首页和部分文章内会发生，且仅限于手机端的chrome浏览器，其他浏览器均正常，并且在您的博客也是如此，博客和github不方便回复图片，如果您愿意的话可以留下您的邮箱，我会将截图发给您看

**Comment by solstice23** [comment]
> 第 3 个问题我再次确认了一下，在博客首页和部分文章内会发生，且仅限于手机端的 chrome 浏览器，其他浏览器均正常，并且在您的博客也是如此，博客和 github 不方便回复图片，如果您愿意的话可以留下您的邮箱，我会将截图发给您看

solstice233@gmail.com

**Comment by solstice23** [comment]
问题 1、2、4、6 已经修复

**Comment by solstice23** [comment]
关于问题 6 ，已增加新的更新源 : jsdelivr

**Comment by mocehu** [comment]
> 关于问题 6 ，已增加新的更新源 : jsdelivr

jsdelivr更新源存在检测不到更新的问题，目前自动更新主题在国内主机中属于不可用状态，安装某插件后解决了github,博客源更新失败的问题，但是更新失败的问题还是很大，希望可以用coding（gitee昨天我自己改了一下好像不行）之类的国内代码仓库作为新的更新源
