### ISSUE TITLE
增加Go链接跳转

### ISSUE THREAD

**Issue by ouyangyanhuo** [solstice23/argon-theme#301]
针对外部链接失效导致网站权重降低的问题，我觉得Go链接应该是有助于改善这个问题的。
对Argon主题使用一年多以后的感受就是，功能很棒，更新后也更强大，但是一直没有Go链接。
我有Go链接的跳转系统，但是不内置在主题中还是用着不习惯，所以希望作者能考虑加入这个东西。
如果作者确实认为这有必要，我可以提供几个操作设计上面的思路。
1.外部链接全部采用Go链接跳转，针对单独的某个外部链接可以对其进行关闭。
2.网站内部链接，全部不采用GO链接跳转，针对单独的某个内部链接可以对其进行开启。
3.在对外显示时，可以将其的链接内容进行混淆。
当然这个东西是插件也可以实现的，但是在使用插件时，能明显感觉到性能的降低，如果能加入主题，性能方面可能不会有太大的损失。

还是希望作者大大可以考虑一下这个Go链接跳转这个事情

**Comment by solstice23** [comment]
其实插件并不会影响多少性能 这方面的功能更应该使用插件来实现
