### ISSUE TITLE
又是字数问题

### ISSUE THREAD

**Issue by laoguanTX** [solstice23/argon-theme#309]
可以自己修改文章字数吗，一篇至少5000字的文章硬数成了1500字。可能是因为我是用的html转的markdown再用的，markdown编辑器？

**Comment by solstice23** [comment]
@laoguanTX todo

**Comment by solstice23** [comment]
能提供一下错误文章的地址吗

**Comment by laoguanTX** [comment]
线性动态规划 – 老官童鞋gogo的博客 (laoguantx.top)
数论专题 – 老官童鞋gogo的博客 (laoguantx.top)
上面是典型的。
老官童鞋gogo的博客 – by laoguanTX
这是我的网站，其中最近的几篇都出现这样的问题，因为最近这几篇是markdown（typora）转成html导入的，wordpress对markdown很不友好




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "solstice23/argon-theme"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月12日(星期五) 晚上8:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [solstice23/argon-theme] 又是字数问题 (Issue #309)





 
能提供一下错误文章的地址吗
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by solstice23** [comment]
HTTP ERROR 502

**Comment by laoguanTX** [comment]
htt p://www.laogua ntx.to p/%e6%95%b0%e8%ae%ba%e4%b8%93%e9%a2%98/.html
http://www.laoguantx.top/%e6%95%b0%e8%ae%ba%e4%b8%93%e9%a2%98/.html
zhe shi yi xie dian xing de an li (wo bu zhi dao wei shen me wo de zhong wen shu ru fa bu hao yong le)
And this is my blog.
you can find more problems.
http://www.laoguantx.top/&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "solstice23/argon-theme"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月12日(星期五) 晚上9:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [solstice23/argon-theme] 又是字数问题 (Issue #309)





 
HTTP ERROR 502
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by laoguanTX** [comment]
http://www.laoguantx.top/%e6%95%b0%e8%ae%ba%e4%b8%93%e9%a2%98/.html
zhe shi yi xie dian xing de an li (wo bu zhi dao wei shen me wo de zhong wen shu ru fa bu hao yong le)
And this is my blog.
you can find more problems.
http://www.laoguantx.top/&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月12日(星期五) 晚上9:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [solstice23/argon-theme] 又是字数问题 (Issue #309)





 
HTTP ERROR 502
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by laoguanTX** [comment]
http://www.laoguantx.top/
This is the right site
