### ISSUE TITLE
关于日历、标题、目录的问题与建议

### ISSUE THREAD

**Issue by laoguanTX** [solstice23/argon-theme#314]
又是我！

----

发现日历数字背景颜色有问题，对于两位数的显示不正确，改成这样就好了。
![img](https://z3.ax1x.com/2021/11/15/I2gg6H.png)

----

第二个是我想把博客banner栏搞成透明的，并且希望只显示背景的三角彩带，同时使背景和banner透明我做到了，但是这样我的博客标题会变得不清晰，我尝试修改标题为黑色，但是又无法使标题变粗，观感也不好，F12提醒我去根目录的“（索引）“但是我在FTP种并没有找到这个文件，我应该怎么办？

----

对于文章目录，我发现当点击标题跳转到某一个标题目录时，内容栏会跳转到相应位置，但是左侧的目录栏会返回到我点击的标题的上一个标题。

----

对于您更新的代码，直接在后台修改，wordpress会提示出现致命错误，但是我太菜了，不会php，只能重新下载源码重装，这个问题有解决方案吗？

----

大佬，你的主题太棒了！这好像是第三次我想您提问了

**Comment by solstice23** [comment]
第一个问题已修

第二第三 https://argon-docs.solstice23.top/#/faq?id=q-%e6%88%91%e7%bc%96%e8%be%91%e4%ba%86%e4%b8%bb%e9%a2%98%e7%9a%84%e6%96%87%e4%bb%b6%ef%bc%8c%e4%bd%86%e6%98%af%e4%b8%bb%e9%a2%98%e6%9b%b4%e6%96%b0%e5%90%8e%e7%bc%96%e8%be%91%e7%9a%84%e5%86%85%e5%ae%b9%e6%b6%88%e5%a4%b1%e4%ba%86
