### ISSUE TITLE
过长的标题会导致标题不断闪动

### ISSUE THREAD

**Issue by BNQDZJ** [solstice23/argon-theme#315]
# **该问题只出现在特定分辨率的情况下 如 1600*900**
当鼠标放在过长的标题上会不断的闪动，比如说“微软开始在 Win11 上测试 Win10 经典右键菜单的新型设计，更加干净整洁”这个标题当鼠标不放在上面的时候刚好占满，当鼠标放上去时文字放大就开始不断闪动且无法点击（原因是放大后刚好超出一个字，当鼠标移动到标题所在的地方JS会不断检测鼠标位置是否在标题上就出现了这种情况）

https://user-images.githubusercontent.com/64721413/141790783-651cb93c-242b-4ea6-9a66-b5bf2e7cf0f6.mp4

**Comment by solstice23** [comment]
Duplicate with #276
