### ISSUE TITLE
你好，banner标题、副标题能否修改样式，如果不可以，能否增加相应的功能？

### ISSUE THREAD

**Issue by ywh07** [solstice23/argon-theme#316]
当背景图较亮时，banner标题、副标题会看不清，能否修改样式，与背景形成反差？
![image](https://user-images.githubusercontent.com/72757758/141996122-dad7bd90-0a4d-4bfb-8677-758eee4945d9.png)

**Comment by laoguanTX** [comment]
我来回答一下吧.
首先在在主页用f12找到文件的路径。如图：
![1](https://user-images.githubusercontent.com/62329359/142132690-8fc29799-661a-4ed4-8191-8c8b5463e5f3.png)
![2](https://user-images.githubusercontent.com/62329359/142132696-398e75b6-7da8-4455-bf46-bf5839f6188c.png)
然后，在FTP中找到文件位置，打开文件并修改，样式什么的可以在F12中修改后复制过去

**Comment by ywh07** [comment]
> 我来回答一下吧. 首先在在主页用f12找到文件的路径。如图： ![1](https://user-images.githubusercontent.com/62329359/142132690-8fc29799-661a-4ed4-8191-8c8b5463e5f3.png) ![2](https://user-images.githubusercontent.com/62329359/142132696-398e75b6-7da8-4455-bf46-bf5839f6188c.png) 然后，在FTP中找到文件位置，打开文件并修改，样式什么的可以在F12中修改后复制过去

感谢解答

**Comment by solstice23** [comment]
https://argon-docs.solstice23.top/#/faq?id=q-%e6%88%91%e7%bc%96%e8%be%91%e4%ba%86%e4%b8%bb%e9%a2%98%e7%9a%84%e6%96%87%e4%bb%b6%ef%bc%8c%e4%bd%86%e6%98%af%e4%b8%bb%e9%a2%98%e6%9b%b4%e6%96%b0%e5%90%8e%e7%bc%96%e8%be%91%e7%9a%84%e5%86%85%e5%ae%b9%e6%b6%88%e5%a4%b1%e4%ba%86
