### ISSUE TITLE
在解析代码块的 JavaScript 代码时似乎有问题

### ISSUE THREAD

**Issue by imByteCat** [solstice23/argon-theme#32]
Bug 显示可以参考 [我的博客](https://www.imbytecat.com/posts/185/)，不知道是因为主题的原因还是我所使用的 WP Githuber MD 插件的问题？编辑器预览的适合似乎没有这个问题，所以我觉得是主题问题。

![](https://i.loli.net/2020/05/06/HPkxtrRD2zb4I5O.png)

**Comment by solstice23** [comment]
代码块里没 HTML 特殊字符转义吧

**Comment by imByteCat** [comment]
破案了，确实是 WP GitHuber MD 的问题，看来 WordPress 还是不太适合使用 Markdown 啊
