### ISSUE TITLE
在主题设置的侧边栏点击一个项目会自动跳到上一个项目

### ISSUE THREAD

**Issue by BNQDZJ** [solstice23/argon-theme#320]
在在主题设置的侧边栏点击一个项目侧边栏的蓝框会自动跳到上一个项目
实际上是在点击的那个项目的，侧边栏却显示在上一个项目

https://user-images.githubusercontent.com/64721413/142752962-17549743-7d7f-4b7b-bfaa-f409558a4bcc.mp4

https://user-images.githubusercontent.com/64721413/142752993-13f09951-afe7-4751-8306-8ae1b60f45e4.mp4

**Comment by solstice23** [comment]
滚动判定的关系，无足轻重
