### ISSUE TITLE
自定义页面说说的分页怎么设置

### ISSUE THREAD

**Issue by susttt** [solstice23/argon-theme#321]
主题很好看，高度自定义，基本满足日常使用，感谢分享！
但现在在使用说说，全部的说说都是显示在一个页面的，方便的话，能否告知怎么设置分页？

**Comment by susttt** [comment]
已解决，代码本来就自带这个功能，只是默认没开启，posts_per_page为-1，怪不得刚开始没显示
argon\shuoshuo.php
      query_posts("post_type=shuoshuo&post_status=publish&posts_per_page=-1");

**Comment by solstice23** [comment]
会新增无限滚动加载

**Comment by susttt** [comment]
我的服务端：apache2.4 php8.0 wordpress 5.8.2
客户端浏览用chrome，没有无限滚动加载的情况，不过单纯改posts_per_page没用，分页面功能还是不正常，后改成如下才正常。
$paged = (get_query_var('paged')) ? get_query_var('paged') : 1;
query_posts('post_type=shuoshuo&post_status=publish&posts_per_page=' . $limit=7 . '&paged=' . $paged);
