### ISSUE TITLE
是否可以在编辑文章时指定高亮代码语言？

### ISSUE THREAD

**Issue by Natsukage** [solstice23/argon-theme#322]
例如Code Syntax Block可以在古腾堡编辑器中插入代码区块后在右侧菜单设置区块的语言以及是否显示行号等配置
目前采用的highlight.js高亮似乎只能自动识别代码语言不能手动指定，时常会出现识别错误情况

希望可以像Code Syntax Block一样，添加于文章内指定代码块的语言的功能

**Comment by solstice23** [comment]
@Natsukage 可以加个类名来指定语言 代码块功能不会内置 Gutenberg 区块 如果有扩展需求请使用相关插件
