### ISSUE TITLE
bug：首页显示说说时不加载图片

### ISSUE THREAD

**Issue by crowya** [solstice23/argon-theme#33]
首页显示说说时不加载图片，只有进入具体说说页面才显示
如图，中间本该是图片的位置留下很大一片空白
![image](https://user-images.githubusercontent.com/61354956/81401085-1ea1d900-9161-11ea-8f02-ce35adde52fb.png)

**Comment by solstice23** [comment]
fixed

**Comment by crowya** [comment]
new bug：更新后图片可以显示了，但是会溢出卡片(ﾉ*･ω･)ﾉ
![image](https://user-images.githubusercontent.com/61354956/81474855-b1fb0d00-923a-11ea-9dee-d76e91c9eeff.png)

**Comment by solstice23** [comment]
fixed
