### ISSUE TITLE
1.2.9更新之后后台文章相关界面一些按钮无响应

### ISSUE THREAD

**Issue by CherryGS** [solstice23/argon-theme#331]
以下截图中 三个编辑, 添加新分类, 从常用标签选择按钮均不可用, 点击后除url部分发生改变, 其余均无反应
尝试添加标签也无反应
1.2.8版本正常
尝试更换主题后正常
![屏幕截图 2021-12-05 230826](https://user-images.githubusercontent.com/61844819/144752226-d384f28c-a132-4d38-a185-3f57c7baadfa.png)

**Comment by CherryGS** [comment]
补充一下,包括那些块的折叠或者位置移动也均失效

**Comment by solstice23** [comment]
@CherryGS 请提供 F12 Console 报错信息

**Comment by CherryGS** [comment]
![屏幕截图 2021-12-06 132534](https://user-images.githubusercontent.com/61844819/144792402-34f311ae-5e40-43e7-8797-d58ad0c5ded1.png)

**Comment by solstice23** [comment]
使用的是否是经典编辑器
可能 jq 冲突了，到时候用 vanilla js 重写一遍

**Comment by CherryGS** [comment]
是的,通过官方提供的插件
