### ISSUE TITLE
评论是否可以支持通过 ajax 获取呢

### ISSUE THREAD

**Issue by imlijq** [solstice23/argon-theme#335]
如果使用了 Cloudflare CDN 并且设置了缓存所有 HTML（路径 /* 缓存所有、路径 /wp-admin* 不缓存），因为现在评论和 HTML 一起加载，有新评论时刷新页面不能立刻显示出来，需要清空缓存才行。是否可以支持 ajax 获取评论，通过 /wp-admin/admin-ajax.php 获取这样就不走缓存了

**Comment by solstice23** [comment]
@imlijq todo
