### ISSUE TITLE
取消訂閱郵件通知有問題？

### ISSUE THREAD

**Issue by chiyi4488** [solstice23/argon-theme#339]
如題，在郵件中點取取消訂閱連結，點開後 404，還請查明，謝謝<3

![image](https://user-images.githubusercontent.com/30853081/145664999-6c0408df-cdbf-4a80-8b99-e55592afa72a.png)

**Comment by solstice23** [comment]
如果是 Nginx，可能需要添加伪静态

```
rewrite /unsubscribe-comment-mailnotice/?(.*)$ /wp-content/themes/argon/unsubscribe-comment-mailnotice.php$1;
```

**Comment by chiyi4488** [comment]
沒錯！加上後即正常了！多謝！
