### ISSUE TITLE
文章目录的定位似乎有点问题

### ISSUE THREAD

**Issue by Natsukage** [solstice23/argon-theme#342]
![image.png](https://s2.loli.net/2021/12/13/MhHAb2uGiIwTUZY.png)
如图，在Argon的介绍文章 https://solstice23.top/archives/746 中也能复现。
当我在文章目录中点击Telegram 频道时，页面滚动到了《Telegram 频道》这一行，此时《Telegram 频道》这行标题的上面还有2行属于上一段《修改》的文字，可能因为如此，左侧的文章目录会即刻滑动到《修改》一段，而非《Telegram 频道》。
也就是文章目录判断当前位置是根据当前页面最顶端的文字进行判定的，然而页面滚动时候却为了给顶栏留出了空间所以留出了2行空行。导致了问题的发生。
不过我也不确定是不是我本地浏览器或者插件导致的问题…

**Comment by solstice23** [comment]
https://github.com/solstice23/argon-theme/releases/tag/v1.2.10 中已修复
