### ISSUE TITLE
中国必应搜索停用带来的网站首页每日bing无法使用

### ISSUE THREAD

**Issue by HanHan666666** [solstice23/argon-theme#345]
![Screenshot_2021-12-17-09-25-16-992_com.android.chrome.jpg](https://user-images.githubusercontent.com/60591430/146473498-50b0be5d-a806-495b-b9d1-11004da2fc9c.jpg)
![Screenshot_2021-12-17-09-26-33-495_com.android.chrome.jpg](https://user-images.githubusercontent.com/60591430/146473542-180cdcfd-7da5-4d2c-be1e-cfe564ebe323.jpg)

**Comment by Ghost-chu** [comment]
电信路由炸了，非Bing停用，属于临时故障

**Comment by HanHan666666** [comment]
> 电信路由炸了，非Bing停用，属于临时故障

原来是这样，吓死我了。
