### ISSUE TITLE
jsdelivr挂了

### ISSUE THREAD

**Issue by ngrok-add** [solstice23/argon-theme#346]

**Comment by ngrok-add** [comment]
![QQ截图20211220155840](https://user-images.githubusercontent.com/9362876/146732455-f139e0ae-515d-42b7-92ef-7da7c309598a.png)
临时解决

**Comment by solstice23** [comment]
@ngrok-add 暂不处理，先等待

**Comment by Ghost-chu** [comment]
jsdelivr 的 SSL 证书出现问题，Status页显示服务outage，已经在修了，晚点看看吧
