### ISSUE TITLE
与WP Githuber MD编辑器不兼容

### ISSUE THREAD

**Issue by tangger2000** [solstice23/argon-theme#355]
argon主题启用后，会导致wp githuber md编辑器的右侧小工具栏失效。期待您对此问题的修复。
![image](https://user-images.githubusercontent.com/16505692/147999320-e10261e9-b565-4fea-addc-2f134844df35.png)
问题复现：
当启用非argon主题时，编辑器的浏览器控制台显示为：
![image](https://user-images.githubusercontent.com/16505692/147999505-4d86779f-6f53-4bc0-a43e-559382927fbf.png)
当启用argon主题时，编辑器的浏览器控制台显示为：
![image](https://user-images.githubusercontent.com/16505692/147999586-26a8e64a-0413-4317-9e39-6bc11939ad84.png)

**Comment by solstice23** [comment]
@tangger2000 duplicate with #331
已在 e2253ef 中修复
请等待下一个 Release 或 clone 该 repo 的最新版本

**Comment by tangger2000** [comment]
感谢您的工作。祝您生活愉快！
