### ISSUE TITLE
Error with Sonaar Stcky Music Player

### ISSUE THREAD

**Issue by mARUwTC** [solstice23/argon-theme#359]
<img width="1382" alt="Screen Shot 2022-01-12 at 10 20 45" src="https://user-images.githubusercontent.com/86964487/149197762-4b6fceb5-6f02-48fb-971a-db05bf59de82.png">
The catalog and search function don't work after I activated the sticky function of Sonaar Music Player. The google chrome console output the error as mention in the photo above.

**Comment by solstice23** [comment]
jquery duplicate, try disabling the jquery of extension
