### ISSUE TITLE
jsDelivr - limit number of releases in solstice23/cdn

### ISSUE THREAD

**Issue by MartinKolarik** [solstice23/argon-theme#37]
Hi, Martin from jsDelivr CDN here.

I couldn't quickly find an e-mail contact but hopefully, you'll see this issue soon. I noticed you are using our CDN for repository https://github.com/solstice23/cdn in a way that's causing some issues for us. Our implementation currently doesn't do well with repositories that have too many releases, and you have more than 12000 - it appears that for each commit, a release is made as well. We kindly ask you to either:
 - automatically delete older releases, to ensure there are no more than 100 at the time,
 - or delete all releases and use commit hashes instead to access the files ([like this](https://cdn.jsdelivr.net/gh/solstice23/cdn@86e8aa8ea31d8cce213bab6616d43c496fb2cd8a/README.md)).

**Comment by solstice23** [comment]
I'm so sorry for taking you up too much server resources, now all releases are deleted and the new  script will delete old releases automatically, only keep the latest one. Thanks for your reminding.

**Comment by MartinKolarik** [comment]
Thanks.
