### ISSUE TITLE
文章预览无法显示特征图

### ISSUE THREAD

**Issue by smile-jing** [solstice23/argon-theme#372]
![image](https://user-images.githubusercontent.com/33960876/151099486-c6a48a53-199f-47d5-918d-f03ca5d5d127.png)

在文章外面看不到特征图，其他人有遇到过这个错误吗？

**Comment by solstice23** [comment]
请截图 F12 报错信息

**Comment by smile-jing** [comment]
![image](https://user-images.githubusercontent.com/33960876/151099854-ef02534a-4e6c-40b7-ada1-a80f07a2a0c8.png)
我对html不是很了解，您可以去看下
网址是smilejing.cn稍微往下拉一下就可以看到

**Comment by solstice23** [comment]
和 wp-smushit 插件冲突

**Comment by smile-jing** [comment]
好的，我测试了下，关了确实好了
