### ISSUE TITLE
站点概览额外内容左对齐

### ISSUE THREAD

**Issue by smile-jing** [solstice23/argon-theme#373]
感觉这个左对齐没啥用

- 测试
- 测试
- 测试

![image](https://user-images.githubusercontent.com/33960876/151101942-81e36a5b-11d0-4d0a-9984-c859a459ab91.png)

**Comment by smile-jing** [comment]
点和文字中间的空隙好大

**Comment by solstice23** [comment]
因为这块内容不带 css，留给自定义的
当时设想的用途是 添加 自定义 html section
如果想要样式，可以将菜单移动到 功能
