### ISSUE TITLE
主题设置中页头脚本失效？

### ISSUE THREAD

**Issue by halgion** [solstice23/argon-theme#38]
我在页头脚本中放了以下脚本，用于prismjs语法高亮。在0.944版之前是有效的，在之后的版本中失效了。
```
<link href="./wp-content/plugins/prism/prism.css" rel="stylesheet" />
<script src="./wp-content/plugins/prism/prism.js"></script>
<script type="text/javascript">
function loadprism(){
        var codes = document.querySelectorAll('code');
        [].forEach.call(codes,function(block){
            try{
                Prism.highlightElement(block);
            }catch(e){}
        });
}
$( document ).ready(function() {
        loadprism();
});
window.pjaxLoaded = function(){
        loadprism();
}
</script>
```

**Comment by solstice23** [comment]
0.944 没有修改与页头脚本相关的地方，失效可能是因为别的原因

**Comment by halgion** [comment]
是我弄错了，这段代码是有效的，但是prism高亮不成功，色彩没有作用，不知道是不是css的问题。
以前是可以的。我记得是0.950加入highlight高亮之后就不行了，highlight高亮不支持latex，所以我还是想用prism。

**Comment by halgion** [comment]
就是css的问题，只加载了highlight的高亮css，prism的没用，我并没有启用highlight，这里应该怎么办？
![QQ截图20200522160721](https://user-images.githubusercontent.com/11943235/82646073-7f8fdd80-9c46-11ea-8c45-d2448fb33383.png)

**Comment by halgion** [comment]
我没想到什么办法。。。只能把主题自带css中相应的部分删掉了😥
