### ISSUE TITLE
当文章内所有图片是远程图片，特色图设置无效

### ISSUE THREAD

**Issue by cdncomco** [solstice23/argon-theme#380]
“默认使用文章中第一张图作为头图”
文章内使用图床的远程图片，那么这个选项启用无效

**Comment by solstice23** [comment]
无法复现，请问是头图无法被加载还是没有头图

**Comment by cdncomco** [comment]
> 无法复现，请问是头图无法被加载还是没有头图

大佬，不好意思，没说清楚问题
在设置了使用第一张作为头图那么可以在阅读页的顶部显示（这里不限远程图片和本地图片，都可以显示），
但是在首页和分类页这种页面下图片不会显示（这里指的是远程图片。 本地图片或手动设置特色图正常显示）

**Comment by solstice23** [comment]
无法复现

https://user-images.githubusercontent.com/23134847/151702230-b9952900-9a44-4d29-b754-24a65a0ddef3.mp4

**Comment by cdncomco** [comment]
新年快乐！
感谢大佬，重新自查了，发现是插件导致的，目前已发现导致冲突的插件“WP-UTF8-Excerpt”，之前忘了自查插件冲突
辛苦了

**Comment by solstice23** [comment]
新年快乐！
