### ISSUE TITLE
首页隐藏特定 分类/Tag 下的文章出现致命错误

### ISSUE THREAD

**Issue by lovelycatv** [solstice23/argon-theme#384]
首页隐藏特定 分类/Tag 下的文章 一旦设置后就会引发错误：
Fatal error: Uncaught Error: Call to undefined function create_function() 
...functions.php on line 2109
此站点遇到了致命错误。

以下是具体代码
2105-2116
//首页隐藏特定分类文章
function argon_home_hide_categories($query){
	if (is_home() && $query -> is_main_query()){
		$excludeCategories = explode(",", get_option("argon_hide_categories"));
		$excludeCategories = array_map(create_function('$cat', 'return "-$cat";'), $excludeCategories);
		$query -> set('cat', $excludeCategories);
	}
	return $query;
}
if (get_option("argon_hide_categories") != ""){
	add_action('pre_get_posts', 'argon_home_hide_categories');
}

**Comment by solstice23** [comment]
请使用最新 Master 分支代码，此问题已修复

**Comment by lovelycatv** [comment]
> 请使用最新 Master 分支代码，此问题已修复

现在已经使用了Mater的代码，但是它只对分类有效，输入 标签 的ID并不会生效。
