### ISSUE TITLE
不能進行留言

### ISSUE THREAD

**Issue by mmm25002500** [solstice23/argon-theme#385]
在說說/文章底下/留言板 進行留言的時候 無法留言 切換到其他的佈景主題可以 但這個不行 請問一下怎解?
![image](https://user-images.githubusercontent.com/39051261/151852187-f4e0c485-f95e-48cf-96c7-2ee092b4a531.png)

**Comment by solstice23** [comment]
请提供 F12 Console 菜单的报错信息

**Comment by mmm25002500** [comment]
![image](https://user-images.githubusercontent.com/39051261/151852458-84d2e13c-a377-4b9e-bf1e-2e56df70ca34.png)

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/151852579-5db08b57-7336-4f60-9808-329bf7fda217.png)
https://argon-docs.solstice23.top/#/faq?id=q-%e8%af%84%e8%ae%ba%e5%a4%b1%e8%b4%a5
