### ISSUE TITLE
请求在 footer 中加入备案号

### ISSUE THREAD

**Issue by lym12321** [solstice23/argon-theme#388]
rt, 希望能在设置页面设置 footer 中备案号等信息而不是更改其源代码

**Comment by solstice23** [comment]
@lym12321 直接在 argon 设置 - 页脚 HTML 中写就行了，不需要修改源代码

**Comment by lym12321** [comment]
> @lym12321 直接在 argon 设置 - 页脚 HTML 中写就行了，不需要修改源代码

能否和 Theme [Argon](https://github.com/solstice23/argon-theme) By solstice23 显示在同一 div 下呢？（那 card 还挺好看的）

**Comment by solstice23** [comment]
页脚 HTML ≠ 页尾 HTML

**Comment by lym12321** [comment]
~~抱歉我没看见~~  
感谢回复
