### ISSUE TITLE
[建议]留言板评论置顶

### ISSUE THREAD

**Issue by lovelycatv** [solstice23/argon-theme#389]
如果可以实现的话，建议增加一个 评论置顶 功能，感谢(*´・ｖ・)。

**Comment by solstice23** [comment]
有意思的 Request
如果实现的话，有几个小问题：

**Comment by lym12321** [comment]
**Cu Ball**  
不过我觉得仅仅是将“原始评论”移动到顶部即可，并显示“置顶” tag  
即：  
- 不显示原始（位置的）评论  
- 显示在原评论区的顶部

**Comment by lovelycatv** [comment]
1. 原始评论显示在置顶评论下方
2. 独立与否我觉得都可以，但我更加偏向于类似B站的评论置顶(原评论顶部)
可以参照这个评论区：https://www.bilibili.com/video/BV1kq4y1h7Hu

如果是显示在原评论区顶部，那么这条置顶评论就不会再出现在评论区里面，也就是直接被提到了顶部，并且带有一个 置顶 的标识。

**Comment by solstice23** [comment]
如果一条评论是其他评论的回复，应该如何置顶

- 禁止这样的评论置顶
- 将其与讨论串一起置顶（包括子评论和被回复的评论）
- 置顶它及它的子评论

**Comment by lym12321** [comment]
@solstice23 应该 **只允许对主干评论进行置顶** 并在对其置顶时同步移动其回复罢。  

让被回复的评论和其所有回复内容一起置顶；另外，对一条评论下超过一定数量的回复进行折叠。

**Comment by lovelycatv** [comment]
> 如果一条评论是其他评论的回复，应该如何置顶
> 
> * 禁止这样的评论置顶
> * 将其与讨论串一起置顶（包括子评论和被回复的评论）
> * 置顶它及它的子评论

可以参照B站的评论区，只能对 **主评论** 置顶，若被置顶的评论有回复，回复也一起移动到置顶评论下面，也就是一整块都置顶上去了。回复过多的可以考虑用分页/折叠。

**Comment by solstice23** [comment]
已支持，需要在 argon 选项中开启评论置顶功能，然后评论区会出现置顶按钮

**Comment by lovelycatv** [comment]
> 已支持，需要在 argon 选项中开启评论置顶功能，然后评论区会出现置顶按钮

现在是可以了，但是还是有几个小问题。
- 已经置顶的评论没有置顶标识
- 已经置顶的评论没有取消置顶按钮，仍然是置顶按钮
- 已经有置顶的评论，其他评论仍可以置顶但无效

**Comment by solstice23** [comment]
> > 已支持，需要在 argon 选项中开启评论置顶功能，然后评论区会出现置顶按钮
> 
> 置顶按钮是有了，但是点了之后没反应

本地测试没问题

https://user-images.githubusercontent.com/23134847/152632368-28bc2f32-b67a-42c8-bd90-0c39953cbc57.mp4

**Comment by Ghost-chu** [comment]
<img width="694" alt="image" src="https://user-images.githubusercontent.com/30802565/152632422-4b444698-cca1-48d1-8d82-61b0c8891ae3.png">
未能复现问题

**Comment by lovelycatv** [comment]
> > > 已支持，需要在 argon 选项中开启评论置顶功能，然后评论区会出现置顶按钮
> > 
> > 
> > 置顶按钮是有了，但是点了之后没反应
> 
> 本地测试没问题
> 
>  output.mp4

https://storagereve.oss-cn-beijing.aliyuncs.com/uploads/aaa.mp4?Expires=1644048547&OSSAccessKeyId=TMP.3KgPY7yySYh9XwpwHGHm8sRCVJB4VhPcCtKPmYy5N4ttzcPUL8MxPA1v5gxqC4PbeakqeMVz9uPv7y3jVoJGxCaT1nzFQ9&Signature=ymkcfOQZT1sZUkBWJ4A56eoViGE%3D

**Comment by solstice23** [comment]
请关闭 CDN 选项

> > > > 已支持，需要在 argon 选项中开启评论置顶功能，然后评论区会出现置顶按钮
> > > 
> > > 
> > > 置顶按钮是有了，但是点了之后没反应
> > 
> > 
> > 本地测试没问题
> > output.mp4
> 
> https://storagereve.oss-cn-beijing.aliyuncs.com/uploads/aaa.mp4?Expires=1644048547&OSSAccessKeyId=TMP.3KgPY7yySYh9XwpwHGHm8sRCVJB4VhPcCtKPmYy5N4ttzcPUL8MxPA1v5gxqC4PbeakqeMVz9uPv7y3jVoJGxCaT1nzFQ9&Signature=ymkcfOQZT1sZUkBWJ4A56eoViGE%3D

请关闭 CDN 选项，然后 Ctrl + F5

**Comment by lovelycatv** [comment]
> 

但是置顶之后的评论位置还是没变，只是多了个标识

> > > > > 已支持，需要在 argon 选项中开启评论置顶功能，然后评论区会出现置顶按钮
> > > > 
> > > > 
> > > > 置顶按钮是有了，但是点了之后没反应
> > > 
> > > 
> > > 本地测试没问题
> > > output.mp4
> > 
> > 
> > https://storagereve.oss-cn-beijing.aliyuncs.com/uploads/aaa.mp4?Expires=1644048547&OSSAccessKeyId=TMP.3KgPY7yySYh9XwpwHGHm8sRCVJB4VhPcCtKPmYy5N4ttzcPUL8MxPA1v5gxqC4PbeakqeMVz9uPv7y3jVoJGxCaT1nzFQ9&Signature=ymkcfOQZT1sZUkBWJ4A56eoViGE%3D
> 
> 请关闭 CDN 选项，然后 Ctrl + F5

成功了，但是这好像是 ..置底...?
https://storagereve.oss-cn-beijing.aliyuncs.com/uploads/bbb.mp4?Expires=1644049129&OSSAccessKeyId=TMP.3KgPY7yySYh9XwpwHGHm8sRCVJB4VhPcCtKPmYy5N4ttzcPUL8MxPA1v5gxqC4PbeakqeMVz9uPv7y3jVoJGxCaT1nzFQ9&Signature=ZG7CA5%2FdUNvMfzXKjgYoSQ49Un8%3D

**Comment by Ghost-chu** [comment]
> > 
> 
> 但是置顶之后的评论位置还是没变，只是多了个标识
> 
> > > > > > 已支持，需要在 argon 选项中开启评论置顶功能，然后评论区会出现置顶按钮
> > > > > 
> > > > > 
> > > > > 置顶按钮是有了，但是点了之后没反应
> > > > 
> > > > 
> > > > 本地测试没问题
> > > > output.mp4
> > > 
> > > 
> > > https://storagereve.oss-cn-beijing.aliyuncs.com/uploads/aaa.mp4?Expires=1644048547&OSSAccessKeyId=TMP.3KgPY7yySYh9XwpwHGHm8sRCVJB4VhPcCtKPmYy5N4ttzcPUL8MxPA1v5gxqC4PbeakqeMVz9uPv7y3jVoJGxCaT1nzFQ9&Signature=ymkcfOQZT1sZUkBWJ4A56eoViGE%3D
> > 
> > 
> > 请关闭 CDN 选项，然后 Ctrl + F5
> 
> 成功了，但是这好像是 ..置底...? https://storagereve.oss-cn-beijing.aliyuncs.com/uploads/bbb.mp4?Expires=1644049129&OSSAccessKeyId=TMP.3KgPY7yySYh9XwpwHGHm8sRCVJB4VhPcCtKPmYy5N4ttzcPUL8MxPA1v5gxqC4PbeakqeMVz9uPv7y3jVoJGxCaT1nzFQ9&Signature=ZG7CA5%2FdUNvMfzXKjgYoSQ49Un8%3D

<Error>
<Code>AccessDenied</Code>
<Message>Request has expired.</Message>
<RequestId>61FE36515423BA32327B1D89</RequestId>
<HostId>storagereve.oss-cn-beijing.aliyuncs.com</HostId>
<Expires>2022-02-05T08:18:49.000Z</Expires>
<ServerTime>2022-02-05T08:33:21.000Z</ServerTime>
</Error>

**Comment by solstice23** [comment]
https://github.com/solstice23/argon-theme/commit/117360fa9c01b3a7ade2891da0ed8e6f03074e85

**Comment by lovelycatv** [comment]
> 

https://storagereve.oss-cn-beijing.aliyuncs.com/uploads/bbb.mp4

**Comment by lovelycatv** [comment]
> [117360f](https://github.com/solstice23/argon-theme/commit/117360fa9c01b3a7ade2891da0ed8e6f03074e85)

已经好了，感谢
