### ISSUE TITLE
几个涉及SEO的相关建议

### ISSUE THREAD

**Issue by hugoyue** [solstice23/argon-theme#39]
1、banner区域网站名称不建议固定为H1标签，将导致除首页以外的文章或页面标题存在歧义，希望文章正文标题页面标题添加H1标签。
2、文章页面建议增加相关文章模块根据tag进行推荐，增强相关性的同时减少跳出率。

---
其它的建议

1、建议首页列表可以对特定的目录进行隐藏。
2、文章图片希望能居中，不排除部分图片尺寸存在较小的情况。

---
最后，感谢作者提供如此精美的主题，也是目前开源的wordpress模版当中为数不多的优质主题，功能性、美观性兼具。

**Comment by solstice23** [comment]
感谢建议
> banner区域网站名称不建议固定为H1标签，将导致除首页以外的文章或页面标题存在歧义，希望文章正文标题页面标题添加H1标签。

已换成 DIV

> 文章页面建议增加相关文章模块根据tag进行推荐，增强相关性的同时减少跳出率。

TODO

> 建议首页列表可以对特定的目录进行隐藏。

已支持该功能

> 文章图片希望能居中，不排除部分图片尺寸存在较小的情况。

![](https://i.loli.net/2020/05/21/GihyN6LIRmV9wYO.png)

**Comment by hugoyue** [comment]
作者大大🐂太高效了，点赞
