### ISSUE TITLE
[建议] 关于评论

### ISSUE THREAD

**Issue by lym12321** [solstice23/argon-theme#391]
- 建议使发送评论的人可以删除自己的评论  
- 建议在回复时使用类似 `@昵称` 或 `引用` 的方式，现在的方法虽然直观，但假设场景如下：
  - 两个人（或多个人）在评论区互动，需要互相进行回复：
  会出现类似于 <https://dev.dawn-light.cn/src/argon-2.png> 的情况，难以分清到底是相互的回复还是在上一级评论下的回复  
  （其嵌套逻辑与 <https://dev.dawn-light.cn/src/argon.png> 相同）  

对于第一条建议，大抵是有不少的需求的，如果 Wordpress 允许这种操作的话或许可以实现一下。
对于第二条建议，由于这种场景并不多见，是否修改都无妨。

**Comment by solstice23** [comment]
https://user-images.githubusercontent.com/23134847/152647788-04dc15a7-b9ad-4407-9288-9631f76fc6b8.mp4
