### ISSUE TITLE
短代码嵌套则无效

### ISSUE THREAD

**Issue by northword** [solstice23/argon-theme#395]
## 问题描述
短代码嵌套会导致里面的短代码不执行，
![image](https://user-images.githubusercontent.com/44738481/152798753-874d351c-eee2-4c0c-b44e-16fedd14111a.png)

## 可能的解决方案
可否通过判断短代码是否是嵌套的，然后嵌套的执行`do_shortcode`来解决？

**Comment by solstice23** [comment]
已支持，不过更推荐使用 Gutenberg 编辑器区块来插入折叠区块等

**Comment by northword** [comment]
> 已支持，不过更推荐使用 Gutenberg 编辑器区块来插入折叠区块等

收到，感谢！
这个网站是给课题组搞来着，那群老师用不来 Gutenberg ，所以被迫启用了经典编辑器哈哈哈
