### ISSUE TITLE
[功能建议]关于友情链接排序

### ISSUE THREAD

**Issue by lovelycatv** [solstice23/argon-theme#398]
因为友链比较多，想把一些友链放到前面，但并没有这个选项。
后台的链接->添加链接中还有一个"评级"，可不可以把这个作为权重，数值大的越靠前。
如果有同样权重的，就在一定范围内随意排序即可。
例如（括号内为评级，中括号内评级一致）：a(10)、b(1)、c(3)、d(3)、e(10)、f(3)、g(1)
可以排序成[a e] [c d f] [b g]
也可以是[e a] [d f c] [g b]

如果可以实现的话，就请麻烦了。

**Comment by northword** [comment]
https://argon-docs.solstice23.top/#/shortcode/friendlinks?id=%e5%8f%82%e6%95%b0
参考主题文档/友情链接列表/ `sort` 参数
