### ISSUE TITLE
能不能针对cdn做做优化呢？

### ISSUE THREAD

**Issue by anglesgirl** [solstice23/argon-theme#40]
我本人是使用cloudflare的，cdn可以缓存页面各种数据来加速访问

笨妞告诉我，使用get的请求才会被cloudflare缓存，动态交互的部分应该使用AJAX POST来绕过缓存

作者有没有时间研究一下针对cdn的优化，笨妞的cfp接入页面已经这样设计
你可以参考参考 http://cdn.mnn.tw (内测中，未完工)

虽然现在速度已经很快了，但是还能更快当然更好，对吧₊◝(●⁰⃚⃙̴ꇴ⁰⃚⃙̴●)◜✦

**Comment by Ryanjiena** [comment]
WordPress 使用 Cloudflare 作为 CDN 缓存的，可以尝使用 `WP Cloudflare Super Page Cache` 插件（使用的是Cloudflare 的 API 接口） 。

WP Cloudflare Super Page Caches 官方地址： [https://wordpress.org/plugins/wp-cloudflare-page-cache](https://wordpress.org/plugins/wp-cloudflare-page-cache)

插件里提供 绕过AJAX请求的缓存，绕过POST请求的缓存，绕过GET请求的缓存 的设置选项。另外，前台因为缓存问题看不到最新内容可以设置更新内容时自动删除CDN缓存。

**Comment by Ryanjiena** [comment]
另外，Cloudflare 的相关设置可以参考 `wp-cloudflare-page-cache` 作者的教程 ：[https://www.speedywp.it/cache-di-post-e-pagine-wordpress-con-cloudflare](https://www.speedywp.it/cache-di-post-e-pagine-wordpress-con-cloudflare)
