### ISSUE TITLE
argon主题支持谷歌广告插件吗？

### ISSUE THREAD

**Issue by RookieTerry** [solstice23/argon-theme#400]
如果不支持，那请问每个页面的body标签能在哪个文件找到呢？我要在其中插入广告代码

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/153389710-ed689782-b462-497c-84ac-466fd7a7d7fb.png)

**Comment by RookieTerry** [comment]
如果想在文章中插入script广告标签呢？我的是WordPress博客
