### ISSUE TITLE
升级到1.3.2及以上版本后，使用WP Githuber MD编写的文章代码块样式错乱

### ISSUE THREAD

**Issue by solderwire** [solstice23/argon-theme#402]
![](https://jyzbbucket-hk-1307778350.cos.ap-hongkong.myqcloud.com/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202022-02-11%20192428.jpg)

更新到1.3.2及以上版本后，使用该编辑器编辑的文章会出现代码块背景错乱的问题，疑似与1.3.2版本对代码块越界问题的修复有关。使用WP内置编辑器编辑的文章则不会出现该问题。
F12面板中没有报错信息，现在只能降级到1.3.0使用
望修复！

**Comment by solstice23** [comment]
请提供错误文章地址

**Comment by solderwire** [comment]
> 请提供错误文章地址

https://intermedice.cn/2022/01/18/packet-loss-solution-with-rinetd/

清理WP服务端和浏览器的缓存均不能解决该问题。
