### ISSUE TITLE
[bug] 访客不知道给我评论了个啥 留言板打不开了

### ISSUE THREAD

**Issue by BATTLEHAWK00** [solstice23/argon-theme#404]
网页卡在loading comments...  
console里提示json parse出错  
是在该访客评论后出现的错误
![image](https://user-images.githubusercontent.com/45313304/153626266-a03cd1a6-f6a2-4d66-8fcb-e241002ce459.png)
![image](https://user-images.githubusercontent.com/45313304/153626381-d184b567-8715-4954-9ddf-6e72e6965a65.png)
![image](https://user-images.githubusercontent.com/45313304/153626513-f443b233-c6a3-499c-b6a1-53ed6507b355.png)

**Comment by solstice23** [comment]
Argon 没有 Loading comments 这样的过程，请检查是否是插件所致

**Comment by BATTLEHAWK00** [comment]
> 

排查出来了 是hummingbird插件导致
