### ISSUE TITLE
同类型短代码嵌套失效

### ISSUE THREAD

**Issue by RichardHu714** [solstice23/argon-theme#405]
## 问题
同种类型的短代码嵌套出现识别错误的情况，实测提示、警告嵌套出现bug
## 测试代码
```[admonition title="我是标题" color="indigo"]靛蓝警告[admonition title="我是标题" color="green"]绿色警告[/admonition][/admonition]```

```[alert color="indigo"]靛蓝提示[alert color="green"]绿色提示[/alert][/alert]```
## 实际效果
![](https://www.tupians.top/imgs/2022/02/0ce93e8b188123dc.png)
![](https://www.tupians.top/imgs/2022/02/293f36da437d3183.png)

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/153628071-8c06b399-1b3c-4b37-9dc5-152d3ae7b0fe.png)

wordpress 特性，同类型的会解析成这样，暂时无解

可以使用 Gutenberg 编辑器配合短代码插入
