### ISSUE TITLE
argon-demo 站点无法打开设置

### ISSUE THREAD

**Issue by EchoGroot** [solstice23/argon-theme#406]
> argon-demo 站点可在线自定义 Argon 的各种设置，预览 Argon 的所有特性。

![image](https://user-images.githubusercontent.com/44628981/153695807-48714976-c5a9-4297-933c-51b500d80514.png)
## 点击左侧设置按钮
![image](https://user-images.githubusercontent.com/44628981/153695828-c40ca048-64b3-488e-921c-9f3d22ba93d0.png)

**Comment by solstice23** [comment]
Fixed
