### ISSUE TITLE
Bug反馈 关于首页卡片白色

### ISSUE THREAD

**Issue by Small-SaltedFish** [solstice23/argon-theme#408]
![image](https://user-images.githubusercontent.com/34180066/153710129-b96720a4-74af-4769-94c8-4dfe3365807b.png)
![image](https://user-images.githubusercontent.com/34180066/153710141-e81db346-a7ce-4c6c-9213-95492df52187.png)

**Comment by Jiaocz** [comment]
控制台有没有什么报错

**Comment by Andy17269** [comment]
打开wp的调试模式，错误代码有吗？

**Comment by solstice23** [comment]
主题色是不是白色了
