### ISSUE TITLE
评论页表情点开，要切换到其它表情有点费力。

### ISSUE THREAD

**Issue by ulifuqiang** [solstice23/argon-theme#411]
![微信截图_20220213124801](https://user-images.githubusercontent.com/25083314/153739179-00bb9578-91b6-4c9f-aeff-3a331a54a924.png)

**Comment by solstice23** [comment]
往下滚动下看看

**Comment by ulifuqiang** [comment]
往下滚动看到切换，要是能默认显示出来就更好了。
