### ISSUE TITLE
jsDelivr的镜像站点问题

### ISSUE THREAD

**Issue by Jiaocz** [solstice23/argon-theme#420]
非常棒的是，一觉醒来区域ISP的DNS给把 `cdn.jsdelivr.net` 解析到了 `0.0.0.0`
![image](https://user-images.githubusercontent.com/14857984/153837109-5b4b4cfa-060d-4f45-88b6-d60adae2beb2.png)

自己的博客、作者的博客及其他使用了jsd的小伙伴全部收到了影响。经过搜寻找到了几个jsd的官方镜像站：
- gcore.jsdelivr.net
- fastly.jsdelivr.net
- testingcf.jsdelivr.net
分别由不同的jsd赞助商提供cdn，并且目前没有看到DNS污染的事。

**想来问一下，有没有必要在设置页面分别列出这些jsd的cdn，以增加选项方便博客维护者进行更换**

---
<details>
  <summary><b>速度测试结果</b></summary>
  <ul>
    <li><a href="https://www.boce.com/http/gcore.jsdelivr.net/vs/fastly.jsdelivr.net/d232bf27cf111bebd9a6bf5d8c8b1f72.html" target="_blank"><img src="https://user-images.githubusercontent.com/14857984/153837863-07a8dcc1-f0f0-461c-b0b1-d7e8c40e2e92.png" /><br />https://www.boce.com/http/gcore.jsdelivr.net/vs/fastly.jsdelivr.net/d232bf27cf111bebd9a6bf5d8c8b1f72.html</a></li>
    <li><a href="https://www.boce.com/http/cdn.jsdelivr.net/vs/testingcf.jsdelivr.net/ab92554b53b0395b771f6a4d13a75ba4.html" target="_blank"><img src="https://user-images.githubusercontent.com/14857984/153838348-f97ec494-7bb5-498c-99f4-24e870f5bf7c.png" /><br />https://www.boce.com/http/cdn.jsdelivr.net/vs/testingcf.jsdelivr.net/ab92554b53b0395b771f6a4d13a75ba4.html</a></li>

</details>

**Comment by solstice23** [comment]
我们 ____ 真是太厉害啦
不想说什么了，我加一个自定义 CDN 地址好了

**Comment by Jiaocz** [comment]
> 我们 ____ 真是太厉害啦 不想说什么了，我加一个自定义 CDN 地址好了

在询问官方是否会开启DNSSEC来减少DNS被修改，，，本来cdn前缀是自动解析cf/gcore/fastly三家服务的，现在如果换了就只能指定某一家服务了。

可以用各种测试试一下，最近经常发现被偷改为0.0.0.0或者127.0.0.1
