### ISSUE TITLE
关于副标题调用接口的问题

### ISSUE THREAD

**Issue by laoguanTX** [solstice23/argon-theme#422]
嗷嚎，作者你好，又是我，这是我第四次向您提出问题了。
出于我对WordPress不太了解，请问如何在副标题调用“今日诗词”或者“一言”？

**Comment by solstice23** [comment]
https://www.jinrishici.com/doc/

**Comment by laoguanTX** [comment]
忘说了，这个我是看过的，但是我并没有在找到在哪里修改标题

**Comment by yzxoi** [comment]
argon settings-left sidebar-subtitle

**Comment by laoguanTX** [comment]
对不起才看到，很感谢您的回答，那么banner副标题应如何修改，使其支持html
