### ISSUE TITLE
BUG反馈 评论审核功能失效

### ISSUE THREAD

**Issue by Suiyi-Light** [solstice23/argon-theme#424]
待审核评论在前端显示

已测试关闭所有插件，问题仍然存在
怀疑是主题最近评论功能更新所致

主题版本1.3.4
wp5.9

**Comment by Jiaocz** [comment]
我通过Rest API调用评论的话，没有审核的评论不会出现，可能是生成HTML的时候跳过了

**Comment by Suiyi-Light** [comment]
这样的话，评论者查看自己待审核评论的特性就没有了
