### ISSUE TITLE
评论无法打出斜杠问题

### ISSUE THREAD

**Issue by zlxFTH** [solstice23/argon-theme#426]
我在主题设置里面开启了评论使用 MarkDown 和数学公式 KaTex，但是评论无法正确打出 "\"，导致很多数学公式无法正确显示，请问一下有什么解决方法。

**Comment by zlxFTH** [comment]
好吧这里的斜杠也被屏蔽了

**Comment by zlxFTH** [comment]
\\

**Comment by solstice23** [comment]
"\"

**Comment by zlxFTH** [comment]
好像只有打出两个斜杠才能显示一个

**Comment by hiikii** [comment]
Markdown 里反斜杠是个特殊的符号，是用来转义的，你如果要在内容上显示反斜杠本身，需要写两次而不是一次。
