### ISSUE TITLE
feature:用户墙 

### ISSUE THREAD

**Issue by EchoGroot** [solstice23/argon-theme#430]
能否提供个地方展示使用案例，让使用者么都能录入自己的站点。毕竟这个主题支持很多自定义操作，让新用户能看到更多的使用案例。

**Comment by northword** [comment]
如果要加的话，可以加在文档里，形如 [vuepress-theme-vdoing 案例](https://doc.xugaoyi.com/pages/5d571c) ，并开一个 issue 用作申请。但这需要被经常维护，避免有些站点可能不再维护或加了案例后又自己换了主题之类的。

**Comment by solstice23** [comment]
@EchoGroot good idea, todo

**Comment by EchoGroot** [comment]
维护确实是个问题，换主题就尴尬了，得写程序去监控

**Comment by solstice23** [comment]
https://argon-showcase.solstice23.top
