### ISSUE TITLE
首页说说从折叠状态展开后与其他卡片重叠

### ISSUE THREAD

**Issue by crowya** [solstice23/argon-theme#431]
![cut_20225226125238](https://user-images.githubusercontent.com/61354956/155829598-d34c5de4-973c-4dcd-ae2d-aa2a649ef41f.png)
![cut_20225226125204](https://user-images.githubusercontent.com/61354956/155829580-7ea2b31c-e84c-4bf6-bea8-d0dbf0721889.png)

**Comment by crowya** [comment]
另外是否考虑下增加一个设置项，让用户自定义“说说”的名字

**Comment by solstice23** [comment]
展开以后其他块位置可能会变动（目前贪心计算瀑布流位置），有两个选择
1. 平滑过渡
2. 每张卡片保持原来的列位置

**Comment by solstice23** [comment]
后者可以使用 wordpress 的翻译 filter

**Comment by Suiyi-Light** [comment]
![image](https://user-images.githubusercontent.com/69178257/159205529-6c1ae6f7-7493-4ef9-bd90-db7b49298a47.png)
后加载的音乐播放器，应该是同样的问题

**Comment by solstice23** [comment]
https://github.com/solstice23/argon-theme/commit/bcee75b2fb53b358c0363f2f6bbb2a223046e74a
