### ISSUE TITLE
WP Editor.md插件兼容性问题

### ISSUE THREAD

**Issue by FlyLolo** [solstice23/argon-theme#432]
![image](https://user-images.githubusercontent.com/9459248/155930977-e7491633-9e11-4a15-9f02-0e30ca29835a.png)
如上图，开启WP Editor.md插件，会出现以下问题：
1. 左侧的文章目录无法显示。
2. 文章中的图片一直转圈，右上角也有个一直转圈的图标
3. 页面顶部的加载进度条一直无法到达终点，非常慢

2,3两个问题在刷新页面后消失，一切正常

**Comment by northword** [comment]
> 1. 左侧的文章目录无法显示。
https://github.com/solstice23/argon-theme/issues/253#issuecomment-894138361

> 2,3两个问题在刷新页面后消失，一切正常
尝试关闭 pjax 后是否正常？

**Comment by FlyLolo** [comment]
刚测试了一下WP Githuber MD，  这个markdown插件是正常的，或许那个太老了

**Comment by solstice23** [comment]
@FlyLolo 开启兼容模式

**Comment by FlyLolo** [comment]
总结一下： 

- WP Editor.md：
关闭 pjax 后，可修复问题2，3，目录仍无法正常显示
开启兼容模式，未关闭pjax，即可修复1,2,3

- WP Githuber MD
采用此插件可正常使用。

感谢两位非常快的回复
