### ISSUE TITLE
网站使用IP访问正常，使用域名访问部分的icon无法显示，这个怎么解决呢?

### ISSUE THREAD

**Issue by LTlw** [solstice23/argon-theme#436]
这是我用IP进行访问的：
![image](https://user-images.githubusercontent.com/44549832/156499266-c19f5ead-2042-4d42-93d4-21fb857722c4.png)
域名访问会出现如下情况，icon显示不出来
![image](https://user-images.githubusercontent.com/44549832/156499425-00790336-1c4b-4954-a4c5-83d7128524aa.png)

图标设置都是按用户手册直接使用的 Font Awesome库

宝塔面板部署的时候我是先使用的IP，后面再进行域名的绑定，然后用域名访问就是这样结果？
有没有懂哥教教，求求了？

**Comment by Jiaocz** [comment]
你看看F12的报错，是不是跨域了
