### ISSUE TITLE
首页说说代码块渲染不正确

### ISSUE THREAD

**Issue by Ghost-chu** [solstice23/argon-theme#439]
首页
<img width="477" alt="image" src="https://user-images.githubusercontent.com/30802565/157435834-e73a88c1-ca80-4be4-8c97-bd8d673cd6d4.png">
打开说说后
<img width="871" alt="image" src="https://user-images.githubusercontent.com/30802565/157435874-381fcab9-1efe-4283-8cde-38f91a3ceec0.png">

**Comment by Ghost-chu** [comment]
补充：夜间模式下行为就更奇怪了：
<img width="477" alt="image" src="https://user-images.githubusercontent.com/30802565/157435955-a1b9b396-bcbb-411e-a40b-b66c96733960.png">

**Comment by solstice23** [comment]
1. feature
2. 夜间模式待修
