### ISSUE TITLE
頂部Banner標題與副標題不顯示

### ISSUE THREAD

**Issue by Nebulosa-Cat** [solstice23/argon-theme#454]
![image](https://user-images.githubusercontent.com/30948446/162378473-dbbe6f1e-b4e3-4304-bdaf-ee4e0cc7bc7b.png)
如圖

這一項設定我只有開打字機效果而已，關掉依然是這樣的錯誤

**Comment by Nebulosa-Cat** [comment]
![image](https://user-images.githubusercontent.com/30948446/162378574-8d0e95e6-6c25-407f-a1bd-cfe7e006ee01.png)

錯誤狀態演示

**Comment by EvanLuo233** [comment]
看console

**Comment by Nebulosa-Cat** [comment]
> 看console

開發人員工具無法載入來源對應：無法載入 chrome-extension://lcghoajegeldpfkfaejegfobkapnemjl/lib/browser-polyfill.js.map 的內容：系統錯誤: net::ERR_BLOCKED_BY_CLIENT

看起來可能和這個有關，不確定是不是瀏覽器預設封鎖這個功能了?
目前測試下來
Chrome、Edge、Vivaldi都不行
手機版Safari可以

**Comment by Nebulosa-Cat** [comment]
> > 看console
> 
> 開發人員工具無法載入來源對應：無法載入 chrome-extension://lcghoajegeldpfkfaejegfobkapnemjl/lib/browser-polyfill.js.map 的內容：系統錯誤: net::ERR_BLOCKED_BY_CLIENT
> 
> 看起來可能和這個有關，不確定是不是瀏覽器預設封鎖這個功能了? 目前測試下來 Chrome、Edge、Vivaldi都不行 手機版Safari可以

F12的console目前也只有看到這個黃字

**Comment by Nebulosa-Cat** [comment]
![image](https://user-images.githubusercontent.com/30948446/170237789-d79bd3e9-be71-4fa1-a36a-2f91319de7b3.png)

換使用 Chrome 開啟 Console到有新的警告出現了

**Comment by EvanLuo233** [comment]
開啟打字動畫可以看到，你關閉打字動畫，讓我排查一下具具體錯誤
<img width="1440" alt="Screen Shot 2022-05-26 at 17 04 19" src="https://user-images.githubusercontent.com/68590232/170456121-e63e4200-1a3c-42d3-a413-21e9fc821eeb.png">

**Comment by Nebulosa-Cat** [comment]
開啟狀態
![image](https://user-images.githubusercontent.com/30948446/172630433-5594d180-504e-43da-85b3-ba44998ef937.png)

關閉狀態
![image](https://user-images.githubusercontent.com/30948446/172630644-8612808e-48a3-4479-92ac-d1f083e132ba.png)

@EvanNotFound

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/172631053-a670be81-175a-4a90-8cd8-08dd33d49ec8.png)
似乎无法复现

**Comment by Nebulosa-Cat** [comment]
@EvanNotFound 

關閉狀態
![image](https://user-images.githubusercontent.com/30948446/172630921-b4265ac0-a3c2-4f49-9287-a53bf3d4d647.png)

瀏覽器是擋廣告插件那些全關狀態

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/172631291-525bd92c-812f-4bea-af87-13799ad5555b.png)
请检查此元素和其 CSS 是否正常

**Comment by Nebulosa-Cat** [comment]
![image](https://user-images.githubusercontent.com/30948446/172631512-9e48be99-134c-493b-8f59-23b409839dba.png)
對了一下應該是一樣的

然後下面
![image](https://user-images.githubusercontent.com/30948446/172632441-65a4746d-fa43-47b1-9ce1-89e3227939ea.png)

**Comment by solstice23** [comment]
似乎没什么问题。很奇怪的是我这无法复现（chrome 和 Edge 最新版），请尝试**禁用**所有插件（在浏览器中禁用、隐身模式）并测试是否能够复现。

**Comment by Nebulosa-Cat** [comment]
Edge (我直接砍光插件並於隱身模式開啟)
![image](https://user-images.githubusercontent.com/30948446/172634334-62af9e94-1827-4895-a763-ae74f91b121f.png)

Chrome (全新安裝並於無痕模式)
![image](https://user-images.githubusercontent.com/30948446/172635841-64e5ae16-4f5b-4d48-a2a4-44f8910dd65e.png)

這問題的確挺奇怪，我手機版網頁反而可以看到

**Comment by Nebulosa-Cat** [comment]
應該不是DNS，手機和電腦用的是同一個DNS
本地問題可就麻煩了...
大海撈針

**Comment by EvanNotFound** [comment]
<img width="1220" alt="Screen Shot 2022-06-08 at 22 10 52" src="https://user-images.githubusercontent.com/68590232/172638342-1873c221-5440-4183-8618-5b07b4421671.png">

使用GTmetrix分析的网页快照也显示正常，判定为本地问题

**Comment by 928882650** [comment]
@Nebulosa-Cat 请看下是不是浏览器开启了AdGuard插件
