### ISSUE TITLE
关于一个萌新对表情功能的疑问（开发中）

### ISSUE THREAD

**Issue by Andy17269** [solstice23/argon-theme#455]
作者您好！我想问一下关于表情功能的问题：
1.为什么按您的模板来做，同时使用两个表情包（一个插件一个），启用时显示："Fatal error: Cannot redeclare add_more_emotions() (previously declared in /www/wwwroot/Boke/wp-content/plugins/BiliBili/index.php:13) in /www/wwwroot/Boke/wp-content/plugins/argon-huhu-emotions/argon_huhu_emotions.php on line 14"，但如果修改了add_more_emotions（比如把add_more_emotions改成add_huhu_emotions），可以启用插件，但在评论表情栏中却找不到它？
2.如果我要一个插件多个表情组，该如何编写？大佬能否给出示例代码？
**望作者回复！谢谢！**

**Comment by solstice23** [comment]
@Andy17269 数组里追加两个子数组即可

**Comment by Andy17269** [comment]
能否具体说明？

**Comment by Andy17269** [comment]
谢谢
