### ISSUE TITLE
插件	 Mine Video Player 与pjax 方式加载页面无法兼容

### ISSUE THREAD

**Issue by JIM353** [solstice23/argon-theme#456]
该插件为视频播放插件，在首页刷新可以正常使用，但是进入到文章也无法正常打开，如图
正常加载：
![image](https://user-images.githubusercontent.com/53323241/162557577-fa3cf62e-c690-4ed2-bd9c-5c17adaa2c66.png)
无状态栏及视频：
![image](https://user-images.githubusercontent.com/53323241/162557588-944b4a3e-f77d-4e61-8b58-913e8061dd71.png)

配置如下：
<img width="661" alt="image" src="https://user-images.githubusercontent.com/53323241/162557611-432e27b6-31be-4919-90d6-a2a57ee680c0.png">

望作者回复，谢谢！

**Comment by solstice23** [comment]
上面的红字

**Comment by JIM353** [comment]
请问是这样配置吗
![image](https://user-images.githubusercontent.com/53323241/162568100-96a85d60-7673-4460-98cc-3a9b9177e640.png)

**Comment by huangwb8** [comment]
@JIM353 请问您成功了吗？最近我也遇到了Pjax不回调JS的问题，但我用`window.pjaxLoaded`函数并没有成功。
