### ISSUE TITLE
【Bug】近期文章中会出现隐藏的文章

### ISSUE THREAD

**Issue by Mars160** [solstice23/argon-theme#458]
如题，在首页的近期文章中，会出现隐藏类别的文章，用户也因此可以见到站长不希望他们可以看到的东西

**Comment by Mars160** [comment]
归档中也会出现该文章

**Comment by solstice23** [comment]
隐藏类别并不是隐藏文章本身（此功能是为了使首页更简洁，隐藏一些文章，使其要在专门分类页面查看）。要想隐藏文章，请将文章设为“私密”。
