### ISSUE TITLE
左边栏宽度调整

### ISSUE THREAD

**Issue by huangwb8** [solstice23/argon-theme#459]
请问左边栏的这个宽度可以调整一下吗？我想调大一些以便可以让网易云短代码看上去协调一些！如图所示：

![](https://raw.githubusercontent.com/huangwb8/GithubPicture/main/img/20220412103039.png)

**Comment by solstice23** [comment]
@huangwb8 TODO

**Comment by huangwb8** [comment]
@solstice23 大佬，没有理解您的意思呀~是指在计划中吗？还是指To-Do List有关的设置呀

**Comment by solstice23** [comment]
计划中，后续会支持自由调整宽度

**Comment by huangwb8** [comment]
@solstice23 大佬YYDS!!
