### ISSUE TITLE
一个功能建议

### ISSUE THREAD

**Issue by Andy17269** [solstice23/argon-theme#460]
开发者您好！请问能否更新下[Font Awesome 4](https://fontawesome.com/v4/icons/)图标库？比如更新成**Font Awesome 6**图标库？

**Comment by Suiyi-Light** [comment]
https://github.com/solstice23/argon-theme/issues/401#issuecomment-1034981275

**Comment by solstice23** [comment]
尝试过升级到 6.0，但由于 6.0 Free 相比 4.0 部分图标缺少，其他图标免费版也不尽人意，所以回滚了
