### ISSUE TITLE
Markdown中链接未自动显示

### ISSUE THREAD

**Issue by huangwb8** [solstice23/argon-theme#463]
我最近发现，我在markdown里的链接，渲染到html后没有超链接的效果

![image](https://user-images.githubusercontent.com/35643122/164268737-1c7d97d2-0e13-4a69-aa18-673f323886fb.png)

这和我在Typora中的使用不太一样。是我设置的不对吗？

大佬们可以给点建议不？

**Comment by solstice23** [comment]
主题无关

**Comment by huangwb8** [comment]
确定不是主题的问题后，我想了一下，直接用
`[链接](链接)`的方法。

可能是自用的Typora太强大了，所以对于原生链接一直没有用一个比较严谨的写法。

谢谢大佬的帮助！
