### ISSUE TITLE
博客布局崩了，重装后依然无法解决

### ISSUE THREAD

**Issue by ccc592** [solstice23/argon-theme#466]
<img width="1635" alt="image" src="https://user-images.githubusercontent.com/63574264/164984427-ad5f86b9-4c4c-447e-a19f-c47661ae2a63.png">
<img width="1378" alt="image" src="https://user-images.githubusercontent.com/63574264/164984440-8e741cd3-aece-4bfd-9561-53b6c2835867.png">

**Comment by EvanLuo233** [comment]
换cdn，建议关闭
