### ISSUE TITLE
请问文档小标题如何实现的

### ISSUE THREAD

**Issue by shizhou1993** [solstice23/argon-theme#469]
![image](https://user-images.githubusercontent.com/22760752/165356847-89a1cb36-75c3-4f0f-8b73-6fe4989092e3.png)
找遍了文档都没找到，哭了

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/165981403-a43748ee-ca0a-4d3d-b5af-7e0fdf902ca1.png)

`<h1>` ~ `<h6>`
