### ISSUE TITLE
代码显示不完整

### ISSUE THREAD

**Issue by Qxin-X** [solstice23/argon-theme#470]
**后台代码正常，是这样的**
![a9a8cdd6dccaaf5e41ef3f2f69dd044](https://user-images.githubusercontent.com/66522154/165977520-4eceb60b-9269-4f60-bb92-8418f76ee2ee.png)

**访问时候变成这样，缺失了**
![88993e97f7d2e51cc0d0603ad44872e](https://user-images.githubusercontent.com/66522154/165977505-c12b7a62-3120-42c4-bc53-dac1682436a6.png)

**这是 bug 吗，因为多个 <> 这种，导致解析出错了？**

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/165978393-c8577452-b702-4862-8eae-295d23c36bcc.png)
似乎无法复现

**Comment by Qxin-X** [comment]
> ![image](https://user-images.githubusercontent.com/23134847/165978393-c8577452-b702-4862-8eae-295d23c36bcc.png) 似乎无法复现

我用的 java，后台添加的是 java 代码，清理缓存，换个浏览器也不行，手机也试过了，都一样

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/165979067-a06d20ec-d692-4b35-9a62-eb4a3dd4ddf0.png)
![image](https://user-images.githubusercontent.com/23134847/165979095-c8a589d6-3469-4656-84e1-fa8fbbf842b5.png)

**Comment by Qxin-X** [comment]
> ![image](https://user-images.githubusercontent.com/23134847/165979067-a06d20ec-d692-4b35-9a62-eb4a3dd4ddf0.png) ![image](https://user-images.githubusercontent.com/23134847/165979095-c8a589d6-3469-4656-84e1-fa8fbbf842b5.png)

还是不行，邪门了,单单 <>是可以显示的，但是 <String> 就消失了，好像只要 <>里边有内容就连 <> 一起消失了，有没有能推出可能是什么原因

**Comment by Qxin-X** [comment]
> > ![image](https://user-images.githubusercontent.com/23134847/165979067-a06d20ec-d692-4b35-9a62-eb4a3dd4ddf0.png) ![image](https://user-images.githubusercontent.com/23134847/165979095-c8a589d6-3469-4656-84e1-fa8fbbf842b5.png)
> 
> 还是不行，邪门了,单单 <>是可以显示的，但是 就消失了，好像只要 <>里边有内容就连 <> 一起消失了，有没有能推出可能是什么原因

这个<String> 一评论就消失，github 也是这样

![6c3b117ac578299d20dd2d7749a67f4](https://user-images.githubusercontent.com/66522154/165982187-52cea5c1-34f8-42ca-a4e9-f5a808035c70.png)

**Comment by solstice23** [comment]
`<String>`
\<String\>

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/165982424-c4b073b5-1a54-4f50-bd74-2e1f332a434d.png)

**Comment by Qxin-X** [comment]
> `<String>` <String>

还是不行，如果你那边正常的话，应该是我这边的问题，明天排查调试一下，推测可能跟 markdown 编辑插件有关，我不是用 wp 自带的编辑器，感谢给出指导
