### ISSUE TITLE
目录树不显示的问题

### ISSUE THREAD

**Issue by whjysh** [solstice23/argon-theme#473]
如图所示左侧目录树不显示，不清楚怎么解决
![image](https://user-images.githubusercontent.com/40263315/166098546-a4dcd557-1c54-4de9-9a27-91367331e21c.png)

**Comment by solstice23** [comment]
F12 有报错信息吗

**Comment by whjysh** [comment]
> F12 有报错信息吗

![image](https://user-images.githubusercontent.com/40263315/166099332-dcf99018-a330-4c50-9a04-5f65e20fb601.png)

**Comment by solstice23** [comment]
请检查是否有不兼容的插件

https://argon-docs.solstice23.top/#/faq?id=q-%e5%ae%89%e8%a3%85%e4%ba%86-editormd-%e6%8f%92%e4%bb%b6%ef%bc%8cconsole-%e6%8a%a5%e9%94%99
