### ISSUE TITLE
能否考虑将首页文章块变得更简洁

### ISSUE THREAD

**Issue by youthriverside** [solstice23/argon-theme#48]
因为打开时看到许多相关信息并不是很简洁，能否考虑将首页文章块变得更简洁，剔除不必要的东西。如评论数之类的，或者能否添加一个选项关闭

**Comment by solstice23** [comment]
考虑加入自定义 Meta 信息功能

**Comment by solstice23** [comment]
已支持自定义 Meta 信息功能，位置："Argon 设置 - 文章"
