### ISSUE TITLE
文章分享生成的微信二维码不会随文章变动而改变

### ISSUE THREAD

**Issue by hiikii** [solstice23/argon-theme#480]
由于我浏览器装的各类扩展比较多，为了保证测试结果可靠，使用了默认配置的 EDGE 进行测试，结果发现不论打开哪篇文章，生成的微信二维码始终为初次打开文章的链接，目测是和 pjax 相关？

**Comment by solstice23** [comment]
即将到来的 dev 分支已经重写二维码模块
