### ISSUE TITLE
顶部导航栏的搜索后404

### ISSUE THREAD

**Issue by qll-yin** [solstice23/argon-theme#483]
主页的搜索之前可以的，但是捣腾了之后搜索就变成了404，这是为什么呀？

**Comment by solstice23** [comment]
https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by solstice23** [comment]
为什么不使用 issue template 详细描述问题呢？

**Comment by qll-yin** [comment]
### 在主页导航栏的搜索 跳转到了404
在刚安装好主题时是没问题的，后面我给我的主页添加了菜单后，
又或者是更改了某些设置，导致我今天使用导航栏的搜索时，输入内容跳转显示没有该网页，报错代码404，
我有些头绪，就是我没创建这个搜索后的网页，但是也不知道是怎么没的，因为之前有成功过，
麻烦solstice23大大帮我看一下是个什么原因吧~
[我的网站主页](http://182.61.1.186/)

- 404页面

![image](https://user-images.githubusercontent.com/86601137/168268125-cd2032f0-d3c5-436b-acc2-81ebe7166af7.png)

- 请求链接信息

![image](https://user-images.githubusercontent.com/86601137/168268154-b7169dcb-7706-4698-8e59-08c1a78c99c5.png)
