### ISSUE TITLE
[Bug] 点击搜索功能跳转显示404

### ISSUE THREAD

**Issue by qll-yin** [solstice23/argon-theme#485]
### 主题版本

1.3.5

### Bug 类型

该 Bug 是后端问题

### 浏览器

Chrome / Edge

### 普遍性

是

### 问题描述

在刚安装好主题时是没问题的，后面我给我的主页添加了菜单后，
又或者是更改了某些设置，导致我今天使用导航栏的搜索时，输入内容跳转显示没有该网页，报错代码404，
我有些头绪，就是我没创建这个搜索后的网页，但是也不知道是怎么没的，因为之前有成功过，
麻烦solstice23大大帮我看一下是个什么原因吧~
[我的网站主页](http://182.61.1.186/)

### 复现步骤

频繁出现，就是点击搜索就会出现404，找不到页面

### 截图

- 404页面

![image](https://user-images.githubusercontent.com/86601137/168268125-cd2032f0-d3c5-436b-acc2-81ebe7166af7.png)

- 请求链接信息

![image](https://user-images.githubusercontent.com/86601137/168268154-b7169dcb-7706-4698-8e59-08c1a78c99c5.png)

### 附加说明

还有就是评论出现的问题，之前可以，现在也评论不了，点击发送就显示 发送失败，未知错误...麻烦solstice23大大进我的网站看一下吧

**Comment by solstice23** [comment]
设置了错误的子目录前缀

**Comment by qll-yin** [comment]
> 设置了错误的子目录前缀

那我要怎么修改呢？

**Comment by qll-yin** [comment]
> 设置了错误的子目录前缀

已经可以啦，感谢！原来是那个argon主题选项里的子目录我添加了个安装子目录，可实际上是没有的，现在已经没问题了

**Comment by Andy17269** [comment]
就现在这网络环境，不要把IP暴露了，否则很容易被D的

**Comment by qll-yin** [comment]
> 就现在这网络环境，不要把IP暴露了，否则很容易被D的

嗯嗯，好的

**Comment by qll-yin** [comment]
> > 就现在这网络环境，不要把IP暴露了，否则很容易被D的
> 
> 嗯嗯，好的

谢谢提醒啦，
![C58F8D09701F6FDA228E109372DA20D8](https://user-images.githubusercontent.com/86601137/169808188-076ea8c2-e385-4eb5-8130-bd2571a649fc.png)

**Comment by solstice23** [comment]
可以去github discussion讨论，此讨论串我之前就unsubscribe了(
