### ISSUE TITLE
[Bug] Source Global CDN和Fastgit这两个cdn无法正常使用

### ISSUE THREAD

**Issue by BA7JCM** [solstice23/argon-theme#486]
### 主题版本

v1.3.5

### Bug 类型

该 Bug 是前端问题，且似乎和浏览器无关

### 浏览器

此问题与前端无关

### 普遍性

否，只出现在特定的网站，但触发条件未知

### 问题描述

Fastgit和Source Global CDN两个cdn挂了

### 复现步骤

在wp后台主题设置中cdn选择Source Global CDN或者选择Fastgit然后保存，不过不知道是不是我这边的网络问题，我选择这俩个cdn的话前端就有文件无法加载，导致布局乱了，我现在已将cdn切为”不使用“

### 截图

![image](https://user-images.githubusercontent.com/79561519/168537148-7095104f-9d4e-47f0-b861-4bafd9264223.png)
![image](https://user-images.githubusercontent.com/79561519/168537658-866fb36a-d304-47e0-880f-56741242a912.png)

**Comment by EvanLuo233** [comment]
建议更换自己的cdn，用oss搭建一个就行

**Comment by BA7JCM** [comment]
> 建议更换自己的cdn，用oss搭建一个就行

我看了主题里面对应部分的代码，并还原出了github直链，然后填github直链到自定义CDN那里，结果还是不行，提示说类型不对好像是，说给的类型是文本，而要求的是CSS

**Comment by EvanLuo233** [comment]
填主题的地址，比如`argon`文件夹下有argon的主题文件，那么就直接填argon的文件夹地址。
<img width="617" alt="Screen Shot 2022-05-22 at 10 40 47" src="https://user-images.githubusercontent.com/68590232/169675908-7688ed03-ef6a-4b53-b239-a60c08a1a6ed.png">
比如这样

**Comment by BA7JCM** [comment]
> 填主题的地址，比如`argon`文件夹下有argon的主题文件，那么就直接填argon的文件夹地址。
> <img width="617" alt="Screen Shot 2022-05-22 at 10 40 47" src="https://user-images.githubusercontent.com/68590232/169675908-7688ed03-ef6a-4b53-b239-a60c08a1a6ed.png">
> 比如这样
> 

那我直接设置“不使用”跟这个有啥区别，不都是从自己服务器加载……

**Comment by EvanLuo233** [comment]
你可以把主题文件夹传到oss，然后获取文件直链，就可以加速了

**Comment by Andy17269** [comment]
自建CDN会让图标挂了，不知道怎么办

**Comment by EvanLuo233** [comment]
开启跨域访问，谷歌请

**Comment by EvanLuo233** [comment]
我用的阿里云oss，开启跨域请求以后正常使用

**Comment by Andy17269** [comment]
套了腾讯CDN，其他正常，就是图标不行

**Comment by Andy17269** [comment]
网站是https://wenlei.club

**Comment by EvanLuo233** [comment]
都说了，开启跨域资源访问。f12看console就可以看出具体错误，就是跨域问题，你去谷歌搜一下腾讯怎么开启。也可以找我用我的cdn，加wx

**Comment by EvanLuo233** [comment]
这个是我谷歌找到的，你可以试试看https://cloud.tencent.com/developer/information/cdn%E8%B7%A8%E5%9F%9F#:~:text=%E7%99%BB%E5%BD%95%E8%85%BE%E8%AE%AF%E4%BA%91CDN%EF%BC%8C%E7%84%B6%E5%90%8E,%E5%9F%9F%EF%BC%8C%E5%85%B6%E4%BB%96%E5%9F%9F%E5%90%8D%E4%B8%8D%E5%85%81%E8%AE%B8%E3%80%82

**Comment by Andy17269** [comment]
稍等，我试试

**Comment by BA7JCM** [comment]
> 你可以把主题文件夹传到oss，然后获取文件直链，就可以加速了

```
https://raw.githubusercontent.com/solstice23/argon-theme/v%theme_version%/
```
我自定义cdn填的这个，但是浏览器console会报类型不对

**Comment by Andy17269** [comment]
> > 你可以把主题文件夹传到oss，然后获取文件直链，就可以加速了
> 
> ```
> https://raw.githubusercontent.com/solstice23/argon-theme/v%theme_version%/
> ```
> 
> 我自定义cdn填的这个，但是浏览器console会报类型不对
最后一个前面为什么要加V，是不是打错了？

**Comment by BA7JCM** [comment]
> > > 你可以把主题文件夹传到oss，然后获取文件直链，就可以加速了
> > 
> > 
> > ```
> > https://raw.githubusercontent.com/solstice23/argon-theme/v%theme_version%/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我自定义cdn填的这个，但是浏览器console会报类型不对
> > 最后一个前面为什么要加V，是不是打错了？

他主题版本就是1.2.3这样的数字，GitHub直链里面版本是v1.2.3这样的
![image](https://user-images.githubusercontent.com/79561519/169682150-8fb85804-d0af-47a7-8780-a710d7f584c7.png)

**Comment by Andy17269** [comment]
> > 你可以把主题文件夹传到oss，然后获取文件直链，就可以加速了
> 
> ```
> https://raw.githubusercontent.com/solstice23/argon-theme/v%theme_version%/
> ```
> 
> 我自定义cdn填的这个，但是浏览器console会报类型不对
https://cdn.wenlei.club/Argon-Theme/%theme_version% 不用加v

**Comment by BA7JCM** [comment]
> > > 你可以把主题文件夹传到oss，然后获取文件直链，就可以加速了
> > 
> > 
> > ```
> > https://raw.githubusercontent.com/solstice23/argon-theme/v%theme_version%/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我自定义cdn填的这个，但是浏览器console会报类型不对
> > 最后一个前面为什么要加V，是不是打错了？

![image](https://user-images.githubusercontent.com/79561519/169682186-64a27568-cfd2-4847-90d5-56af0cbada40.png)
没有打错，直接浏览器打开被程序拼凑后的GitHub直链能看到内容，但就是浏览器报类型不对

**Comment by Andy17269** [comment]
> > > > 你可以把主题文件夹传到oss，然后获取文件直链，就可以加速了
> > > 
> > > 
> > > ```
> > > https://raw.githubusercontent.com/solstice23/argon-theme/v%theme_version%/
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 我自定义cdn填的这个，但是浏览器console会报类型不对
> > > 最后一个前面为什么要加V，是不是打错了？
> 
> 他主题版本就是1.2.3这样的数字，GitHub直链里面版本是v1.2.3这样的 ![image](https://user-images.githubusercontent.com/79561519/169682150-8fb85804-d0af-47a7-8780-a710d7f584c7.png)
GitHub开了防盗链，您要上传到自己的服务器上

我这样不加v没事

**Comment by Andy17269** [comment]
> > > > 你可以把主题文件夹传到oss，然后获取文件直链，就可以加速了
> > > 
> > > 
> > > ```
> > > https://raw.githubusercontent.com/solstice23/argon-theme/v%theme_version%/
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 我自定义cdn填的这个，但是浏览器console会报类型不对
> > > 最后一个前面为什么要加V，是不是打错了？
> 
> ![image](https://user-images.githubusercontent.com/79561519/169682186-64a27568-cfd2-4847-90d5-56af0cbada40.png) 没有打错，直接浏览器打开被程序拼凑后的GitHub直链能看到内容，但就是浏览器报类型不对

Github防盗链，上传到自己服务器上或用托管

**Comment by EvanLuo233** [comment]
github开了防盗链

**Comment by BA7JCM** [comment]
> github开了防盗链

他内置的几个cdn也都是GitHub的反代站
![image](https://user-images.githubusercontent.com/79561519/169682303-989c0342-18f1-477e-ba13-d99c1571b24b.png)
`/wp-content/themes/argon-theme-master/functions.php`第十五行到第十四行

**Comment by Andy17269** [comment]
argon_js_merged.js?ver=1.3.5:2 
        
       Uncaught TypeError: $(...).tooltip is not a function
    at HTMLDocument.<anonymous> (argon.min.js?ver=1.3.5:18:689)
    at j (argon_js_merged.js?ver=1.3.5:2:29999)
    at k (argon_js_merged.js?ver=1.3.5:2:30313)
这是报错

**Comment by Andy17269** [comment]
> 

反代没限制吧

**Comment by EvanLuo233** [comment]
建议直接传自己服务器或者找托管，不要用github，什么事情都解决了

**Comment by BA7JCM** [comment]
> argon_js_merged.js?ver=1.3.5:2
> 
> ```
>    Uncaught TypeError: $(...).tooltip is not a function
> at HTMLDocument.<anonymous> (argon.min.js?ver=1.3.5:18:689)
> at j (argon_js_merged.js?ver=1.3.5:2:29999)
> at k (argon_js_merged.js?ver=1.3.5:2:30313)
> ```
> 
> 这是报错

![image](https://user-images.githubusercontent.com/79561519/169682377-09f57862-5f71-4393-a0de-d1454982e70a.png)
这是我去访问你网站的时候console里面的报错

**Comment by Andy17269** [comment]
> > github开了防盗链
> 
> 他内置的几个cdn也都是GitHub的反代站 ![image](https://user-images.githubusercontent.com/79561519/169682303-989c0342-18f1-477e-ba13-d99c1571b24b.png) `/wp-content/themes/argon-theme-master/functions.php`第十五行到第十四行

Source Global CDN最近被人D了，具体去看 https://www.sourcegcdn.com/public/138.html

**Comment by Andy17269** [comment]
> > > github开了防盗链
> > 
> > 
> > 他内置的几个cdn也都是GitHub的反代站 ![image](https://user-images.githubusercontent.com/79561519/169682303-989c0342-18f1-477e-ba13-d99c1571b24b.png) `/wp-content/themes/argon-theme-master/functions.php`第十五行到第十四行
> 
> Source Global CDN最近被人D了，具体去看 https://www.sourcegcdn.com/public/138.html

正在修复

**Comment by BA7JCM** [comment]
> 建议直接传自己服务器或者找托管，不要用github，什么事情都解决了

cdn选择“不使用”就是从wordpress主题目录加载，但受服务器速度限制

**Comment by EvanLuo233** [comment]
还是自己建cdn比较稳定，还快，也便宜

**Comment by EvanLuo233** [comment]
@Andy17269 你跨域解决了吗

**Comment by Andy17269** [comment]
不是跨域

**Comment by Andy17269** [comment]
这报错根本不是

**Comment by Andy17269** [comment]
要是跨域样式根本加载不出来

**Comment by EvanLuo233** [comment]
就是跨域，你听我的。我之前也遇到了这个，font-awesome图标有这个问题

**Comment by BA7JCM** [comment]
> 不是跨域

![image](https://user-images.githubusercontent.com/79561519/169682456-0c678da8-adf5-44e9-a65f-f9afc8a1d79f.png)
你看这个图

**Comment by EvanLuo233** [comment]
CORS就是跨域

**Comment by Andy17269** [comment]
我试试

**Comment by EvanLuo233** [comment]
<img width="748" alt="Screen Shot 2022-05-22 at 14 43 28" src="https://user-images.githubusercontent.com/68590232/169682487-a7326cae-dcda-4291-a04d-53d9cedf4d6d.png">

**Comment by Andy17269** [comment]
我用的服务器+CDN，Sever没开防盗链

**Comment by EvanLuo233** [comment]
我也是的，CDN去开一下允许跨域

**Comment by Andy17269** [comment]
我刚整上，请问具体怎么办，谢谢

**Comment by BA7JCM** [comment]
> 我用的服务器+CDN，Sever没开防盗链

在`/wp-admin/admin.php?page=functions.php#header-id-7`里面设置`不使用`也能解决，就是速度慢点
![image](https://user-images.githubusercontent.com/79561519/169682650-95b41cfa-a6d5-4871-80ae-fdcfd017dd35.png)

**Comment by EvanLuo233** [comment]
> 我刚整上，请问具体怎么办，谢谢

我网站www.evanluo.top，用的cdn域名借朋友的，evan.beee.top/wp-content/themes/argon

我的是阿里云oss+cdn，网上有腾讯云的设置教程

**Comment by EvanLuo233** [comment]
> > 我用的服务器+CDN，Sever没开防盗链
> 
> 在`/wp-admin/admin.php?page=functions.php#header-id-7`里面设置`不使用`也能解决，就是速度慢点 ![image](https://user-images.githubusercontent.com/79561519/169682650-95b41cfa-a6d5-4871-80ae-fdcfd017dd35.png)

就是因为要速度快一点才会用cdn啊😂

**Comment by Andy17269** [comment]
稍等，正在部署CDN

**Comment by EvanLuo233** [comment]
不着急

**Comment by BA7JCM** [comment]
> > > 我用的服务器+CDN，Sever没开防盗链
> > 
> > 
> > 在`/wp-admin/admin.php?page=functions.php#header-id-7`里面设置`不使用`也能解决，就是速度慢点 ![image](https://user-images.githubusercontent.com/79561519/169682650-95b41cfa-a6d5-4871-80ae-fdcfd017dd35.png)
> 
> 就是因为要速度快一点才会用cdn啊😂



> 我刚整上，请问具体怎么办，谢谢

腾讯云cdn好像得自己添加响应头才行
![image](https://user-images.githubusercontent.com/79561519/169682741-03f1f84e-9977-457f-b23b-81a3b7b0ebf0.png)

**Comment by BA7JCM** [comment]
> 稍等，正在部署CDN

腾讯云的文档：https://cloud.tencent.com/document/product/228/41737#.E5.A4.B4.E9.83.A8.E5.8F.82.E6.95.B0

**Comment by Andy17269** [comment]
好了，谢谢博主！（对了，我刚刚申请您的友链

**Comment by Andy17269** [comment]
急着要把上边的配置状态按钮打开

**Comment by EvanLuo233** [comment]
好的，我也加一下你，我们几个互加一下吧

**Comment by Andy17269** [comment]
头部参数是Access-Control-Allow-Origin，取值是*即可

**Comment by BA7JCM** [comment]
> 好的，我也加一下你，我们几个互加一下吧

可以啊，不过我博客是我和朋友一起在管理，申请友链表单：https://gaoice.ba7jcm.live/friend/

**Comment by Andy17269** [comment]
> > 好的，我也加一下你，我们几个互加一下吧
> 
> 可以啊，不过我博客是我和朋友一起在管理，申请友链表单：https://gaoice.ba7jcm.live/friend/

提示已拒绝链接

**Comment by EvanLuo233** [comment]
好的，我博客https://www.evanluo.top

**Comment by Andy17269** [comment]
> > 好的，我也加一下你，我们几个互加一下吧
> 
> 可以啊，不过我博客是我和朋友一起在管理，申请友链表单：https://gaoice.ba7jcm.live/friend/

已经填写表了，通过下

**Comment by BA7JCM** [comment]
> > > 好的，我也加一下你，我们几个互加一下吧
> > 
> > 
> > 可以啊，不过我博客是我和朋友一起在管理，申请友链表单：https://gaoice.ba7jcm.live/friend/
> 
> 提示已拒绝链接

现在试试，我刚改了下配置

**Comment by BA7JCM** [comment]
> > > 好的，我也加一下你，我们几个互加一下吧
> > 
> > 
> > 可以啊，不过我博客是我和朋友一起在管理，申请友链表单：https://gaoice.ba7jcm.live/friend/
> 
> 已经填写表了，通过下

我在管理页面没看到申请啊。。。你是在https://gaoice.ba7jcm.live/friend/ 填的吗
![image](https://user-images.githubusercontent.com/79561519/169683065-07fdca3f-3110-4010-acc7-c192a5598844.png)

**Comment by EvanLuo233** [comment]
蚌埠住了，我按了好几次，多了好多邮件。欢迎加入我的电报群~~一共才三个人~~：[@anonymousland](https://t.me/anonymousland)

**Comment by BA7JCM** [comment]
> > > 好的，我也加一下你，我们几个互加一下吧
> > 
> > 
> > 可以啊，不过我博客是我和朋友一起在管理，申请友链表单：https://gaoice.ba7jcm.live/friend/
> 
> 已经填写表了，通过下

收到了好多条同样的申请。。。。。
![image](https://user-images.githubusercontent.com/79561519/169683305-186ed597-7f4f-43e4-8309-c2bbff842655.png)

**Comment by BA7JCM** [comment]
> 蚌埠住了，我按了好几次，多了好多邮件。欢迎加入我的电报群~一共才三个人~：[@anonymousland](https://t.me/anonymousland)

我差点以为我写的网站出bug了。。。。。。（这个表单是我自己用原生PHP手撸的）

**Comment by EvanLuo233** [comment]
大佬大佬

**Comment by EvanLuo233** [comment]
链接我加了，不过缓存刷新比较慢，过一会应该就能看到了

> > 蚌埠住了，我按了好几次，多了好多邮件。欢迎加入我的电报群~一共才三个人~：[@anonymousland](https://t.me/anonymousland)
> 
> 我差点以为我写的网站出bug了。。。。。。（这个表单是我自己用原生PHP手撸的）

**Comment by BA7JCM** [comment]
> 大佬大佬

算不上大佬，自己写的网站的美化还得靠我朋友帮忙（首页的美化就是我朋友帮我做的，这个网站功能和模板我写，美化他负责）

**Comment by EvanLuo233** [comment]
> > 大佬大佬
> 
> 算不上大佬，自己写的网站的美化还得靠我朋友帮忙（首页的美化就是我朋友帮我做的，这个网站功能和模板我写，美化他负责）

真厉害，我根本不会php，总之以后多多请教了！

**Comment by BA7JCM** [comment]
> > > 好的，我也加一下你，我们几个互加一下吧
> > 
> > 
> > 可以啊，不过我博客是我和朋友一起在管理，申请友链表单：https://gaoice.ba7jcm.live/friend/
> 
> 已经填写表了，通过下

弱弱问句你填的是哪个地址的表。。。目前这里没见到你填写的。。。。
![image](https://user-images.githubusercontent.com/79561519/169683640-ed679daf-a915-43f1-9ec2-062292c7850f.png)

**Comment by BA7JCM** [comment]
> > > 大佬大佬
> > 
> > 
> > 算不上大佬，自己写的网站的美化还得靠我朋友帮忙（首页的美化就是我朋友帮我做的，这个网站功能和模板我写，美化他负责）
> 
> 真厉害，我根本不会php，总之以后多多请教了！

我写的时候也是边上网查边写的，只学过一点PHP

**Comment by Andy17269** [comment]
好了，通过下吧

**Comment by BA7JCM** [comment]
> 好了，通过下吧

通过了，不出意外的话邮件也已经由程序自动发过去了，不过弱弱问句为啥要提交两次。。。。。。

**Comment by EvanLuo233** [comment]
因为你那个提交成功没有反馈，也没有任何提示，差点以为自己没提交。邮件有延迟

**Comment by BA7JCM** [comment]
> 因为你那个提交成功没有反馈，也没有任何提示，差点以为自己没提交。邮件有延迟
> […](#)
> On May 22, 2022, at 9:06 PM, BA7JCM ***@***.***> wrote: ﻿ 好了，通过下吧 通过了，不出意外的话邮件也已经由程序自动发过去了，不过弱弱问句为啥要提交两次。。。。。。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

其实是有反馈的，只是要等久点，提交之后要进行一些操作，服务器比较慢。。。。。。服务器在国内，但是需要调用微软的api发邮件，如果填了tg还要经过我在buyvm租的一台服务器访问tg api来发消息。。。

**Comment by Andy17269** [comment]
> > 因为你那个提交成功没有反馈，也没有任何提示，差点以为自己没提交。邮件有延迟
> > […](#)
> > On May 22, 2022, at 9:06 PM, BA7JCM _**@**_.***> wrote: ﻿ 好了，通过下吧 通过了，不出意外的话邮件也已经由程序自动发过去了，不过弱弱问句为啥要提交两次。。。。。。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.
> 
> 其实是有反馈的，只是要等久点，提交之后要进行一些操作，服务器比较慢。。。。。。服务器在国内，但是需要调用微软的api发邮件，如果填了tg还要经过我在buyvm租的一台服务器访问tg api来发消息。。。

整个提交中的提示

**Comment by BA7JCM** [comment]
> 因为你那个提交成功没有反馈，也没有任何提示，差点以为自己没提交。邮件有延迟
> […](#)
> On May 22, 2022, at 9:06 PM, BA7JCM ***@***.***> wrote: ﻿ 好了，通过下吧 通过了，不出意外的话邮件也已经由程序自动发过去了，不过弱弱问句为啥要提交两次。。。。。。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

![image](https://user-images.githubusercontent.com/79561519/169696923-0d60727f-952d-4833-9db0-c6e971750779.png)
这是提交之后的样子（截图是在开发&测试环境截的图，但是在实际环境也是这样的界面）

**Comment by BA7JCM** [comment]
> > > 因为你那个提交成功没有反馈，也没有任何提示，差点以为自己没提交。邮件有延迟
> > > […](#)
> > > On May 22, 2022, at 9:06 PM, BA7JCM _**@**_.***> wrote: ﻿ 好了，通过下吧 通过了，不出意外的话邮件也已经由程序自动发过去了，不过弱弱问句为啥要提交两次。。。。。。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.
> > 
> > 
> > 其实是有反馈的，只是要等久点，提交之后要进行一些操作，服务器比较慢。。。。。。服务器在国内，但是需要调用微软的api发邮件，如果填了tg还要经过我在buyvm租的一台服务器访问tg api来发消息。。。
> 
> 整个提交中的提示

这个我跟我朋友说一下，前端我不太会，我只会点PHP

**Comment by BA7JCM** [comment]
> > > 因为你那个提交成功没有反馈，也没有任何提示，差点以为自己没提交。邮件有延迟
> > > […](#)
> > > On May 22, 2022, at 9:06 PM, BA7JCM _**@**_.***> wrote: ﻿ 好了，通过下吧 通过了，不出意外的话邮件也已经由程序自动发过去了，不过弱弱问句为啥要提交两次。。。。。。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.
> > 
> > 
> > 其实是有反馈的，只是要等久点，提交之后要进行一些操作，服务器比较慢。。。。。。服务器在国内，但是需要调用微软的api发邮件，如果填了tg还要经过我在buyvm租的一台服务器访问tg api来发消息。。。
> 
> 整个提交中的提示

不过还是感谢建议

**Comment by BA7JCM** [comment]
@Andy17269 @EvanLuo233 刚刚在测试环境加了PHP实时输出，你们方便的时候来试试看效果？

**Comment by Andy17269** [comment]
好的，我看看

**Comment by Andy17269** [comment]
这个提交后的提示大了点吧.....应该可以缩小下吧

**Comment by BA7JCM** [comment]
> 

额。。。提交后的提示这个是我朋友美化的半成品。。。。。。最初始的样子是没有css的
@gaoicex 出来挨打（受虐滑稽）

**Comment by EvanLuo233** [comment]
感觉至少比之前好，其实加一个“提交成功”的提示就行了，没必要那么多详细信息

**Comment by EvanLuo233** [comment]
提交以后跳转到一个静态html页面，显示提交成功，就可以了。可以网上找一个html模版自己改改就行

**Comment by Andy17269** [comment]
对了，Argon主题有用户群吗(滑稽

**Comment by EvanLuo233** [comment]
没有吧，只有tg公告群，不能发言的

**Comment by Andy17269** [comment]
建一个（滑稽

**Comment by EvanLuo233** [comment]
tg？我们几个人太少了吧（受虐滑稽

还有其他人吗

**Comment by Andy17269** [comment]
Q群

**Comment by Andy17269** [comment]
> Q群

这样受众广（异想天开

**Comment by EvanLuo233** [comment]
我很少用q（滑稽

**Comment by BA7JCM** [comment]
> > Q群
> 
> 这样受众广（异想天开

既然都出到这了，tg不好吗（滑稽

**Comment by Andy17269** [comment]
我没tg

**Comment by EvanLuo233** [comment]
注册一个吧，tg还是挺方便的（（

**Comment by Andy17269** [comment]
很大一部分人应该没工具（指自己

**Comment by BA7JCM** [comment]
> 很大一部分人应该没工具（指自己

好家伙，看来你那的网络对GitHub挺友好的？

**Comment by EvanLuo233** [comment]
电信对github一直挺友好的
不过我路由器常年挂tz

**Comment by Andy17269** [comment]
用的Steam++（本身时不时就可以访问

**Comment by BA7JCM** [comment]
> 电信对github一直挺友好的 不过我路由器常年挂tz

我家里就是电信，学校宿舍也是电信，GitHub一样日常上不去，系楼的移动反而有时候挺快（非教育网）

**Comment by EvanLuo233** [comment]
建议搞个工具，有很多便宜的机场的。~~完了，github要变成群了~~

**Comment by Andy17269** [comment]
Q对国内环境好

**Comment by BA7JCM** [comment]
> 建议搞个工具，有很多便宜的机场的。~完了，github要变成群了~

仓库作者不知道会不会过会看着99+的未读邮件发呆（滑稽

**Comment by EvanLuo233** [comment]
主要是很多用argon的都有工具（（（）

**Comment by EvanLuo233** [comment]
solstice关闭了这个issue了吧，不会收到邮件了吧（不是很懂

**Comment by BA7JCM** [comment]
> 主要是很多用argon的都有工具（（（）

不少能来GitHub的都有工具吧，就国内对GitHub的友好程度

**Comment by BA7JCM** [comment]
> >

不知道，issue是关了，但我们这么你一条我一条，我邮箱是在响个不停的，仓库作者估计可能好不到哪去（没试过已任何一个仓库作者的身份收过issue邮件，我也不清楚，不过确实好像可以对issue设置不提醒
![image](https://user-images.githubusercontent.com/79561519/169805964-d08af072-1750-4fee-ac55-8cae58e6be0d.png)

**Comment by Andy17269** [comment]
嫌吵作者应该关了提醒（

**Comment by BA7JCM** [comment]
> 嫌吵作者应该关了提醒（

可能吧

**Comment by GaoiceX** [comment]
刚放学的我也看着你们留下的issue发愣

**Comment by solstice23** [comment]
可以去 github discussion 讨论，此讨论串我之前就 unsubscribe 了(
