### ISSUE TITLE
[Feature Request] 增加官网或交流群

### ISSUE THREAD

**Issue by Andy17269** [solstice23/argon-theme#489]
### 功能描述

这个主题很棒，但是我觉得应该整一个官网和Q群

### 附加说明

现在几乎有此主题一样大规模的用户在我看来没有几个，增加Q群可以增加本主题凝聚力。而官网则能更有<s>逼格</s>高大上。（如果工作量太大，作者可以找几个志同道合的Friend）

**Comment by solstice23** [comment]
目前已经有博客评论区，Github Issues / Discussions，TG 频道评论等交流途径了。暂没有开设群或官网的打算
