### ISSUE TITLE
[Feature Request] F# 和 Dockerfile 代码高亮支持

### ISSUE THREAD

**Issue by IllyaTheHath** [solstice23/argon-theme#492]
### 功能描述

[highlight.js](https://highlightjs.org/) 支持 F# 以及 Dockerfile 语言高亮，但是没有默认选中，希望可以加入对这两个语言的支持。
或者是否可以考虑加入 hightlight.js 自定义源功能，可以让用户自定义 hightlight.js 加载地址，，从而实现让用户自选语言高亮支持

**Comment by EvanLuo233** [comment]
建议自己改主题文件
