### ISSUE TITLE
建议主题取消引用Jsdelivr的资源[Bug] 

### ISSUE THREAD

**Issue by lyryblog** [solstice23/argon-theme#495]
### 主题版本

最新版本

### Bug 类型

该 Bug 是后端问题

### 浏览器

Chrome / Edge

### 普遍性

是

### 问题描述

引用cdn.jsdelivr.com的所有资源超时无响应，作者的博客也打不开

### 复现步骤

访问网站

### 附加说明

可以尝试更换其它CDN，或者改为可用的Jsdelivr链接，如fastly.jsdelivr.com.

**Comment by solstice23** [comment]
jsdelivr 本身只是一个可选项，不开启即可

**Comment by lyryblog** [comment]
![20220529_073659](https://user-images.githubusercontent.com/61700209/170845998-b7747d4b-b40c-454d-966f-4d346c56ba74.png)
这个是主题引用的吗？

**Comment by solstice23** [comment]
不是
