### ISSUE TITLE
升级1.3.5后，网站显示混乱

### ISSUE THREAD

**Issue by 6vision** [solstice23/argon-theme#496]
### Issue 内容

1.3.4版本能够正常显示网站，在线升级之后，网址就显示混乱了，请问怎么解决呀，
[![XMA46x.png](https://s1.ax1x.com/2022/05/29/XMA46x.png)](https://imgtu.com/i/XMA46x)

**Comment by huangwb8** [comment]
@6vision 这个问题很有可能是由于argon 1.3.5默认调用CDN有关。
这个CDN近期在中国大陆有问题，你可以改为下列选项或可成功，比如不使用或者用fastly那个都行。

![image](https://user-images.githubusercontent.com/35643122/170901849-83e0667b-60c9-4bc2-ab9b-39000b14b55e.png)

**Comment by Andy17269** [comment]
我自建了个CDN，腾讯的：https://cdn.wenlei.club/Argon-Theme/%theme_version% （选自定义即可输入）

**Comment by 6vision** [comment]
> @6vision 这个问题很有可能是由于argon 1.3.5默认调用CDN有关。 这个CDN近期在中国大陆有问题，你可以改为下列选项或可成功，比如不使用或者用fastly那个都行。
> 
> ![image](https://user-images.githubusercontent.com/35643122/170901849-83e0667b-60c9-4bc2-ab9b-39000b14b55e.png)

正解，我还网站回滚了，谢谢

**Comment by EvanNotFound** [comment]
可以 Mark as closed 了
