### ISSUE TITLE
[Bug] 重要错误

### ISSUE THREAD

**Issue by Andy17269** [solstice23/argon-theme#497]
### 主题版本

v1.5.4

### Bug 类型

该 Bug 是前端问题，且似乎和浏览器无关

### 浏览器

此问题与前端无关

### 普遍性

否，只出现在特定的网站，并且知道触发条件

### 问题描述

因Argon主题及文档默认使用的是JsdelivrCDN，所以因为GFW无法正常访问（主题可以切换，问题不大。但文档直接显示不出来）望解决问题

### 复现步骤

打开https://argon-docs.solstice23.top即可复现

### 截图

![网页捕获_1-6-2022_21012_argon-docs solstice23 top](https://user-images.githubusercontent.com/81066358/171410246-265d3f31-a2e7-4138-8bf3-7ac29a08714b.jpeg)

**Comment by solstice23** [comment]
CDN 是可选项

**Comment by Andy17269** [comment]
用的是jsdelivr的CDN，文档是docsify
//cdn.jsdelivr.net/npm/docsify-pagination/dist/docsify-pagination.min.js

**Comment by solstice23** [comment]
@Andy17269 站长可以选择是否开启，而我选择开启

**Comment by Andy17269** [comment]
我说的是文档，访问不了


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: solstice23 ***@***.***&gt;
发送时间: 2022年6月1日 22:26
收件人: solstice23/argon-theme ***@***.***&gt;
抄送: 干净T松鼠 ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[solstice23/argon-theme] [Bug] 重要错误 (Issue #497)





 
@Andy17269 站长可以选择是否开启，而我选择开启

**Comment by Andy17269** [comment]
文档打开加载不出，不是主题
