### ISSUE TITLE
[Feature Request] IP 属地显示

### ISSUE THREAD

**Issue by bytecaps** [solstice23/argon-theme#499]
### 功能描述

您好，关于评论，请问是否能添加一个 是否显示评论IP归属地的功能？

**Comment by solstice23** [comment]
这个需要IP库支持 基本需要付费第三方服务

**Comment by bytecaps** [comment]
> 这个需要IP库支持 基本需要付费第三方服务

这个有免费公开的接口的，例如：`http://ip-api.com/json/24.48.0.1?lang=zh-CN`

**Comment by solstice23** [comment]
评论区提供了相关 filter, 主题不会内置此功能

**Comment by Andy17269** [comment]
我这有插件，https://fatesinger.com/100958（自己试过，主题完美支持）

**Comment by bytecaps** [comment]
> 我这有插件，[https://fatesinger.com/100958（自己试过，主题完美支持）](https://fatesinger.com/100958%EF%BC%88%E8%87%AA%E5%B7%B1%E8%AF%95%E8%BF%87%EF%BC%8C%E4%B8%BB%E9%A2%98%E5%AE%8C%E7%BE%8E%E6%94%AF%E6%8C%81%EF%BC%89)

好的，谢谢，我去试试。

**Comment by Marukon** [comment]
> 我这有插件，[https://fatesinger.com/100958（自己试过，主题完美支持）](https://fatesinger.com/100958%EF%BC%88%E8%87%AA%E5%B7%B1%E8%AF%95%E8%BF%87%EF%BC%8C%E4%B8%BB%E9%A2%98%E5%AE%8C%E7%BE%8E%E6%94%AF%E6%8C%81%EF%BC%89)

谢谢分享，真的好用。
