### ISSUE TITLE
可以考虑下友情链接页面的开发

### ISSUE THREAD

**Issue by rateldev** [solstice23/argon-theme#51]
友情链接可能出现无头像的情况，中间部分没有头像，后面部分又有，看起来有些突兀

**Comment by solstice23** [comment]
确定不是头像链接错误吗

**Comment by rateldev** [comment]
哈哈，就是有的用户没有提供头像，然后就有了这个尴尬的局面
![image](https://user-images.githubusercontent.com/43286016/87747278-690c9980-c825-11ea-8e95-a2e491e9c1c4.png)

**Comment by youthriverside** [comment]
### 左侧那个就是友链一旦多了就需要拖动，我觉得这样很不舒服。可以让友链一直排下去吗

**Comment by solstice23** [comment]
已优化无头像情况

**Comment by solstice23** [comment]
> ### 左侧那个就是友链一旦多了就需要拖动，我觉得这样很不舒服。可以让友链一直排下去吗

修了
