### ISSUE TITLE
左侧小工具过于粗糙[doge]

### ISSUE THREAD

**Issue by youthriverside** [solstice23/argon-theme#52]
![image](https://user-images.githubusercontent.com/63176620/88352510-96f55f00-cd8c-11ea-8246-932bebd12dce.png)
![image](https://user-images.githubusercontent.com/63176620/88352528-a7a5d500-cd8c-11ea-9d9f-c6cd86ee4529.png)
右侧也有些粗糙  
* 建议：对小工具进行界面优化

**Comment by solstice23** [comment]
改了
