### ISSUE TITLE
[Bug] 文章卡片中文章描述截取长度错误

### ISSUE THREAD

**Issue by AH-dark** [solstice23/argon-theme#526]
### 主题版本

v1.3.5

### Bug 类型

该 Bug 是后端问题

### 浏览器

此问题与前端无关

### 普遍性

否，只出现在特定的网站，但触发条件未知

### 问题描述

当文章卡片通过文章内容截取摘要时，出现错误。

![image](https://user-images.githubusercontent.com/51253685/182130057-cd4cefae-4734-4f4e-ab23-0644e381843a.png)

在此配置条件下，未设置摘要的文章卡片出现以下状态：

![image](https://user-images.githubusercontent.com/51253685/182130260-c1af8a1f-6c33-4260-843c-07b4eea6b22c.png)

即文章卡片摘要字数比预设值高出数十倍。

站点地址为 <https://ahdark.com> ，目前仅在本站出现此问题。已尝试将WordPress回滚、去除全部插件、回滚主题等方法，均未解决。
尝试在当前环境调用 `wp_trim_words()` 函数，仍不可正常使用。
暂不确定问题是否有Argon引起或是内核引起。因站点结构复杂而难以判断。

但在此处使用这种方法截取摘要也是不合适的，WP有提供相关函数。

### 复现步骤

目前问题仅出现在 <https://ahdark.com> ，故只提供本站点环境。

除去部分确认不导致错误产生的私有插件以外，本站使用以下插件：

- Flamingo
- Source Global CDN
- Super Progressive Web Apps
- Sync QCloud COS
- W3 Total Cache
- WP Telegram
- WP-Matomo Integration
- WPJAM BASIC
- Yoast SEO

本站使用 WordPress 6.0.1 版本，回退到 6.0.0 、 5.9.3 版本均无法解决问题。

**Comment by BNQDZJ** [comment]
这个问题我也遇到了，我设的175它给我把全文列出来了
![QQ截图20220801204521](https://user-images.githubusercontent.com/64721413/182150795-545b36c1-d4ba-486c-8a93-d0eb03d34d10.png)
![QQ截图20220801204552](https://user-images.githubusercontent.com/64721413/182150809-c4d93d1d-3d85-46e7-81c9-47e90dddcfb2.png)

**Comment by BNQDZJ** [comment]
这个问题我也遇到了，我设的175它给我把全文列出来了
![QQ截图20220801204521](https://user-images.githubusercontent.com/64721413/182150795-545b36c1-d4ba-486c-8a93-d0eb03d34d10.png)
![QQ截图20220801204552](https://user-images.githubusercontent.com/64721413/182150809-c4d93d1d-3d85-46e7-81c9-47e90dddcfb2.png)

**Comment by kirigirisan** [comment]
+1 今天上博客发现截取也出了问题

**Comment by fubostudy** [comment]
+1

**Comment by Smith-Cruise** [comment]
一开始好的，我重新设置了一下主题，就这样了。
Wordpress 为最新版。

**Comment by Smith-Cruise** [comment]
> 这个问题我也遇到了，我设的175它给我把全文列出来了 ![QQ截图20220801204521](https://user-images.githubusercontent.com/64721413/182150795-545b36c1-d4ba-486c-8a93-d0eb03d34d10.png) ![QQ截图20220801204552](https://user-images.githubusercontent.com/64721413/182150809-c4d93d1d-3d85-46e7-81c9-47e90dddcfb2.png)

你这个字体怎么搞的，有教程吗，挺好看的。

**Comment by BNQDZJ** [comment]
> > 这个问题我也遇到了，我设的175它给我把全文列出来了 ![QQ截图20220801204521](https://user-images.githubusercontent.com/64721413/182150795-545b36c1-d4ba-486c-8a93-d0eb03d34d10.png) ![QQ截图20220801204552](https://user-images.githubusercontent.com/64721413/182150809-c4d93d1d-3d85-46e7-81c9-47e90dddcfb2.png)
> 
> 你这个字体怎么搞的，有教程吗，挺好看的。

https://github.com/lxgw/LxgwWenKai
然后我用的是npm.elemecdn.com的cdn

**Comment by Smith-Cruise** [comment]
> > > 这个问题我也遇到了，我设的175它给我把全文列出来了 ![QQ截图20220801204521](https://user-images.githubusercontent.com/64721413/182150795-545b36c1-d4ba-486c-8a93-d0eb03d34d10.png) ![QQ截图20220801204552](https://user-images.githubusercontent.com/64721413/182150809-c4d93d1d-3d85-46e7-81c9-47e90dddcfb2.png)
> > 
> > 
> > 你这个字体怎么搞的，有教程吗，挺好看的。
> 
> https://github.com/lxgw/LxgwWenKai 然后我用的是npm.elemecdn.com的cdn

主要css和js怎么写，方便贴个教程链接吗，或者这里写下。

**Comment by BNQDZJ** [comment]
> > > > 这个问题我也遇到了，我设的175它给我把全文列出来了 ![QQ截图20220801204521](https://user-images.githubusercontent.com/64721413/182150795-545b36c1-d4ba-486c-8a93-d0eb03d34d10.png) ![QQ截图20220801204552](https://user-images.githubusercontent.com/64721413/182150809-c4d93d1d-3d85-46e7-81c9-47e90dddcfb2.png)
> > > 
> > > 
> > > 你这个字体怎么搞的，有教程吗，挺好看的。
> > 
> > 
> > https://github.com/lxgw/LxgwWenKai 然后我用的是npm.elemecdn.com的cdn
> 
> 主要css和js怎么写，方便贴个教程链接吗，或者这里写下。

<link rel="stylesheet" href="https://npm.elemecdn.com/lxgw-wenkai-webfont/style.css" />

css:
*{
	font-family: "LXGW WenKai", sans-serif;
}

**Comment by BNQDZJ** [comment]
> > > > 这个问题我也遇到了，我设的175它给我把全文列出来了 ![QQ截图20220801204521](https://user-images.githubusercontent.com/64721413/182150795-545b36c1-d4ba-486c-8a93-d0eb03d34d10.png) ![QQ截图20220801204552](https://user-images.githubusercontent.com/64721413/182150809-c4d93d1d-3d85-46e7-81c9-47e90dddcfb2.png)
> > > 
> > > 
> > > 你这个字体怎么搞的，有教程吗，挺好看的。
> > 
> > 
> > https://github.com/lxgw/LxgwWenKai 然后我用的是npm.elemecdn.com的cdn
> 
> 主要css和js怎么写，方便贴个教程链接吗，或者这里写下。

`js:<link rel="stylesheet" href="https://npm.elemecdn.com/lxgw-wenkai-webfont/style.css" />`

**Comment by wlmqpsc** [comment]
+1 出现相同问题

**Comment by solstice23** [comment]
疑似 WP 上游问题

**Comment by AH-dark** [comment]
这个是WordPress 6.0.1的Bug，还是简体中文独有的Bug

**Comment by BNQDZJ** [comment]
那我换个英文版看看能不能解决

**Comment by Claradoll** [comment]
现在又变短了。。。

**Comment by wlmqpsc** [comment]
Bug已经没有了，并不是主题的问题

**Comment by Claradoll** [comment]
> > > > > 这个问题我也遇到了，我设的175它给我把全文列出来了 ![QQ截图20220801204521](https://user-images.githubusercontent.com/64721413/182150795-545b36c1-d4ba-486c-8a93-d0eb03d34d10.png) ![QQ截图20220801204552](https://user-images.githubusercontent.com/64721413/182150809-c4d93d1d-3d85-46e7-81c9-47e90dddcfb2.png)
> > > > 
> > > > 
> > > > 你这个字体怎么搞的，有教程吗，挺好看的。
> > > 
> > > 
> > > https://github.com/lxgw/LxgwWenKai 然后我用的是npm.elemecdn.com的cdn
> > 
> > 
> > 主要css和js怎么写，方便贴个教程链接吗，或者这里写下。
> 
> css: *{ font-family: "LXGW WenKai", sans-serif; }

如何在不改变代码块Consolas字体的前提下，更改其他部分的字体呢？
我尝试了几种过滤器，如:not(pre) {}或者 :not(code) {··· ！important} 都没有生效，仍会改变所有的字体样式，包括代码块。
但是像pre {}这种只改变代码块的css能够正常工作。
不知道是不是优先级的问题。

**Comment by BNQDZJ** [comment]
> > > > > > 这个问题我也遇到了，我设的175它给我把全文列出来了 ![QQ截图20220801204521](https://user-images.githubusercontent.com/64721413/182150795-545b36c1-d4ba-486c-8a93-d0eb03d34d10.png) ![QQ截图20220801204552](https://user-images.githubusercontent.com/64721413/182150809-c4d93d1d-3d85-46e7-81c9-47e90dddcfb2.png)
> > > > > 
> > > > > 
> > > > > 你这个字体怎么搞的，有教程吗，挺好看的。
> > > > 
> > > > 
> > > > https://github.com/lxgw/LxgwWenKai 然后我用的是npm.elemecdn.com的cdn
> > > 
> > > 
> > > 主要css和js怎么写，方便贴个教程链接吗，或者这里写下。
> > 
> > 
> > css: *{ font-family: "LXGW WenKai", sans-serif; }
> 
> 如何在不改变代码块Consolas字体的前提下，更改其他部分的字体呢？ 我尝试了几种过滤器，如:not(pre) {}或者 :not(code) {··· ！important} 都没有生效，仍会改变所有的字体样式，包括代码块。 但是像pre {}这种只改变代码块的css能够正常工作。 不知道是不是优先级的问题。

先看看npm的源有没有正常工作，elm的npm源有的节点缓存了403
然后尝试把css放在/wp-admin/customize.php 的额外CSS里面

**Comment by Cloudy-Kumori** [comment]
今天升级WordPress 6.4遇到了同样的问题，重装一下WordPress问题解决了
