### ISSUE TITLE
[Bug] 安装主题后报错

### ISSUE THREAD

**Issue by lutcraft** [solstice23/argon-theme#528]
### 主题版本

v1

### Bug 类型

该 Bug 是后端问题

### 浏览器

Chrome / Edge

### 普遍性

否，只出现在特定的网站，并且知道触发条件

### 问题描述

Fatal error: Uncaught Error: Call to undefined function register_block_type() in /var/www/html/wp-content/themes/argon/functions.php:2386 Stack trace: #0 /var/www/html/wp-includes/class-wp-hook.php(286): argon_init_gutenberg_blocks('') #1 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #2 /var/www/html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #3 /var/www/html/wp-settings.php(450): do_action('init') #4 /var/www/html/wp-config.php(95): require_once('/var/www/html/w...') #5 /var/www/html/wp-load.php(37): require_once('/var/www/html/w...') #6 /var/www/html/wp-blog-header.php(13): require_once('/var/www/html/w...') #7 /var/www/html/index.php(17): require('/var/www/html/w...') #8 {main} thrown in /var/www/html/wp-content/themes/argon/functions.php on line 2386

### 复现步骤

安装主题后出现此报错，随后博客无法启动

**Comment by solstice23** [comment]
@lutcraft Wordpress 什么版本

**Comment by lutcraft** [comment]
> 

wordpress:4.9.8

**Comment by lutcraft** [comment]
是否是我的版本过老

**Comment by solstice23** [comment]
@lutcraft 是

**Comment by lutcraft** [comment]
我看文档里写的Argon Theme 仅支持 Wordpress 4.4 及以上的版本，这个描述是否已过时。

**Comment by solstice23** [comment]
已更新
