### ISSUE TITLE
使用访问计数时似乎有问题

### ISSUE THREAD

**Issue by youthriverside** [solstice23/argon-theme#53]
![image](https://user-images.githubusercontent.com/63176620/88352918-2bac8c80-cd8e-11ea-94f9-1404471c06e8.png)
如图，我使用如下代码进行访问统计
```html
<script type="text/javascript""> 
if(localStorage.pagecount){localStorage.pagecount=Number(localStorage.pagecount)+1}else{localStorage.pagecount=1}document.write("欢迎你第"+localStorage.pagecount+"次访问"); 
</script>
```

**Comment by solstice23** [comment]
有 pjax，页面没有刷新，上一次 document.write 文档流还没关闭，所以会重复

不推荐 document.write 直接写文档流，弄个 div 显示不香吗
