### ISSUE TITLE
请求增加分页功能

### ISSUE THREAD

**Issue by Lovelumine** [solstice23/argon-theme#537]
### 功能描述

能够实现分页功能
使得生效

**Comment by solstice23** [comment]
https://github.com/solstice23/argon-theme/commit/b2fc5d096be9225f1b2ceaec4690a95b7ffc3bf6
已在 2.0-dev 中支持

**Comment by Lovelumine** [comment]
请问是加入`<!--nextpage-->`吗，为什么我加入之后后面的就消失了？

**Comment by solstice23** [comment]
dev 分支，目前还没有 Release

**Comment by Lovelumine** [comment]
好，谢谢！
