### ISSUE TITLE
The theme "argon" generated unexpected PHP debug output

### ISSUE THREAD

**Issue by Waga43** [solstice23/argon-theme#56]
Hello @solstice23. Great work you did with this theme. Thanks for all your efforts. I am experiencing this issue when trying to create a child theme from your argon theme as parent. If it's any help, my site is running on PHP 7.3.20 (which isn't the latest by the way). 

Here is the log:

Notice:  Undefined index: update_themeoptions in /home/***/public_html/wp-content/themes/argon/functions.php on line 3405

Warning:  Use of undefined constant TDC_PATH_LEGACY - assumed 'TDC_PATH_LEGACY' (this will throw an Error in a future version of PHP) in /home/***/public_html/wp-content/plugins/td-composer/td-composer.php on line 109

Notice:  Undefined variable: post_id in /home/***/public_html/wp-content/themes/argon/functions.php on line 273

Notice:  Undefined index: preview in /home/***/public_html/wp-content/themes/argon/functions.php on line 276

Notice:  Undefined index: no_post_view in /home/***/public_html/wp-content/themes/argon/functions.php on line 281

Notice:  Undefined index: argon_custom_theme_color in /home/***/public_html/wp-content/themes/argon/header.php on line 33

Thanks.

**Comment by solstice23** [comment]
Fixed.

--------------

```
Warning: Use of undefined constant TDC_PATH_LEGACY - assumed 'TDC_PATH_LEGACY' (this will throw an Error in a future version of PHP) in /home/***/public_html/wp-content/plugins/td-composer/td-composer.php on line 109
```
This should be a problem with this plugin, not the theme.
