### ISSUE TITLE
管理员登陆后，chrome浏览器无法留言[Bug] 

### ISSUE THREAD

**Issue by star2k** [solstice23/argon-theme#560]
### 主题版本

wordpress 5.8.3

### Bug 类型

不能判断 Bug 类型

### 浏览器

Chrome / Edge

### 普遍性

是

### 问题描述

管理员登陆后，chrome浏览器无法留言[Bug] 

### 复现步骤

是

### 截图

![image](https://user-images.githubusercontent.com/9582078/198586946-fdb7ad45-a4c1-418d-a00f-83e364112b3b.png)

**Comment by solstice23** [comment]
[FAQ](https://argon-docs.solstice23.top/#/faq)
![image](https://user-images.githubusercontent.com/23134847/198587110-9d198341-4e88-4277-80b6-ad2c23cb4a7f.png)
