### ISSUE TITLE
RankMath SEO Plugin Breaks WP Site

### ISSUE THREAD

**Issue by Waga43** [solstice23/argon-theme#57]
Hello @solstice23. Great work and I must commend your efforts on your argon theme. Its very feature rich.

I have been using your theme on my WP site for about 3 months now. About a month ago, RankMath updated their SEO Plugin and this broke my website. Apparently the new update isn't compatible with the argon theme. I have tried all my possible best to troubleshoot this issue but to no avail. The theme only works after I disable the RankMath plugin.

While I don't want to let go of your great theme (I took the trouble of editing it and making it English), I also love RankMath SEO Plugin because it does a very good job with ranking my site. 

Here is some logs:

    Plugin could not be activated because it triggered a fatal error.
    error: Cannot redeclare parse_user_agent() (previously declared in /home/***/public_html/wp-content/themes/argon/useragent-parser.php:17) in /home/***/public_html/wp-content/plugins/seo-by-rank-math/vendor/donatj/phpuseragentparser/src/UserAgentParser.php on line 26

![IMG_20200726_165133](https://user-images.githubusercontent.com/44534503/88483814-420b4180-cf62-11ea-8972-10f998086bef.jpg)

Could you please look into this issue. 

Thanks

From your non-Chinese fan. :)

**Comment by Waga43** [comment]
Well the problem obviously is from the RankMath SEO Plugin. I have downgraded to the last version 1.0.41 and all is well with my site.

I have also opened an issue with the developers. Perhaps they will take a look at this. 

Argon is a great theme.

**Comment by solstice23** [comment]
This is a function naming conflict problem, now it is fixed.
