### ISSUE TITLE
bing壁纸有时候会不显示，过个十几二十分之后又显示出来了

### ISSUE THREAD

**Issue by student-ice** [solstice23/argon-theme#577]
为什么啊

**Comment by Ghost-chu** [comment]
自己换个 Bing 壁纸 API。
比如说我在用 `https://www.guanyujiang.com/api/bingapi.php`

**Comment by student-ice** [comment]
这个你们不能直接在主题里更换了吗？
从源头解决

**Comment by solstice23** [comment]
@student-ice 主题不依赖第三方 api
