### ISSUE TITLE
[Bug] 文章不知道为什么排版炸了

### ISSUE THREAD

**Issue by Xalaok** [solstice23/argon-theme#579]
### 主题版本

v1.3.5

### Bug 类型

不能判断 Bug 类型

### 浏览器

Chrome / Edge

### 普遍性

是

### 问题描述

排版异常，图片盖在文字上
http://fishtouchers.freeee.ml/2023/01/04/%e5%88%9b%e5%bb%ba%e5%b1%9e%e4%ba%8e%e4%bd%a0%e8%87%aa%e5%b7%b1%e7%9a%84%e8%b0%b7%e6%ad%8c%e5%8d%9a%e5%ae%a2%ef%bc%81/

### 复现步骤

排版有问题的网页
http://fishtouchers.freeee.ml/2023/01/04/%e5%88%9b%e5%bb%ba%e5%b1%9e%e4%ba%8e%e4%bd%a0%e8%87%aa%e5%b7%b1%e7%9a%84%e8%b0%b7%e6%ad%8c%e5%8d%9a%e5%ae%a2%ef%bc%81/

### 截图

http://fishtouchers.freeee.ml/2023/01/04/%e5%88%9b%e5%bb%ba%e5%b1%9e%e4%ba%8e%e4%bd%a0%e8%87%aa%e5%b7%b1%e7%9a%84%e8%b0%b7%e6%ad%8c%e5%8d%9a%e5%ae%a2%ef%bc%81/

### 附加说明

http://fishtouchers.freeee.ml/2023/01/04/%e5%88%9b%e5%bb%ba%e5%b1%9e%e4%ba%8e%e4%bd%a0%e8%87%aa%e5%b7%b1%e7%9a%84%e8%b0%b7%e6%ad%8c%e5%8d%9a%e5%ae%a2%ef%bc%81/

**Comment by Fishtoucher6** [comment]
没事了，我搞好了，感谢作者的主题，很好看
