### ISSUE TITLE
希望增加文章第一张图片为特色图片的功能

### ISSUE THREAD

**Issue by Dragon-Lu** [solstice23/argon-theme#59]
首先感谢您的辛勤工作。如果文章设置了特色图片，在首页看上去会好看许多，但是特色图片只支持从媒体库选取，不能使用外链图片，由于服务器在国外，加载的速度非常慢。能否添加一个功能，使文章的第一张图片作为特色图片；将外链图片导入到媒体库的方法我目前还没有找到，仅有的几个插件也都失效了。所以希望可以实现这个功能，最终达到可以使用外链图片作为特色图片的目的。

**Comment by SuperNG6** [comment]
赞同，今天刚发现这个主题，觉得非常不错，但是测试了一下，有一些问题待解决，评论区的图片会超出边界，准备等再完善些开始使用

**Comment by solstice23** [comment]
已支持

> 支持将文章中第一张图片设为头图，支持每篇文章单独设置和跟随全局

**Comment by solstice23** [comment]
> 赞同，今天刚发现这个主题，觉得非常不错，但是测试了一下，有一些问题待解决，评论区的图片会超出边界，准备等再完善些开始使用
> ![kLuuEf](https://camo.githubusercontent.com/532281cceeb9113d962f68cabb5e50fb4a3a8c92/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f53757065724e47362f706963406d61737465722f755069632f6b4c757545662e706e67)

貌似是和之前评论 Markdown 插件不兼容，请问插件名是什么

**Comment by SuperNG6** [comment]
官方Jetpack插件自带的评论Markdown支持
在 2020年8月7日 +0800 AM4:14，solstice23 <notifications@github.com>，写道：
