### ISSUE TITLE
如何正确安装百度统计代码？

### ISSUE THREAD

**Issue by CurtainWei** [solstice23/argon-theme#597]
### Issue 内容

作者大大你好，请问应该如何正确安装百度统计代码？我遇到的问题与这个类似：#387 
百度统计提供的代码是这样的：
```html
<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?xxxxxxxxxxxxxx";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>
```
在Argon设置的“页头脚本”中直接添加这段代码，由于主题使用 pjax 方式加载页面，只能统计到访问首页的行为。
![image](https://user-images.githubusercontent.com/40741783/222886346-a5f0261a-1270-481c-aa9e-e7bbc5552d1b.png)
我尝试在百度统计中启用单页应用数据统计功能，还是只有首页的访问记录。
于是，我根据设置界面的指引，把页头脚本设置为
```html
<script>
var _hmt = _hmt || [];
window.pjaxLoaded = function(){
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?xxxxxxxxxxxxxx";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
}
window.pjaxLoaded();
</script>
```
设置之后，还是只有首页的访问记录。

**Comment by Suiyi-Light** [comment]
我把我正在使用的代码贴上来参考一下，忘了在哪里借鉴来的了
`<script>var _hmt = _hmt || [];
var hm = document.createElement("script");
hm.src = "https://hm.baidu.com/hm.js?xxx";
var s = document.getElementsByTagName("script")[0]; 
s.parentNode.insertBefore(hm, s);
</script>
<script>window.pjaxLoaded = function(){
_hmt.push(['_trackPageview', document.location.pathname+document.location.search+document.location.hash]);
}</script>
`
基本思路就是每次pjax刷新后通过_trackPageview函数上传一次当前url

**Comment by CurtainWei** [comment]
> 我把我正在使用的代码贴上来参考一下，忘了在哪里借鉴来的了
> 
> ```
> <script>var _hmt = _hmt || [];
> var hm = document.createElement("script");
> hm.src = "https://hm.baidu.com/hm.js?xxx";
> var s = document.getElementsByTagName("script")[0]; 
> s.parentNode.insertBefore(hm, s);
> </script>
> <script>window.pjaxLoaded = function(){
> _hmt.push(['_trackPageview', document.location.pathname+document.location.search+document.location.hash]);
> }</script>
> ```
> 
> 基本思路就是每次pjax刷新后通过_trackPageview函数上传一次当前url

谢谢你，这个方法确实有效
