### ISSUE TITLE
左侧栏中的“文章”指向链接错误

### ISSUE THREAD

**Issue by HughQuain** [solstice23/argon-theme#599]
### Issue 内容

我使用主题，创建了一个空白页面设置为留言板（/message）
之后，创建一个静态页面设置为首页，新建一个空白页面准备设置为文章页（/article）
之后我发现可能是我之前某个我不知晓的错误操作，主题里已经把留言板页面设置为文章页了
于是我将新建的（/article）设置为文章页，这时候，我在自定义里的菜单里新建一个指向文章页的链接项目，是能够指向正确的（/article）的
但是在左侧栏中与“分类”和“标签”并排的“文章”按钮处，当我点击时它仍然链接的是（/message）页面，我不知道这里的链接应该如何修改
谢谢大佬了

**Comment by Suiyi-Light** [comment]
修改主题设置页面的
归档页面链接

**Comment by HughQuain** [comment]
> 了解了，谢谢您的回复

**Comment by HughQuain** [comment]
> 修改主题设置页面的 归档页面链接
谢谢大佬，明白了
