### ISSUE TITLE
[Bug] 评论失败发送，未知原因

### ISSUE THREAD

**Issue by happysj2202** [solstice23/argon-theme#611]
### 主题版本

v1.3.5

### Bug 类型

不能判断 Bug 类型

### 浏览器

Chrome / Edge

### 普遍性

是

### 问题描述

前台无法评论，但在后台可以正常评论

### 复现步骤

评论

### 截图

![image](https://github.com/solstice23/argon-theme/assets/19954880/daa17329-bc47-4b3d-957c-4d1c60324ea5)

### 附加说明

运行环境：群晖
wordpress来源：群晖套件
wordpress版本：5.8.3

**Comment by Asukaaa648** [comment]
同问，我也是群晖套件用该主题无法发送评论，其他主题可以正常发送

**Comment by womenyiqijugeliziba** [comment]
把wordpress自带的评论-有人发表评论时，取消掉。就可以了

**Comment by Cefathiamidine** [comment]
同问，其他主题可以直接在前台评论，但是采用argon后，前台提示 评论发送失败-未知原因，只能在网页后台发评论

**Comment by Cefathiamidine** [comment]
> 同问，其他主题可以直接在前台评论，但是采用argon后，前台提示 评论发送失败-未知原因，只能在网页后台发评论
![image](https://github.com/solstice23/argon-theme/assets/152960195/7956786c-f138-4348-beb4-58e3b5470646)
![image](https://github.com/solstice23/argon-theme/assets/152960195/2e8d845c-36ce-4194-a798-260d4828fff4)
我这边是报了一个400错误

**Comment by kingpluginser** [comment]
Access to XMLHttpRequest at 'https://vmhost.cc/z-40x.html' (redirected from 'http://lgk111.ccccocccc.cc/wp-admin/admin-ajax.php') from origin 'http://lgk111.ccccocccc.cc' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
请问这个是什么原因？

**Comment by Dancying** [comment]
可以看到控制台发起的 POST 请求地址为 ： http://192.168.6.126/wp-admin/admin-ajax.php

实际应该发起的正确 POST 请求地址应为 ： http://192.168.6.126/wordpress/wp-admin/admin-ajax.php

所以出错的原因是因为没有找到 `/wordpress/wp-admin/admin-ajax.php` 文件

解决方式 ： 在 WordPress 后台 **Argon 主题选项** 中设置 `WordPress 安装目录` 的值即可
![image](https://github.com/solstice23/argon-theme/assets/39695373/eac9871d-405f-4e1a-841f-c9e2694cd906)

此单可关闭
