### ISSUE TITLE
[Bug] WordPress升级到6.2.2版本后报错

### ISSUE THREAD

**Issue by CurtainWei** [solstice23/argon-theme#613]
### 主题版本

v1.3.5

### Bug 类型

不能判断 Bug 类型

### 浏览器

此问题与前端无关

### 普遍性

是

### 问题描述

WordPress从6.2.1升级到6.2.2版本后，前端页面上方显示以下错误信息：
`Warning:  Undefined array key "HTTP_USER_AGENT" in /.../wp-content/themes/argon/header.php on line 45`
PHP版本为8.1

### 复现步骤

WordPress从6.2.1升级到6.2.2版本，访问除后台以外的任意页面都会出现这个问题。将WordPress回退到6.2.1版本后问题消失。

**Comment by FurryRbl** [comment]
我的 Wordpress 也是 **6.2.2** 版本，没有你说的问题欸

我的 PHP 版本是 **8.1.12**

而且这几段代码不应该会出现问题

https://github.com/solstice23/argon-theme/blob/94598137efa7c48d323cd8f4dabf49967d57953a/header.php#L45-L47

**Comment by CurtainWei** [comment]
> 

谢谢你的回答！这个问题确实有点奇怪，我的 PHP 版本是 8.1.27.
我刚刚又尝试重新升级了一下 WordPress，这次就没有出现这个问题啦，有可能是我这里的环境问题吧。
