### ISSUE TITLE
"图片放大预览"功能无效

### ISSUE THREAD

**Issue by sugar-zero** [solstice23/argon-theme#64]
"图片放大预览"功能无效，点击图片会直接打开媒体所在的页面(我是使用oss，点击后直接跳到oss链接了)，而不是打开一个类似于modal框的东西去查看大图
看完后还需要在浏览器返回上一页才能回到文章页面

**Comment by solstice23** [comment]
图片是不是加了链接了

**Comment by sugar-zero** [comment]
wp从媒体库添加图片不是默认会链接到图片地址的嘛，然后我是传到alioss的，现在点击图片就是直接跳到oss链接了
如果我取消掉图片的媒体链接点开就没问题，但是一般我是放缩略图的，不链接媒体文件点开也是缩略图
