### ISSUE TITLE
和《终极会员》插件的冲突？

### ISSUE THREAD

**Issue by lysowc** [solstice23/argon-theme#651]
### Issue 内容

主题和《终极会员》插件，貌似存在css冲突，在账号等页面，会出现页面无法显示的情况。页面表单已经加载出来了，但是无法显示，需要增加css :  opacity: 1; 解决，但是有些页面增加了css : opacity: 1; 之后页面还是无法显示，打开F12后，拖动一下F12的上下位置，页面又显示出来了

**Comment by matthews84** [comment]
主题最重要的就是持续更新，没必要死磕这个，换一个吧，个人建议。

**Comment by huangwb8** [comment]
@lysowc 

在Argon主题中，我使用的是ErphpDown插件。

我在《[Docker系列 WordPress系列 VIP订阅](https://blognas.hwb0307.com/linux/docker/3587)》中介绍了关于多用户与行为限制的测试。设置细节可见：《[Docker系列 WordPress系列 基于ErphpDown的VIP订阅](https://blognas.hwb0307.com/linux/docker/4238)》。

我的会员功能和多帐户功能已经测试了快1年了，目前感觉挺稳的。 仅供参考哈！
