### ISSUE TITLE
最新版argon-theme与插件Hermit X不兼容

### ISSUE THREAD

**Issue by xiaomage2000** [solstice23/argon-theme#67]
最新版argon-theme(0.994)与插件Hermit X不兼容，具体表现为：
主题开启Pjax，Hermit X开启全局加载后（不全局加载不行，如果不全局加载的话控制台会报错，导致每点击一个连接都会让整个页面重新加载），在页面首次加载的情况下，点击侧边栏的功能切换（比如现在是站点概览，要切换到功能上），都会导致页面重新加载，同时浏览器地址栏会跟上类似#leftbar_tab_tools的锚点；而当查看其他页面后，不是首次加载时，或者是已经触发过重新加载后，点击侧边栏切换功能就不会再次重新加载了。期间Hermit X一直工作正常，chrome，新Edge，Firefox下都能触发。
我这边基本排除了其他插件的影响，把其他插件都停用了还是能出现。
Hermit X也算是个比较常用的wp插件，希望看到可以修复一下，谢谢！
问题页面：[https://blog.xmgspace.me](https://blog.xmgspace.me)

**Comment by suiyi-light** [comment]
https://github.com/solstice23/argon-theme/issues/27
之前好像有个类似的问题，
我也希望作者能够修复下

**Comment by xiaomage2000** [comment]
> #27
> 之前好像有个类似的问题，
> 我也希望作者能够修复下

Hermit X就是Aplayer的wp移植版...之前那位遇到的也是这个问题，用之前那位的解决方法暂时解决了
我搭了个测试站 https://wp.baipiaoguai.shop/ 还是能复现的，希望作者能查看修复下~

**Comment by solstice23** [comment]
准备换新的 pjax 方案，还要修改一些地方

**Comment by solstice23** [comment]
已更换 pjax 方案
