### ISSUE TITLE
关于隐藏顶部导航栏的建议

### ISSUE THREAD

**Issue by SuperNG6** [solstice23/argon-theme#68]
在浏览内容区域，导航栏占的地方太大了，影响内容展示，我觉得可以增加一个设置选项 ` [导航栏固定，不出现在内容区域]`或
````网页在向下方滚动的时候，顶部的导航条会自动收起来（隐藏）；网页在向上方滚动的时候，顶部的导航条再自动出现（显示）。这样就能给我们的页面更多的空间，视野更加开阔````
![ZkVSvt](https://gitee.com/sleele/pic/raw/master/uPic/2020-08-07/ZkVSvt.png)
![7rBWKO](https://gitee.com/sleele/pic/raw/master/uPic/2020-08-07/7rBWKO.png)

**Comment by foamzou** [comment]
相比与顶部占用，我倒觉得宽度不够，左右两侧留白太多了，文章宽度太窄。

**Comment by solstice23** [comment]
已增加 "滚动时自动折叠顶栏" 设置项
