### ISSUE TITLE
已迁移至argon-theme，反馈几个比较影响体验的问题

### ISSUE THREAD

**Issue by SuperNG6** [solstice23/argon-theme#76]
首先感谢作者的爆肝更新，在本地测试了一周，观感提升明显，今天正式迁移到线上，但是目前还有一些问题待完善
[sleele的博客:https://sleele.com](https://sleele.com/)
### 1、主题色为黑色，在夜间模式下，文字可见度差
![Xnip2020-08-12_14-07-20](https://cdn.jsdelivr.net/gh/SuperNG6/pic@master/uPic/2020-08-12/Xnip2020-08-12_14-07-20.jpg)
![Xnip2020-08-12_14-05-38](https://cdn.jsdelivr.net/gh/SuperNG6/pic@master/uPic/2020-08-12/Xnip2020-08-12_14-05-38.jpg)
![Xnip2020-08-12_14-04-42](https://cdn.jsdelivr.net/gh/SuperNG6/pic@master/uPic/2020-08-12/Xnip2020-08-12_14-04-42.jpg)
![Xnip2020-08-12_14-20-44](https://cdn.jsdelivr.net/gh/SuperNG6/pic@master/uPic/2020-08-12/Xnip2020-08-12_14-20-44.jpg)
### 2、在移动设备上，WordPress自带的文章引用会超出显示边界，导致显示出错，文章滑动混乱
![WechatIMG13](https://cdn.jsdelivr.net/gh/SuperNG6/pic@master/uPic/2020-08-12/WechatIMG13.jpeg)
![Xnip2020-08-12_14-21-13](https://cdn.jsdelivr.net/gh/SuperNG6/pic@master/uPic/2020-08-12/Xnip2020-08-12_14-21-13.jpg)
### 3、在已登录的情况下，使用`Q2W3 Fixed Widget`插件固定小工具，会显示错位
![Xnip2020-08-12_14-12-22](https://cdn.jsdelivr.net/gh/SuperNG6/pic@master/uPic/2020-08-12/Xnip2020-08-12_14-12-22.jpg)
未登录的情况下使用`Q2W3 Fixed Widget`插件固定小工具，导航栏出现时右侧工具栏不会自动下移，会被导航栏遮盖
![Xnip2020-08-12_14-13-47](https://cdn.jsdelivr.net/gh/SuperNG6/pic@master/uPic/2020-08-12/Xnip2020-08-12_14-13-47.jpg)

**Comment by SuperNG6** [comment]
还有两个细节问题
### 1、大部分移动设备的浏览器因为地址栏和工具栏的缘故，会导致`argon-theme`缩放壁纸，造成顿挫
我录了一段视频，iPad和手机都会出现这种情况
https://www.bilibili.com/video/BV17K4y1Y7Jm/
### 2、引用评论和昵称过长会导致文字重叠
复现地址：https://sleele.com/2018/12/01/hackintosh/
![Xnip2020-08-12_19-55-02](https://cdn.jsdelivr.net/gh/SuperNG6/pic@master/uPic/Xnip2020-08-12_19-55-02.jpg)

### 3、我这里会出现`WP Super Cache`无法生成缓存的情况
更换别的主题可以生成，不知道是不是和pjax有关
![Xnip2020-08-12_19-57-28](https://cdn.jsdelivr.net/gh/SuperNG6/pic@master/uPic/Xnip2020-08-12_19-57-28.jpg)

还有一个小建议，可以加入评论点赞功能，挺实用的，期待正式版的早日来临

**Comment by solstice23** [comment]
1. 已修复，现在判断深色用的是简单的判断灰度，后续会换颜色对比度算法
2. 修了
3. 考虑内置小工具固定功能
4. 现在壁纸实现用的是伪元素，这个有点玄学，可能和伪元素高度设置或者 transition 有关
5. 已修复，现在会自动折行
6. 也有点玄学，抽空下个插件调调看

**Comment by solstice23** [comment]
关于 WP Super Cache 无法生成的问题：

在代码中有地方对 POST 全局变量进行了写入，导致插件误认为是 POST 请求而不缓存

已修复

**Comment by SuperNG6** [comment]
> 关于 WP Super Cache 无法生成的问题：
> 
> 在代码中有地方对 POST 全局变量进行了写入，导致插件误认为是 POST 请求而不缓存
> 
> 已修复

感谢，经测试已正常缓存。提个建议，目前相关文章推荐的数量太多了，一般三个足以，希望可以加入`相似文章`数量设置

**Comment by solstice23** [comment]
> > 关于 WP Super Cache 无法生成的问题：
> > 在代码中有地方对 POST 全局变量进行了写入，导致插件误认为是 POST 请求而不缓存
> > 已修复
> 
> 感谢，经测试已正常缓存。提个建议，目前相关文章推荐的数量太多了，一般三个足以，希望可以加入`相似文章`数量设置，位置建议放在评论区前，评论多的文章容易看不到`相似文章推荐`

已加入
