### ISSUE TITLE
邮件通知不起作用

### ISSUE THREAD

**Issue by loicaplay** [solstice23/argon-theme#77]
在评论下面的复选框邮件通知勾选后发评论没收到任何邮件。

不论是在作者的网站 https://solstice23.top/archives/444 ，还是在我自己的网站https://magisword.net/i-have-something-to-say/ 都不行。

请问这个需要什么配置吗？

**Comment by solstice23** [comment]
安装 WP Mail SMTP 或别的 SMTP 插件

我这里是可以的
