### ISSUE TITLE
新版本的banner问题反馈

### ISSUE THREAD

**Issue by mocehu** [solstice23/argon-theme#8]
1.banner打字机效果开启后banner标题消失
2.页面背景Banner透明化关闭后会出现如图所示的现象（不知道怎么描述），我会把图片发给你的

**Comment by solstice23** [comment]
> 2.页面背景Banner透明化关闭后会出现如图所示的现象（不知道怎么描述），我会把图片发给你的
你是不是设置了 Banner 背景

**Comment by mocehu** [comment]
是啊，更新主题后默认关闭了，然后就发现了这个问题

**Comment by mocehu** [comment]
> > 1.banner打字机效果开启后banner标题消失
> 
> 无法复现，可能是 js 没有被加载？
> 
> > 2.页面背景Banner透明化关闭后会出现如图所示的现象（不知道怎么描述），我会把图片发给你的
> 
> 你是不是设置了 Banner 背景

好吧，打字机好像可以了，有点玄学
