### ISSUE TITLE
Argon与插件Hermit X(APlayer)的兼容性

### ISSUE THREAD

**Issue by Shanwer** [solstice23/argon-theme#84]
这是本人的博客，为Argon的最新版本，我发现说说在首页进入说说（文章也是）刷新一次才能加载出Hermit X配置的音乐播放器，而在首页可以直接加载音乐播放。此外，如何在播放了Hermit X的音乐之后离开页面（说说）停止播放？比如在说说播放之后回到首页仍然在播放Hermix的音乐
https://blog.shanwer.top/

**Comment by suiyi-light** [comment]
在页首或页脚加下重载函数
`<script>window.pjaxLoaded = function(){
reloadHermit()}</script>`

**Comment by Shanwer** [comment]
> 在主题设置中页首或页脚脚本加下重载函数
> `<script>window.pjaxLoaded = function(){ reloadHermit()}</script>`

谢谢，已经好了
