### ISSUE TITLE
Banner 背景图和页面背景冲突

### ISSUE THREAD

**Issue by 52Lau** [solstice23/argon-theme#88]
单纯设置页面背景是不会生效的,设置了Banner 背景图是正常,

背景不透明度
Banner 透明化

需要 设置了页面背景才会生效

另外--bing--不生效

如果后面更新了,请回复下,麻烦了

**Comment by migchar** [comment]
Banner设置 --bing-- 每日一图后需要在页面背景中关闭“Banner透明化”才会生效。

**Comment by solstice23** [comment]
> 单纯设置页面背景是不会生效的,设置了Banner 背景图是正常,

两个设置是独立的，背景图被 Banner 遮住了，往下拉就可以看到。

> 背景不透明度
> Banner 透明化
> 
> 需要 设置了页面背景才会生效

不然呢

> 另外--bing--不生效

> Banner设置 --bing-- 每日一图后需要在页面背景中关闭“Banner透明化”才会生效。

**Comment by migchar** [comment]
> 不然呢
> 
> > 另外--bing--不生效
> 
> > Banner设置 --bing-- 每日一图后需要在页面背景中关闭“Banner透明化”才会生效。

啊 我是回复他关于 --bing-- 不生效的问题

**Comment by solstice23** [comment]
> > 不然呢
> > > 另外--bing--不生效
> > 
> > 
> > > Banner设置 --bing-- 每日一图后需要在页面背景中关闭“Banner透明化”才会生效。
> 
> 啊 我是回复他关于 --bing-- 不生效的问题

我这里是直接 Copy 你的话来回复他了，加了引用 😂
