### ISSUE TITLE
问题反馈和建议

### ISSUE THREAD

**Issue by Hdvjcvjff** [solstice23/argon-theme#9]
问题：文章预览的时候阅读统计也会算进去
建议：加个过滤管理员的选项，这样文章的阅读统计会更准确

**Comment by gitzwt** [comment]
加个页脚备案号

**Comment by solstice23** [comment]
> 问题：文章预览的时候阅读统计也会算进去
> 建议：加个过滤管理员的选项，这样文章的阅读统计会更准确

已更新

**Comment by Hdvjcvjff** [comment]
感谢更新！可是我刚刚尝试访问我的文章依然会计数，是哪里需要设置吗？我没有找到相关设置

**Comment by solstice23** [comment]
> 感谢更新！可是我刚刚尝试访问我的文章依然会计数，是哪里需要设置吗？我没有找到相关设置

文章发布前预览不会计数

**Comment by Hdvjcvjff** [comment]
懂了，发布后的文章查看还是会计数；我是希望发布后的文章，管理员查看也不会计数。
