### ISSUE TITLE
代码块或预格式化块中的内容会被识别为短代码

### ISSUE THREAD

**Issue by ADD-SP** [solstice23/argon-theme#93]
## 复现步骤

在代码块或预格式化块中输入
```
2020/01/20 22:56:30 [alert] 24289#0: *30
```

查看预览效果
![Snipaste_2020-09-20_17-59-32](https://user-images.githubusercontent.com/44437200/93708713-11fbab80-fb6b-11ea-96fa-d2a744b17d1e.png)

## 环境

* Mysql：8.0.21
* Php: 7.4
* Wordpress: 5.5.1
* OS：Ubuntu 18.04
* 主题版本：1.0.3
* 所用的代码高亮插件：[Syntax-highlighting Code Block (with Server-side Rendering)](https://github.com/westonruter/syntax-highlighting-code-block)
* 主题相关设置：未使用主题提供的代码高亮功能

**Comment by solstice23** [comment]
WP 的锅，WP 解析短代码不会考虑是否在代码块内
Argon 提供了 [noshortcode](https://argon-docs.solstice23.top/shortcode/noshortcode) 短代码来解决这个问题
