### ISSUE TITLE
第一张图片设为头图 能否推广到 允许用户选择第N张图片设为头图

### ISSUE THREAD

**Issue by crowya** [solstice23/argon-theme#94]
WordPress自带的特色图片功能无法通过URL设置头图，只能选择媒体库中的图片；
然而很多图片是通过图床的URL插入的，设置特色图片的过程异常繁琐；
第一张图片设为头图的功能提供了很大方便，但是能否推广到第N张图片呢？
希望能够在每篇文章的设置中允许用户选择第N张图片设为头图。

**Comment by solstice23** [comment]
如果这样的话这个功能就失去了它原本的意义：为未设置头图的文章设置一张缺省头图，文章中的单独控制选项是为了"某篇特定文章不想显示头图“这种情况
可以使用插件优化设置外链头图的过程，例如 `External Media without Import` 插件
