### ISSUE TITLE
第一次打开网站很慢。感觉在加载cdn或者谷歌字体还是什么的？

### ISSUE THREAD

**Issue by lweein** [solstice23/argon-theme#95]
作者好。

我的博客地址是 https://www.lweein.cn 

有两个小问题

1. 在首次打开的时候，感觉都在加载字体或者css文件导致很慢。我上传了一个截图。

能说一下如何避免或者规避么？让加载速度可以提高的更快一点。

![image](https://user-images.githubusercontent.com/13096524/94354137-d8ff9180-00aa-11eb-80af-af3686cabe17.png)

2. 设置特色图片之后，在首页并不会显示出来。一直都是黑色的背景，我放了一个截图说明。请问是哪里配置不对么？

![image](https://user-images.githubusercontent.com/13096524/94354161-fc2a4100-00aa-11eb-8748-3f9a77fde1eb.png)

**Comment by solstice23** [comment]
1. 已增加禁用 Google 字体选项
2. 已修复
