### ISSUE TITLE
[功能建议] 移动端 顶栏和浮动操作的菜单按钮外观相同 用户可能会产生困惑

### ISSUE THREAD

**Issue by ppqing** [solstice23/argon-theme#98]
![screenshot2](https://user-images.githubusercontent.com/22339849/95770695-61f20c00-0cec-11eb-8381-116ffccc26a3.png)

两个按钮指向不同的功能，但是却有着相同的外观，均为三条横线。用户可能会产生困惑。

另外一个小建议，从交互设计的角度，移动端不宜设计两个一级菜单入口，两个合并成一个可能是更合适的选择。

**Comment by solstice23** [comment]
早就想合并了，就是不知道合并成什么样，有建议吗（

**Comment by ppqing** [comment]
> 早就想合并了，就是不知道合并成什么样，有建议吗（

提供三个思路方向~

1. “顶部导航”和“左侧栏菜单”的功能重合度较高，可以考虑解耦，仅保留其中一个。删除重复部分后，剩余的子项合并到个人信息中。

2. 左上角按钮功能移至右上角，换为搜索图标。然后将菜单中的 “搜索” 改为 文本框，其余的菜单项在搜索框下面以类似于“搜索推荐”的方式展示。此时左上角的按钮可以空闲出来绑定侧滑菜单。

3. 把右上角的博客名称改为作者名字或头像，点击后展示作者信息。其余菜单项全部放入侧滑栏中，绑定到左上角的按钮上。

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/95861736-712c9480-0d94-11eb-9032-0f0b02bb13cb.png)

大概写了下，感觉还有点丑，现在没时间，等周末再更

**Comment by solstice23** [comment]
done
