### ISSUE TITLE
[问题反馈]关于主题设置中的Meta信息设置项

### ISSUE THREAD

**Issue by xiaomage2000** [solstice23/argon-theme#99]
在主题设置页面中，文章 Meta 信息设置项里面，“第二行”这里是空白的，并且第一行的Meta信息不能拖动到第二页，只能从第一页的“显示”和“不显示”之间拖动，请问是Bug吗，还是就是这样设计的？
如图，绿框圈出的第二行是空白的；第一行中的Meta信息不能拖动到第二页（如红框圈出的所示）
![files](https://user-images.githubusercontent.com/13915895/95868828-4135bf00-0d9d-11eb-8f35-310a1a3aba1c.png)

**Comment by solstice23** [comment]
第二行只有字数和阅读时间
